### ISSUE TITLE
Question: What is Ignore Special Class in the Trainer Editor?

### ISSUE THREAD

**Issue by JohnTitor95** [kwsch/pk3DS#101]
See Title.

**Comment by kwsch** [comment]
https://github.com/kwsch/pk3DS/blob/3b2bd96d3c58d17e1341f1417c518ea1702af855/pk3DS/Legality/Legal.cs#L101-L261

skips certain trainer classes for randomization so a garbage trainer doesn't turn into Hau and Hau doesn't turn into a swimmer.

**Comment by JohnTitor95** [comment]
Cool, thanks a lot. It's working really well! Thanks for all the hard work!
