### ISSUE TITLE
Level modifier for Trainer's pokemon not working.

### ISSUE THREAD

**Issue by JohnTitor95** [kwsch/pk3DS#104]
The level modifier for Trainer's Pokemon does not seem to consistently work. Some Battles seem to be increased, while other do not. Specifically, a couple of battles with Hau were increased, while most other battles are not. Looking at  it, it seems as thought important battles such as elite 4, hau, etc, are the only modified battles when it comes to levels. Also, for more specificity, im talking about the option that increases the level of trainer's pokemon by a %. Set mine to around 25%, but hit randomize twice. Not sure if that double randomization is what is killing the effect.

**Comment by JohnTitor95** [comment]
I've redone the trainers randomization, this time being careful not to hit randomize more than once. All battles are seemingly working as intended. However, i was unable to reproduce the issue by hitting randomize more than once.

**Comment by kwsch** [comment]
```
if (CHK_Level.Checked)
    pk.Level = (int)(pk.Level*(100 + NUD_LevelBoost.Value))/100;
```

should be functioning correctly in SMTE on the latest commits

**Comment by JohnTitor95** [comment]
Closing issue for now, because issue is not reproducible.
