### ISSUE TITLE
Request: Good moves

### ISSUE THREAD

**Issue by XtreemLiam** [kwsch/pk3DS#105]
In the sun and moon editor, I want moves equal to thier level, not op moves, not moves from level 1. If there is a way for this, please tell me.

**Comment by kwsch** [comment]
That's what "Current Levelup Moves" does.

**Comment by XtreemLiam** [comment]
Wheres that? Only have dont randomize, fully random, use level up moves ( Only does first four moves) or op moves?

**Comment by kwsch** [comment]
Recompile the latest version, don't use a random version you found on the internet. If you are unable to compile, please [use the CI server to download the latest commit](http://teamcity.projectpokemon.org/).

Has been fixed for over a month: https://github.com/kwsch/pk3DS/issues/77
