### ISSUE TITLE
pk3DS doesn't work anymore after some edits

### ISSUE THREAD

**Issue by GinKamas** [kwsch/pk3DS#108]
Hello! 
After I did some edits on the moves/pokemon/trainers of a SMrom and closed pk3DS, the application didn't want to open again...I have the usually Alert message about the folders, but nothing else.

It's not after little edits, most likely for bigger edits.
I tried to extract again the cia (with the hackingtool of asia81) , and it worked, but the same problem occured again later on...

Any idea of the source of the problem?

**Comment by kwsch** [comment]
Are you using the latest commits or some random exe you found on a YouTube video?

**Comment by GinKamas** [comment]
I use the latest, downloaded here : https://github.com/kwsch/pk3DS
Builded with Microsoft Visual Studio

**Comment by kwsch** [comment]
I'd try running it under the debugger, if it never shows up you can press the pause button to see if it is looping anywhere.

Not exactly sure what you mean by:
>application didn't want to open again

Be sure you didn't manually unpack any files in the romfs

**Comment by GinKamas** [comment]
Sorry for the bad english, I'm french...
I meant just to say pk3ds didn't work anymore after closing the program.

When you mean the debugger, you mean that, right? http://i.imgur.com/qt2znx4.jpg

for the romfs, I changed nothing...it's arranged like this if that can help :  http://i.imgur.com/MFCliwU.jpg

**Comment by kwsch** [comment]
looks like a garc was packed incorrectly (possibly on a previous version); you'd have to restore the backup files or start fresh.

**Comment by GinKamas** [comment]
Ok thanks, I restored the backup files, looks like it works for now! :)
