### ISSUE TITLE
PK3ds sets all trainer's pokemon to level 1

### ISSUE THREAD

**Issue by DwarfDan** [kwsch/pk3DS#110]
I was randomizing trainers and I accidently set Hau 006's pokemon to lvl 0. I didn't know what to put it as after so I just left it as it was thinking the game would update it to the correct lvl (after all its lvl 0). For some  strange reason all the others trainers pokemon were now lvl 0. I thought nothing of it. I brung everything over, pasted in the correct SaltySD folders, loaded up the game and.... ALL WERE LVL 1! I went back into pk3ds and all the levels were 0. I dont want to manually go through all of them and change the levels (probobly because pk3ds wont save it, and I dont know what the levels are). Please help.

**Comment by kwsch** [comment]
We're you using the latest commits?
Can restore backup files and try randomizing again.

**Comment by DwarfDan** [comment]
Yes I am using the latest version.

I dumped a .txt file from before. How could I restore it?

**Comment by DwarfDan** [comment]
I just realized I was asking the wrong person.

Pk3ds was only ever created for ORAS and X and Y.
I downloaded a Pk3ds version that was modified for Sun/Moon. 
THAT Pk3ds is probobly unstable.

Sorry for wasting your time.

**Comment by kwsch** [comment]
Well, this is the main repo for pk3DS and the exe you probably used was from a few months ago (ie not using the latest code).

You can download the latest version by visiting the projectpokemon link at the top of the [repo's page](https://github.com/kwsch/pk3DS).
