### ISSUE TITLE
TM Randomization for Pokemon Moon

### ISSUE THREAD

**Issue by JackTheMenace** [kwsch/pk3DS#116]
I built a .3ds then converted it to a .cia using Pokemon moon and the TMs aren't randomized when I definitely did randomize them. Is it something to do with the fact that I built a .3ds file and then converted it to a cia or is it something in pk3ds

**Comment by kwsch** [comment]
remove any installed patches.

https://github.com/kwsch/pk3DS/issues/98

**Comment by JackTheMenace** [comment]
I tried that now the game doesn't start up at all it just leaves me at a black screen

**Comment by sora10pls** [comment]
> I built a .3ds then converted it to a .cia

That's your problem. Every person I've seen rebuild a Sun/Moon ROM into `.3DS` or `.CIA` has had their game fail to load properly.

Play the vanilla game with patches through SaltySD for RomFS patches, and use Luma3DS' code patching for ExeFS (in this case, `code.bin`) patches.
