### ISSUE TITLE
SunMoon Wild Encounters

### ISSUE THREAD

**Issue by Kingsbury8** [kwsch/pk3DS#117]
Pk3ds crashes after almost completing the saving the changes made to the encounter tables.  This is a screenshot of the error it spits back: http://imgur.com/a/LebfW

**Comment by sora10pls** [comment]
Are you using latest commit?

**Comment by Kingsbury8** [comment]
I'm not. That could be it. Could you compile the latest commit for me? I'm a noob at stuff like that.

**Comment by kwsch** [comment]
Use the download link on the thread.
