### ISSUE TITLE
3-file exefs folders are accepted, 4-file exefs folders are rejected.

### ISSUE THREAD

**Issue by MrCheeze** [kwsch/pk3DS#12]
It's common for an exefs folder to contain four files: code.bin, banner.bin, icon.bin, and logo.bin. However the function checkIfExeFS() rejects all folders that don't contain exactly 3 files.

**Comment by kwsch** [comment]
Pretty sure the exefs for the games do not contain logo.bin files

**Comment by MrCheeze** [comment]
Huh. Well, somehow I managed to end up with one, and it was pretty tricky to work out why the exefs was being rejected. It's probably safe to skip that check entirely (who would try to open anything else?), but if you want one then checking code.bin filesizes would probably work.

**Comment by kwsch** [comment]
k :)

https://github.com/kwsch/pk3DS/commit/c00de4259aa23225c618e185f1d310ebab107c82
