### ISSUE TITLE
randomized encounter didnt work

### ISSUE THREAD

**Issue by hakulonewulf** [kwsch/pk3DS#121]
i have pokemon x update 1.5 and i randomized trainers, encounters, level up moves and items before battle, everything works except the wild encounters....i did all the steps including save currents encounters twice and none ot them works...can somebody help me with that???

**Comment by kwsch** [comment]
not pk3DS's fault.
remove the update, it overwrites the game content.

**Comment by hakulonewulf** [comment]
really!!! wow!!! thanks!!!!

**Comment by hakulonewulf** [comment]
i delete the update and now the game wont pass the nintendo 3ds logo...is there a way to fix it???
