### ISSUE TITLE
pokemon y does not start since deleted update

### ISSUE THREAD

**Issue by hakulonewulf** [kwsch/pk3DS#122]
hi, it me again... after i delete d eupdate for pokemon x the game simply does not start...it keeps lw nintendo 3da logo....can somebodybfix that???

**Comment by sora10pls** [comment]
I don't get this error with X, Y, Omega Ruby, or Alpha Sapphire (testing with latest commit). Definitely an issue on your end, not pk3DS.

Try running a `.3DS` or `.CIA` by getting a clean dump, randomizing, and then rebuilding.

**Comment by kwsch** [comment]
If you modified any CROs and aren't running CFW, then you can't play with modified CROs. The alert is there for a reason :)

**Comment by sora10pls** [comment]
That is true, but even without RO patches, the game runs fine until the save file is loaded and *then* crashes. If there's no save data present, then it runs fine until the user has control of the player character and *then* crashes.

Looping Nintendo 3DS logo is usually due to bad builds. ;P

**Comment by hakulonewulf** [comment]
i used a internet downloaded cia to biuld...and only the game runs with the update...i will try to used a clean eshop cia and try again...but the odd thinf is only the wild encounter does not work

**Comment by hakulonewulf** [comment]
and i am running arm9 and luma 6.6

**Comment by sora10pls** [comment]
You're far better off dumping the game yourself. Use Hourglass9/Decrypt9WIP/GodMode9 to do so; this can be done via Game Card or even SysNAND directory (digital install; eShop, freeShop, CIA, etc.).

You should close the issue as it's invalid, if not, @kwsch. ;)
