### ISSUE TITLE
Feature request: Form randomization in Starter/Gift/Static editors (6/7)

### ISSUE THREAD

**Issue by sora10pls** [kwsch/pk3DS#124]
It would be neat to see it included for all Pokemon with multiple forms in both the Gen 6 and Gen 7 editors. Obviously wouldn't apply to Pokemon with only 1 Form.

As far as I'm aware, these editors only take into account Pokemon with Alola Forms (Gen 7 only); if not all, then for sure Starter Editor 7.

**Comment by kwsch** [comment]
I think the gen7 editor works fine; the starter randomization button is separate from the rest.
