### ISSUE TITLE
Question regarding Wild Encounter Editor randomization

### ISSUE THREAD

**Issue by sora10pls** [kwsch/pk3DS#125]
As of late, when randomizing Wild Encounters, I've noticed that there seem to be duplicates with every attempt at randomization. I know that this was NOT the case in the past; while repeats could happen, they were not **this** common.

While it's not a huge problem, I would much rather prefer unique Pokemon in each slot, rather than having repeats in multiple slots, thus giving the user less to work with in a playthrough. Perhaps you could see this as a feature request, but I'll keep it listed as a question since I'm not sure if this is intentional or not.

The following screenshots are from Wild Encounters being randomized once:

Noctowl, Gogoat, and Goomy are repeats:
![image](https://cloud.githubusercontent.com/assets/17801814/25060569/65ab89ba-216e-11e7-9ed2-d967e25275f1.png)

Volcarona is a repeat (Horde A):
![image](https://cloud.githubusercontent.com/assets/17801814/25060576/8441d65e-216e-11e7-8e0f-8f5936b94a6b.png)

Tauros, Phione, Ledian **and** Carbink are repeats (as well as Huntail in DexNav Foreigns):
![image](https://cloud.githubusercontent.com/assets/17801814/25060579/94a940cc-216e-11e7-945e-c2581a4bd04c.png)

Pyroar is a repeat (Horde C):
![image](https://cloud.githubusercontent.com/assets/17801814/25060591/cb83ad8a-216e-11e7-95d4-0d647b61e942.png)

**Comment by sora10pls** [comment]
Can confirm that after multiple attempts at randomization, every encounter table has at least 1 repeat. This goes for Land, Water, and Horde tabs.

**Comment by kwsch** [comment]
DexNav max species limit :)
