### ISSUE TITLE
Editing shiny rates causes crashes, regardless of value

### ISSUE THREAD

**Issue by sora10pls** [kwsch/pk3DS#126]
Can confirm this is the case for Gen 7, have not tested yet for Gen 6. Process:

Open pk3DS -> Load Pokemon Moon game files -> Run Shiny Rates editor -> Change `8` to `9` -> Move over `.code.bin` to SD for Luma3DS to read externally -> Run Pokemon Moon -> Game crashes

**Comment by sora10pls** [comment]
Can confirm the same thing happens for Gen 6.

And while I'm at it, I'm not sure how this editor even saves the number of rerolls... I'll set it to a value of `6000`, save and exit the editor, re-open it, and it automatically changed itself from `6000` to `1905`.

Would it be possible to make the editor super user friendly and have the user simply enter a shiny rate percentage, and the program would automatically determine the amount of rerolls? A lot of noobs using the tool will find it very confusing, as well as myself if I'm perfectly honest lmao

**Comment by kwsch** [comment]
Did you recompress it?
I'm not familiar with how luma loads the files

**Comment by sora10pls** [comment]
Luma3DS does not require you recompress it for it to be loaded externally.

I've tested multiple different `code.bin` files edited with pk3DS. In the case of Gen 6, TM/HM edits as well as Mart edits worked; in any event where I edited shiny rates, the game crashed with the newly made `code.bin`.

I'll try to recompress and report back, though.

**Comment by kwsch** [comment]
disassembly of X for reference:
https://i.snag.gy/L5Rfaz.jpg

**Comment by sora10pls** [comment]
Recompressing the `code.bin` and loading the file externally simply leaves the console to endlessly loop the Nintendo 3DS logo when attempting to launch the game.

**Comment by kwsch** [comment]
Does the Restore Original Rate button allow it to boot again?
It should copy the original instruction back.

Could be that the MOVW isn't kosher, maybe need to use the MOV instruction instead.

FA 0E A0 E3 uses the MOV instruction and should set to 4000

**Comment by sora10pls** [comment]
Restoring original rate *does* indeed allow the game to properly load without crashes.

**Comment by kwsch** [comment]
Okay so it properly restores; try the above instruction (use HxD to find the before/after offset it's writing at)

**Comment by sora10pls** [comment]
Before (number of rerolls = `8`):
![image](https://cloud.githubusercontent.com/assets/17801814/25069236/4d9426e4-2249-11e7-806f-9d3a58c8c394.png)

After (number of rerolls = `9`):
![image](https://cloud.githubusercontent.com/assets/17801814/25069237/5a9549b8-2249-11e7-9a83-121f77522c51.png)

**Comment by kwsch** [comment]
Try writing FA 0E A0 E3 instead of 09 00 00 E3

**Comment by sora10pls** [comment]
Game launches totally fine after doing so :)

**Comment by sora10pls** [comment]
Setting a reroll value of 147 (not a multiple of 4, less than 256) still caused the game to crash.

This is what it looked like afterwards in HxD:
![image](https://cloud.githubusercontent.com/assets/17801814/25072609/02fb8cc8-22a1-11e7-8a5d-036bff411ed7.png)

**Comment by sora10pls** [comment]
I can also confirm that the value you gave me earlier (`FA 0E A0 E3` instead of `09 00 00 E3`) worked with Pokemon Moon as well!

Before (not modified, did not crash):
![image](https://cloud.githubusercontent.com/assets/17801814/25072694/df40af40-22a3-11e7-8957-4bf1179d9abc.png)

After edited with pk3DS (did crash):
![image](https://cloud.githubusercontent.com/assets/17801814/25072698/05d2d570-22a4-11e7-957a-11ee907c5889.png)

After edited with HxD (did not crash):
![image](https://cloud.githubusercontent.com/assets/17801814/25072692/c0f6121e-22a3-11e7-9c3e-cc54f79a76ea.png)

**Comment by kwsch** [comment]
(I don't think the patch actually works correctly even then; the `FA 0E A0 E3` corresponds to `MOV	R0, #0xFA0` (4000), which should be noticeable after a few encounters.

note to self:
@SciresM suggested doing something like `LDR R0, [pc, #some_value]` to load the value from a fixed offset

**Comment by sora10pls** [comment]
Shiny rate definitely was modified after writing `FA 0E A0 E3` to Moon's `code.bin`, so it seems that only when it's edited with pk3DS it causes a crash.

If you need me to test anything else, just let me know!

**Comment by kwsch** [comment]
Ah, it could just be my testing method screwing up :)

cool that it works

I was using http://armconverter.com/ to convert the instructions to hex but was unable to figure out how to convert it to c# for 'compiling' the MOV instruction for these %4 variants... guess they work so I'll figure something out!

**Comment by sora10pls** [comment]
Glad to hear and to help :+1:

**Comment by kwsch** [comment]
Added a table of precomputed instructions (~700) to support a range of values up to ~9000 (which is darn near 100%).
https://github.com/kwsch/pk3DS/commit/1f377de7e23ad73dd9175d28335f909d7530fc55

Thanks for the help !

**Comment by sora10pls** [comment]
My pleasure!

**Comment by sora10pls** [comment]
Hmm... may have found a bug with latest commit. If the specified number of rerolls is greater than 256, it doesn't save properly. Anything <= 255 is fine, though.

**Comment by sora10pls** [comment]
Commit f60a981 did indeed fix this :) thanks!

**Comment by Kyn77** [comment]
![Image](https://github.com/user-attachments/assets/5ca20074-c656-405a-b3a9-f09cc0132697)

Hi, ik its been 8 years but im encountering the exact same error but with UltraMoon (prismatic moon mod), I edited the shiny rates (9 rerolls) with pk3ds and they work, but as soon as I go to talk to a pokemart it freezes..
I tried changing the same numbers you did in the code.bin (decompressed and recompressed) with HxD, I was looking at the blue numbers on the left (0004F460) and changed the 5th, 6th and 7h paramater to FA 0E A0 E3 but it probably was a stupid idea since they are 2 different games, im kinda bad at programming so im lost ahah
Also I tried editing the hex of the code.bin after editing with pk3ds and even without editing with p3ds but the paramaters at 0004F460 were the exact same so ye idk what to even try
