### ISSUE TITLE
Feature request: importing/exporting unique, pre-made settings files

### ISSUE THREAD

**Issue by sora10pls** [kwsch/pk3DS#129]
Similar to how [Universal Pokemon Randomizer](https://github.com/Dabomstew/universal-pokemon-randomizer) handles things. The user is able to save the unique changes that they make with the program to a unique file format (`.rnqs`), which can then be loaded in the future to load the exact same settings they once had, speeding up the process of randomizing.

Something similar implemented into pk3DS would be awesome. However, while UPR loads ROM files directly and allows for one settings file that works for the entire ROM, I don't think that'd be the case for pk3DS which has multiple editors in multiple different forms. Perhaps a settings file per form? I don't know.

I wouldn't be surprised if this doesn't get implemented any time soon or at all seeing as how it's a big request, but I'm sure a lot of people, myself included, would love it.

**Comment by trainex25** [comment]
How can I use this file? The b9e0bf3? Especially the SMWE file?

**Comment by kwsch** [comment]
It is built into the program.

The program saves a settings file which can be sent to others, or reused on different ROMs. You can additionally set the randomization seed so that the randomization proceeds the same way each time, across computers.
