### ISSUE TITLE
Feature request: increase Level via % and not decimal for Static/Gift Editors

### ISSUE THREAD

**Issue by sora10pls** [kwsch/pk3DS#131]
To stay consistent with Wild Editors and Trainer Editors. That, and people generally prefer the percentage system over decimal (as seen in #115).

**Comment by kwsch** [comment]
all the gen7 editors use the factor multiplier; only XYWE / RSWE / RSTE still use the % boost

% is essentially the same as decimal, just add 1.00 to whatever percent you are looking to alter.

0.80 => -20%
1.20 => +20%
1.50 => +50%

**Comment by sora10pls** [comment]
Actually hadn't noticed that until you mentioned it. I thought that issue being closed brought percentage boost back with Gen 7 editors, but I never actually checked lmao

I'll close the issue regardless, I know how to work the decimal boost. Just afraid for the really bad noobs out there ;)
