### ISSUE TITLE
[Feature Request?] Force Full Evolved Pokémon on Trainer based on Level

### ISSUE THREAD

**Issue by egzonqj** [kwsch/pk3DS#132]
Maybe the title is not that accurate but let me explain it a bit. In the Universal Pokémon Randomizer program you have an option to force that the Pokémon of the trainer are fully evolved based on the level. 

I guess it works like if the trainer has Pokémon with level 30>, this option will randomize them as fully evolved Pokémon, regardless of the BST.

For reference:
![image](https://cloud.githubusercontent.com/assets/5099644/25136213/a0a691d4-2454-11e7-97c1-14a22d749273.png)
![image](https://cloud.githubusercontent.com/assets/5099644/25136222/a98c8cea-2454-11e7-836c-7b3d12c57111.png)

**Comment by kwsch** [comment]
It's not too difficult to implement; an array of species and the final evolution(s).
`int[MaxSpeciesID+1][]` where each entry is a species possible final evolutions. 

However, if a user changes the final evolved species, it'd have to be loaded and stored like personal stats.

Does UPR support BST randomization? 

If species are already randomized by BST (~within 20%) they should usually be final evos towards endgame. My question is -- would this Evo bump have enough benefit? It'd take a bit of work to make it behave correctly ;)

**Comment by sora10pls** [comment]
UPR does have BST randomization; in the program it's referred to as "Similar Strength".

**Comment by egzonqj** [comment]
> would this Evo bump have enough benefit? 
I think it would, I mean, a random trainer having a high bst pokemon (say hydreigon) and it's at lvl 30, i guess that would be pretty challenging to face. it's just my opinion tbh.

> However, if a user changes the final evolved species, it'd have to be loaded and stored like personal stats. If there's some cyclic behavior (x evolves into y evolves into z evolves into x; yay randomization), wat do?
i'm sorry, i dont happen to understand this sentence at all

**Comment by sora10pls** [comment]
Piplup => Prinplup => Empoleon

\>somebody changes evolution from Empoleon to Seedot
\>final evolved species is now Seedot

~at least I think so~

**Comment by kwsch** [comment]
But then what does Seedot evolve into? Would the check be limited to 'n' tries and would it automatically stop if the BST decreases?

**Comment by sora10pls** [comment]
But then you'd have to account for randomized BSTs...

I think the best method is to just do it the way UPR handles it, only accept default final evolved species (examples: Empoleon, Scrafty, Gothitelle, Solgaleo; not Prinplup, Scraggy, Gothorita, Cosmoem). That'd easily be done with a hardcoded list of Pokemon.

**Comment by egzonqj** [comment]
> I think the best method is to just do it the way UPR handles it, only accept default final evolved species (examples: Empoleon, Scrafty, Gothitelle, Solgaleo; not Prinplup, Scraggy, Gothorita, Cosmoem). That'd easily be done with a hardcoded list of Pokemon.

I agree on this, no matter how the user messed up with the evo chart, the feature will follow the default one every time.

> But then what does Seedot evolve into? Would the check be limited to 'n' tries and would it automatically stop if the BST decreases?

I guess that would stop on Seedot in that example, since it's the new final evolution of that species

**Comment by sora10pls** [comment]
That's not entirely true. Seedot => Nuzleaf could've also been modified, so it could very well be endless.

Piplup => Prinplup => Seedot => Nuzleaf => etc.

**Comment by kwsch** [comment]
Probably best to do it this way:
If BST is selected, the evo chain check will stop if the BST of the next evo is less than the current.
If BST is not selected, the evo chain check will stop if it has already 'bumped' twice. (a pkm only evolves twice, this isn't digimon)

```
if (evobump && pkm.Level >= evoLevel)
    Randomizer.BumpEvolution(species, BST);

BumpEvolution(int originalSpecies)
{
    int ctr = 0;
    int species = originalSpecies;
    
    do 
    {
        int newSpec = EvoTable.GetNextEvo(species);
        if (newSpec <= 0)
            break;
        if (BST && SpeciesStat[newSpec].BST < SpeciesStat[species].BST)
            break;
        species = newSpec;
    } while (++ctr != 2);
    
    return species;
}
```

if there's 8 evos it can always pick a random one or maybe weight by BST; dunno how extensive everything should be.

**Comment by egzonqj** [comment]
I guess that would be the best path tho, will both options follow the species' original evolution chart?
