### ISSUE TITLE
Romfs Folder

### ISSUE THREAD

**Issue by RUNETHERABBITYT** [kwsch/pk3DS#136]
i need to know a diagram that shows what the romfs/a/0-3/0-9 does for keeping files

**Comment by sora10pls** [comment]
Options > About GARCs

This shows you what each GARC that can be edited by pk3DS is. Example picture is Moon, same process for every other game.
![image](https://cloud.githubusercontent.com/assets/17801814/25292127/d5ff3836-26a2-11e7-9025-5736c66b0017.png)
