### ISSUE TITLE
Question: why does Story Text editor in Gen 6 replace gender symbols in battle?

### ISSUE THREAD

**Issue by sora10pls** [kwsch/pk3DS#137]
If the Story Text editor is simply opened, despite the fact that no changes were made, gender symbols that are placed next to the Pokemon's nickname in the battle HUD will be replaced with `♂` and `♀` from Nidoran's name. This does not happen with Gen 7.

It's easily noticeable, and comparison pictures are below for reference.

Vanilla game:
![1](https://cloud.githubusercontent.com/assets/17801814/25756779/02326ace-3196-11e7-8596-2764a44337cd.png)

Edited game: 
![2](https://cloud.githubusercontent.com/assets/17801814/25756782/05b5515c-3196-11e7-913b-f9a653f7e45f.png)

**Comment by kwsch** [comment]
https://github.com/kwsch/pk3DS/blob/aca8174c38927f85b7bccdddf420ac110ac3a172/pk3DS/Tools/TextFile.cs#L146-L149
https://github.com/kwsch/pk3DS/blob/aca8174c38927f85b7bccdddf420ac110ac3a172/pk3DS/Tools/TextFile.cs#L189-L198

would need some refactoring to disable the string replacement for the full/half width characters
