### ISSUE TITLE
Missing image.cs file in tools folder...

### ISSUE THREAD

**Issue by ApacheThunder** [kwsch/pk3DS#14]
Not sure what purpose this file had, but pk3ds.csproj references this file (specifically at line 207). However it's not available from this github and thus as a result it will not compile till I remove the reference to it from the project file. Please correct this oversight. :D

I don't know if this has any impact on functionality of the program. It seems to compile fine after I removed the reference to it. If there is a feature you made that uses code in that file, it's currently broken.

**Comment by kwsch** [comment]
Image.cs should NOT be in the project as it was removed in the following commit:
https://github.com/kwsch/pk3DS/commit/850593d86c1c098f3968a49a735abb5fe5ce9f72

Github didn't sync the csproj until the project was closed on my end... yeah.
https://github.com/kwsch/pk3DS/commit/8ad066dfa6b7f4a703f3d7c22e2b2014d4463310

Thanks :)
