### ISSUE TITLE
Difference between 3IV and 3IV_2?

### ISSUE THREAD

**Issue by sora10pls** [kwsch/pk3DS#140]
As the title says, I'm not too sure what the difference between the 2 is.

If I had to take a wild guess, I'd assume ticking both checkboxes would guarantee 6IV? I dunno.

**Comment by kwsch** [comment]
No idea, it's just another bitflag with unknown purpose
could be related to antishiny...

**Comment by sora10pls** [comment]
I could probably do some testing throughout the week if you'd like :)

If not, you could always test through Citra since I know you don't own a 3DS.

**Comment by kwsch** [comment]
Effort Required + Interest < Motivation

Developing PKHeX is more important until this weekend :)

**Comment by sora10pls** [comment]
I'll update this comment over the course of my ~~very basic~~ testing.

- 3IV_2 does not actually guarantee 3 perfect IVs
- Ticking 3IV **and** 3IV_2 does not guarantee 3 perfect IVs; 3IV_2 seems to overwrite 3IV

**Comment by kwsch** [comment]
I'm not sure 3IV is really forcing 3IVs; that would likely be done by the sublegends/legends species check forcing those IVs.

No idea what they're for

**Comment by sora10pls** [comment]
I haven't tested using the 3IV checkbox other than in addition with 3IV_2. I can do some more testing tonight by changing some event flags in PKHeX to respawn Legends.

Note to self, in pk3DS:
- First, set all Legends to have 3IV **not ticked**
- Catch multiple (larger sample size) of them and check IVs
- Second, set Shiny Rate to 100%, have 3IV ticked, and have 3IV_2 **not ticked**
- See if Legend is shiny
- Third, have 3IV **not ticked** and have 3IV_2 ticked
- See if Legend is shiny

If 3IV and 3IV_2 really have no relevance to IVs, these tests should help clarify to see if it's related to antishiny. :)

Also I'd like to ask beforehand, what is the difference between Shiny Lock and Antishiny?

**Comment by kwsch** [comment]
No difference; I prefer referring to it as antishiny. "Lock" may imply locked-in as shiny (nature/gender locks are *requirements* for PIDIV generation).

wonder if one of these bits is a behavior bit (for biasing attacking moves) idk lol. 
May be better to just poke around in the disassembly if no correlation is noticed.

**Comment by sora10pls** [comment]
Comment from earlier updated with more info (and timestamps).

Shiny Lock
- If ticked, prevents shininess

3IV
- Guarantees encounter in slot has 3 perfect IVs

3IV_2 (from what I can tell)
- Nothing to do with shininess
- Nothing to do with IVs

**Comment by kwsch** [comment]
Obsolete with current advances in https://github.com/kwsch/pk3DS/issues/146 and USUM documentation.
Structure is likely the same; the 0x7 value may just be related to encounter details (x appeared, wild x appeared, etc) or something non-pkmdata related.
