### ISSUE TITLE
[REQUEST] Set trainers pokemon to current randomized movepool

### ISSUE THREAD

**Issue by ahiddenwaffle** [kwsch/pk3DS#143]
With the "Use Current Level Up Moves" for trainer's pokemon. I would like the levelup moves set to what the _currrent_  level up moves are, not the default. (i.e I want trainers pokemon to have the moves that I randomize/change them too, not default/completely random)

**Comment by kwsch** [comment]
wat

Clear = no moves = game loads current level up moves
Current level up moves = pk3DS freezes current level up moves
High attacking = pk3DS freezes high powered moves

"current level up moves" equivalent to default (no moves entered).

**Comment by ahiddenwaffle** [comment]
So... obviously there's a problem?

**Comment by kwsch** [comment]
No? Leaving the moves empty will let the game populate with current level up moves when it generates them ingame. pk3DS can freeze them for you if desired (to randomize levelup moves afterward).

Current level up moves are the moves you would get if encountering in the wild (ie, the highest 4 level moves for the current level).

**Comment by ahiddenwaffle** [comment]
Oh. I see sorry for posting so many issues, there isnt much documentation on this and I was on mobile so the formatting you did was off. I thought you mean Pk3DS the program freezes, lol. and I figured when you set it to (none) it literally means an empty move slot.
