### ISSUE TITLE
Gen7 Structure EncounterStatic.cs Data Types

### ISSUE THREAD

**Issue by Aussifer** [kwsch/pk3DS#146]
Lines 39 and 40 are set to detail handling the 0x7 byte for IV3 checks, but looking at the raw data in the a155 file, it seems that the 3IV check is done by setting the IV bytes at 0x15 - 0x1A to "FC FF FF FF FF FF" instead of "FF FF FF FF FF FF" for normal encounters. I'm not sure whether that bool is redundant and leftover from Gen_6 or if it codes for something else with the new data structure for static encounters, or if I'm just missing something entirely.

As far as other things within EncounterStatic, 0x8 - 0x9 seem to handle the encounter location data, designating the map in which the encounter is located: Solgaleo's byte value is 00F8 (248), and it's encountered in map 247 (Altar of the Sunne); the static Exeggutor's value is 0100 (256) and it's found on Exeggutor Island (map 255), etc. So I'd wager an educated guess that 0xA - 0xB are for map co-ordinates or the type of terrain on which the encounter takes place, but it's only a guess at this point. 

0x21 - 0x25 look like they handle Totem/Beast auras; 0x25 in particular designates the stat boost from the aura by setting the byte from 00 to 0F (00 = no boost, 01 = Attack +1, 02 = Attack +2, 03 = Attack +3, and so on for Defense, Sp.Atk, Sp.Def and Speed). 10 is a +1 to all stats, which makes me think 11 and 12 give +2 and +3 respectively, since the game text allows for an aura to raise all stats drastically. 

Not sure about 0x26, as the data varies wildly even for non-Totems, but 0x27 - 0x2F determine what allies a Totem calls in Totem battles... and I have a hunch that 0x30 to 0x38 do as well but are unused because the earlier bytes don't allow for them to be called (my working theory is that each SOS ally has a 4-byte cluster, and the 3rd byte counts down when you advance to the next ally).

**Comment by Aussifer** [comment]
Update: can confirm that for 0x25, 11 gives the Pokemon +2 to all stats and 12 gives +3.

**Comment by Aussifer** [comment]
After some experimentation with USUM, it seems like:

0x0-1 is Pokemon ID.

0x2 is Forme.

0x3 is Level.

0x4-5 is Held Item.

0x6 uses four pairs of bits for Shiny Lock (1,2), Gender (4,8), Ability (16,32) and another flag (64,128) that ONLY applies to Pokemon w/ aura boosts (Totems/UBs) and the Solgaleo/Lunala battle @ Mahalo Trail, but NOT any of the Necrozma forms (even Ultra Necrozma). 

0x7 is another bit pair. (00 / 01 / 10 / 11) - I'm not sure what this one is for? I suspect it's closely related to the mystery 0x6 pair... all legendaries have 01 (except the credits Tapu Koko from SM), all Totems have 02 and all UBs have 03.

0x8-9 is the Map number reference.
0xA-B are the co-ordinates within the map.

0xC-13 are its Moveset (four byte-pairs).

0x14 is Nature.

0x15-1A are IVs.
0x1B-20 are EVs (Totems have EVs, believe it or not... as do the storyline Necrozmas).

0x21-24 are Totem/Beast aura information (Totems use FF991900, UBs use FF333300, Ultra Necrozma uses E8D58400, all other encounters are 0). I'm not sure what specifically they refer to. It could also be that the information is just 0x21-23 and 0x24 is 0 for everyone - as of yet, 0x24 has never been anything but 0 for all encounters.

0x25 is the Aura boost. (01-03 for Attack +1/+2/+3, then Defense 04-06, Sp.Atk 07-09, Sp.Def 0A-0C, Speed 0D-0F, all stats 10-12).

0x26 is the battle type for the encounter (designation for music, background, the Pokemon's initial animation, and other special effects - for aura boosts, specific values are needed to trigger the stat raise. It's not enough to just have 0x21-25 for a "totem fight").

0x27 is the number of allies a Pokemon can call in a fixed encounter.
0x28-2B is information for the first ally (picked from the fixed encounters list). The first two bytes are the list number of the Pokemon to be called. The third byte is one less than 0x27 (but I don't know what it signifies). The fourth byte is 0.
0x2C-2F is information for the second ally (if there is no second ally, all bytes are 0). The first two bytes are the list number of the Pokemon to be called. The third byte is one less than 0x2A (but I don't know what it signifies). The fourth byte is 0.

0x30-38 are 0 for all encounters. I suspect they may have initially been coded to allow for additional allies during a Totem fight, but since there are no Pokemon with the enemy_AI to call more than two, it's impossible to test.

**Comment by sora10pls** [comment]
Thanks to all of this documentation, I could eventually PR something along the lines of this that I've been working on today:
![image](https://user-images.githubusercontent.com/17801814/34116588-11ce72d0-e3e7-11e7-88a6-cbe7031f0b40.png)

Just a few small changes need to be made :)

**Comment by sora10pls** [comment]
Ally 1 and 2 documentation added with #318, thanks @Aussifer!
