### ISSUE TITLE
Feature Request: patch offset support for ExeFS editors

### ISSUE THREAD

**Issue by sora10pls** [kwsch/pk3DS#147]
With the help of Luma3DS' code modification, it's possible to load `code.bin` externally, regardless of version (has to match the update data installed, of course). In the case of X/Y:

v1.0 `code.bin` **can be** loaded with no update data installed.
v1.0 `code.bin` **can not be** loaded with v1.5 update data installed.
v1.5 `code.bin` **can be** loaded with v1.5 update data installed.

pk3DS can read and write to any Pokemon `code.bin` file just fine, though there is one exception that I've found: the X/Y/OR/AS Mart Editors. If these are opened with pk3DS and an updated `code.bin` (v1.5 for X/Y, v1.4 for OR/AS), it [throws an exception](https://pastebin.com/crhqNY1F).

As far as I can tell, this is the *only* case of pk3DS failing to modify data due to being of a version other than v1.0; all other Gen 6 ExeFS editors work fine, and everything works fine in S/M.

Implementation for this would be nice as I doubt the Gen 6 games will be getting any more software updates, but it won't be the end of the world if it isn't included. I can always just rebuild a CIA for v1.0 at any time, but having the option is nice :)

**Comment by kwsch** [comment]
Probably because it fails to find the byte pattern; the outer loop of `IndexOfBytes` loops over the entire array and the inner loop can try to access out-of-bounds vals.

Would need to see 👀 a file to come up with a more universal byte pattern to search for. pk3DS does a lazy find bytes :)

**Comment by sora10pls** [comment]
Got it working on my own if you'd like to implement something later so that both v1.0 and update data offsets can be supported at the same time.

https://github.com/kwsch/pk3DS/blob/master/pk3DS/Subforms/Gen6/MartEditor6.cs#L17
Change to:
`offset = Util.IndexOfBytes(data, new byte[] { 0x00, 0x72, 0x6F, 0x6D, 0x32, 0x3A, 0x2F, 0x44, 0x6C, 0x6C, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4D, 0x65, 0x6E, 0x75, 0x2E, 0x63, 0x72, 0x6F, 0x00 }, 0x400000, 0) + 0x18;`

https://github.com/kwsch/pk3DS/blob/master/pk3DS/Subforms/Gen6/MartEditor6.cs#L54
Change to:
`private readonly int offset = Main.Config.ORAS ? 0x0047AA40 : 0x0043F8A0;`

**Comment by sora10pls** [comment]
Turns out the OR/AS Move Tutor offset is also different with update data.

https://github.com/kwsch/pk3DS/blob/master/pk3DS/Subforms/Gen6/TutorEditor6.cs#L29
Change to:
`private const int offset = 0x004961E0;`

**Comment by sora10pls** [comment]
If you'd like to compare files via file size, here are the exact sizes of the *compressed* `code.bin` files for each 3DS Pokemon game.

`5,169,152 bytes` => XY
`5,439,488 bytes` => ORAS
`5,722,112 bytes` => SM

**Comment by kwsch** [comment]
The byte pattern is used the same way as you would 'find' in HxD; by finding a chunk of data before/after the relevant section, the offset can be found by shifting the offset back accordingly. I think one of them has some 'sliding' in the event that there's 00 padding.

Can't search for the original data because it may be user edited :)

would need to find out what byte pattern works for all patches!

**Comment by sora10pls** [comment]
That's true, I never really thought of that possibility.

Would it not be possible to do it the way TutorEditor6 handles it? The offset is listed right there, so one would assume that it'd be possible to do the same for the other editor(s).

**Comment by kwsch** [comment]
All hard-coded values would have to be the same across all patches; I was lazy with the fixed-offsets and didn't bother finding a byte pattern reference. pk3DS has to be able to support vanilla/patchA-Z

**Comment by sora10pls** [comment]
If it helps with anything, I've got all the 3DS Pokemon games `code.bin` files handy; I could easily find offsets if you need them. I've already commented 3 here:

`0x0043F8A0` => XY mart (v1.5)
`0x0047AA40` => ORAS mart (v1.4)
`0x004961E0` => ORAS tutor (v1.4)

The offsets for v1.0 are already in the source code (refer to lines linked above in one of my previous comments).

If you need the others let me know, I can check for each pair of games on both initial release (v1.0) and latest releases (v1.5, v1.4, and v1.2 respectively).

Offsets for S/M v1.2 are the exact same as v1.1, yet both differ from v1.0, so one would only assume that
 this is *also* the case for XY v1.1 through v1.4, and ORAS v1.1 through v1.3. 👍

**Comment by sora10pls** [comment]
More offsets (shiny rate):

`XY v1.0 ---> 0x0004F464`
`XY v1.5 ---> 0x0004F740`

`ORAS v1.0 -> 0x0004ED08`
`ORAS v1.4 -> 0x0004ED40`

`SM v1.0 ---> 0x00218488`
`SM v1.2 ---> 0x00218B8C`

**Comment by kwsch** [comment]
not going to use static offsets; has to be a byte pattern + shift value to auto-find regardless of code binary provided.

**Comment by sora10pls** [comment]
Will have to double-check for byte patterns when I'm home from work. It'd be easier to just have the files on hand but you don't own a 3DS ~~and I'm not sure how you'd feel about me sending you game files. 🤔~~

**Comment by sora10pls** [comment]
So from looking at the source code, pk3DS checks for the following byte pattern with MartEditor6:
`00 72 6F 6D 3A 2F 44 6C 6C 53 74 61 72 74 4D 65 6E 75 2E 63 72 6F 00`
This reads: `.rom:/DllStartMenu.cro.`
After finding this in my `code.bin` for v1.0, I can tell the exact offset is `0x0043C89E` (the following byte).

If this were changed to support update data, the byte pattern would be:
`00 72 6F 6D 32 3A 2F 44 6C 6C 53 74 61 72 74 4D 65 6E 75 2E 63 72 6F 00`
This reads: `.rom2:/DllStartMenu.cro.`
Updates have the `rom2` prefix rather than `rom`.

**Comment by sora10pls** [comment]
Looking at TutorEditor6, source code uses a static offset: `0x004960F8`.
It could instead check for the following byte pattern:
`00 46 6F 72 6D 61 74 54 79 70 65 00 00 45 64 67 65 49 44 00 FF`

The following byte (`0xC2`) is at the offset listed in the source code.
![image](https://user-images.githubusercontent.com/17801814/28046004-90321bc0-65ae-11e7-8b58-80770675b680.png)

In v1.1+, the block is a lot different. It reads:
![image](https://user-images.githubusercontent.com/17801814/28046090-22edb514-65af-11e7-9b3b-1b3e5422f907.png)

And like with v1.0, the following byte is `0xC2`.

Reference (easy copy/paste):
`00 46 6F 72 6D 61 74 54 79 70 65 00 00 45 64 67 65 49 44 00 00 63 3A 5C 72 65 76 69 73 69 6F 6E 31 5F 73 61 6E 67 6F 5C 73 61 6E 67 6F 5F 70 72 6F 6A 65 63 74 5C 70 72 6F 67 5C 73 72 63 2F 73 79 73 74 65 6D 2F 6D 6F 74 69 6F 6E 2F 4D 6F 74 69 6F 6E 2E 63 70 70 00 00`

**Comment by sora10pls** [comment]
ExeFS Editors compatibility list with update data code binaries:

- Move Tutor (OR/AS) ❌ 
- TM/HM ✔️ 
- Mart ❌ 
- Pickup ✔️ 
- O-Power ✔️ 
- Shiny Rate ✔️ 
- Type Chart (S/M) ✔️

**Comment by sora10pls** [comment]
Commit 53b21f1 still throws exceptions for both.

Tutor: https://pastebin.com/uh0r5cum
Mart: https://pastebin.com/XLMPULrd

**Comment by kwsch** [comment]
I added the byte pattern you provided, should work. If the pattern is not found, it returns -1 which yields the above error.

**Comment by sora10pls** [comment]
Have tried using clean dumps of both the game and the patch, still throws an exception with the patched code binary. Not entirely sure why that's the case. :/

**Comment by sora10pls** [comment]
Still getting the same exception.

**Comment by kwsch** [comment]
```

        // Find Code off of Reference
        public static int IndexOfBytes(byte[] array, byte[] pattern, int startIndex, int count)
        {
            int len = pattern.Length;
            int endIndex = count > 0 ? startIndex + count + 1 : array.Length - pattern.Length;
            for (int i = startIndex; i < endIndex; i++)
            {
                for (int j = 0; j < len; j++)
                    if (pattern[j] != array[i + j])
                        goto next_i;
                return i;
                next_i:;
            }
            return -1;
        }
```

added - pattern.Length to end of `int endIndex = ` line

**Comment by sora10pls** [comment]
Still nothing.

**Comment by kwsch** [comment]
should probably transmit files somehow ;)
pp

**Comment by sora10pls** [comment]
That fixed it! ~~I wonder how you got around to that~~ Thanks a ton!
