### ISSUE TITLE
Building commit fd7ecad gives error in TrainerRand.cs

### ISSUE THREAD

**Issue by Favna** [kwsch/pk3DS#15]
Hey Kaphotics,
I just rebuild the latest commit of PK3DS and it gave the following warning upon doing so:

`Accessing a member on 'pk3DS.Subforms.MapPermView.DrawMap' may cause a runtime exception because it is a field of a marshal-by-reference class`

**Comment by kwsch** [comment]
Doesn't happen with VS2012 for me.

Tweaked in the latest commit https://github.com/kwsch/pk3DS/commit/2db39b086644afee136f6ecff8b44173a999c1f4

lmk if that works.

**Comment by Favna** [comment]
Apologies for the late reply, I've just tested it with the latest commit (thus I pulled commits [`2db39b0`](https://github.com/kwsch/pk3DS/commit/2db39b086644afee136f6ecff8b44173a999c1f4) till [`fd7ecad`](https://github.com/kwsch/pk3DS/commit/fd7ecadf4e77209bb71f1dd3477e814514d85c6b)) and well... I'm not getting the warning anymore (presumably), now I get the following error:

    'pk3DS.RSTE' does not  contain a definition for 'rTypeGymE4Only'
        File: TrainerRand.cs || Line: 66 || Column: 18

**Comment by kwsch** [comment]
Should be working now.

**Comment by Favna** [comment]
It works indeed :)
