### ISSUE TITLE
Game text edit breaks SUMO

### ISSUE THREAD

**Issue by Uyuiyu** [kwsch/pk3DS#152]
When you try to enter the game (the start menu works and the new-game intro also works) the screen stays static and does nothing. Something related to the text game of /a/0/3/6. Using luma layered fs. In all cases, probably replicable

**Comment by sora10pls** [comment]
Unable to replicate using a modified Game Text GARC. Game loaded fine and my text edits were present.

Tested using:
/a/0/3/2 (English)
/a/0/3/6 (Spanish)

You said that you're using Luma's LayeredFS, so make sure that you're using a Game Text GARC that matches your game's version; in the case of both 1.1 and 1.2 updates, all Game Text GARCs were updated, so the game expects the GARCs to match the version you have installed.

If you need help getting the GARC, following [this guide](https://3ds.guide/godmode9-usage.html#dump_title) to dump a title.
