### ISSUE TITLE
[Bug?] XYWE level range multiplier button throws exception

### ISSUE THREAD

**Issue by sora10pls** [kwsch/pk3DS#157]
Doesn't happen with OR/AS or S/M, just X/Y. Dumps are clean, too. The exception is [here](https://pastebin.com/veJudrwR). As far as I can tell, and according to Task Manager, I only have that one instance of pk3DS running.

Note that this only happens with the "× Current" button; randomizing with the level boost enabled works as intended.

**Comment by kwsch** [comment]
The error line is at the top:
`System.IO.IOException: The process cannot access the file 'C:\Users\Matt\Randomizers\pk3DS\encdata\dec_001.bin' because it is being used by another process.`

something else is locking up that file when the randomizer is trying to read/write it.

**Comment by sora10pls** [comment]
Weird that it's only X/Y, though. I'll find something for it eventually.
