### ISSUE TITLE
Tm randomisation not Working.

### ISSUE THREAD

**Issue by CloudStyles** [kwsch/pk3DS#159]
So, newest version of Pk3DS, running luma3ds and rosalina, randomising tm moves and have tried on both sun and moon but tm randomization just isn't translating. I've triple checked every file, every subfolder but nothing us updating the tms. 

Is there something I missed??

**Comment by kwsch** [comment]
https://github.com/kwsch/pk3DS/issues/116

**Comment by kwsch** [comment]
Remove any installed patches, as the patch exefs overwrites the edited one.
