### ISSUE TITLE
[Bug] pk3DS fails to unpack/repack several GARCs

### ISSUE THREAD

**Issue by sora10pls** [kwsch/pk3DS#161]
Tested using latest commit.

Gen 6 Wild Encounter Editor unpack: http://i.imgur.com/oNPn1e4.png
Gen 6 Wild Encounter Editor repack: http://i.imgur.com/pJNdjqi.png

Gen 6 Title Screen Editor unpack: http://i.imgur.com/HpAlq8H.png
Gen 6 Title Screen Editor repack: http://i.imgur.com/8ofWkBN.png

Gen 6 Overworld Script Editor unpack: http://i.imgur.com/5LSK0bB.png
Gen 6 Overworld Script Editor repack: http://i.imgur.com/4VAlMJI.png

**Comment by sora10pls** [comment]
Also happens with Gen 6 title screen editor.

Unpack:
![image](https://user-images.githubusercontent.com/17801814/27317935-9f66b1a8-5557-11e7-88d9-5fca7cab96fd.png)

Repack:
![image](https://user-images.githubusercontent.com/17801814/27317944-a921c494-5557-11e7-8845-5ded2fc9e75c.png)

**Comment by kwsch** [comment]
memgarc works fine; the slow filesystem unpack was refactored with the core net standard split (and has issues)

**Comment by sora10pls** [comment]
Yeah this was working totally fine before the refactor so I figured that was the case.

Also, while you're here, my previous issue #153 carried over into Gen 7. Gen 6 still works fine :P
![image](https://user-images.githubusercontent.com/17801814/27318189-120c2b1a-5559-11e7-840b-340f022a187c.png)
