### ISSUE TITLE
pokemon omega

### ISSUE THREAD

**Issue by pandaboom101** [kwsch/pk3DS#162]

**Comment by sora10pls** [comment]
![image](https://user-images.githubusercontent.com/17801814/27511375-336de31c-58f0-11e7-96b1-651086b738aa.png)

**Comment by CharmyBee99** [comment]
🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔
***Insert thonkangs here***
I vote closing, because there's literally no information, this is the least amount of information you can give. 👍 If you agree, 👎 if you don't.

**Comment by evandixon** [comment]
Closing since the title is vague and no description is provided.
