### ISSUE TITLE
Unable to randomize TMs

### ISSUE THREAD

**Issue by Frumentarii** [kwsch/pk3DS#172]
My game freezes on the Nintendo 3DS screen when starting up the game. I'm not sure what the problem is since it can randomize everything under the RomFS category just fine. My code.bin file is in the code_sections folder along with the code.ips.  Not sure if it helps but the GARC files in my SaltySD are:

a/0/1/1
a/0/1/3
a/0/1/4
a/0/1/5
a/0/3/2
a/0/4/2
a/0/8/2
a/1/0/4
a/1/0/5
a/1/0/6
a/1/5/5

Am I doing something wrong? Thanks for all the help.

**Comment by kwsch** [comment]
unrelated to pk3DS, you can randomize TMs just fine with pk3DS.

[refer to past 'issues' regarding saltysd](https://github.com/kwsch/pk3DS/issues?utf8=%E2%9C%93&q=is%3Aissue%20saltysd)
