### ISSUE TITLE
Is there a way to change the settings through PK3ds without losing your save file?

### ISSUE THREAD

**Issue by Tommaniacal** [kwsch/pk3DS#173]
I wanted to increase the catch rate of pokemon, and increase the chance of TMs being compatable (if that's possible), without losing my current randomized save file. Is this possible? I have Omega Ruby if that helps

**Comment by kwsch** [comment]
unrelated to pk3DS; just reimport your save file

**Comment by Tommaniacal** [comment]
How does one do this?
