### ISSUE TITLE
[Question/Request] Wild Form Changes?

### ISSUE THREAD

**Issue by Amphar0s** [kwsch/pk3DS#174]
I know that there is an option to have wild Mega Forms appear, but can other form changes also appear in the wild? Having Darmanitan-Zen appear or an Alolan Form for example. Can this happen by itself or is there an option for this? Otherwise I guess this is a request to add an option to have random wild forms

**Comment by sora10pls** [comment]
This is done by default. The only Form option that can be turned on or off is Mega Evolution.
