### ISSUE TITLE
pk3ds cannot open...

### ISSUE THREAD

**Issue by YamiRioru** [kwsch/pk3DS#178]
it pops up a message saying an unhandled exception has occured and this jarble...

Exception Details:
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at pk3DS.Core.GameConfig.getGARCData(String file, Boolean skipRelative)
   at pk3DS.Core.GameConfig.InitializeAll()
   at pk3DS.Main.openQuick(String path) in C:\BuildAgent\work\b93f10d64d1a1178\pk3DS\Main.cs:line 219
   at pk3DS.Main..ctor() in C:\BuildAgent\work\b93f10d64d1a1178\pk3DS\Main.cs:line 54
   at pk3DS.Program.Main() in C:\BuildAgent\work\b93f10d64d1a1178\pk3DS\Program.cs:line 29

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

pk3DS, Version=1.0.0.108, Culture=neutral, PublicKeyToken=null
C:\Users\Spencer\Desktop\Rom Hack Starter Pack\pk3DS Build 108\pk3DS.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

pk3DS.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\Spencer\Desktop\Rom Hack Starter Pack\pk3DS Build 108\pk3DS.Core.dll

--------------------
User Message:
An unhandled exception has occurred.
The program must now close.
 
can someone help me??

**Comment by sora10pls** [comment]
Works fine for me... make sure all of the dependencies are there alongside the exe

**Comment by YamiRioru** [comment]
what are my dependencies?? I see that they have something to do with windows.net framework but, idk..

**Comment by sora10pls** [comment]
The files that aren't `pk3DS.exe`
![image](https://user-images.githubusercontent.com/17801814/29245321-e3c43844-7fa4-11e7-9f79-38e55a50e83e.png)

**Comment by YamiRioru** [comment]
thank you :)

**Comment by YamiRioru** [comment]
![screenshot 10](https://user-images.githubusercontent.com/17034478/29245334-01449148-7f8c-11e7-8a6e-d06dd550e3f2.png)
I have those files in there but, I'm still getting the error...

**Comment by sora10pls** [comment]
Delete the files beginning with `System`

**Comment by YamiRioru** [comment]
Exception Details:
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at pk3DS.Core.GameConfig.getGARCData(String file, Boolean skipRelative)
   at pk3DS.Core.GameConfig.InitializeAll()
   at pk3DS.Main.openQuick(String path) in C:\BuildAgent\work\b93f10d64d1a1178\pk3DS\Main.cs:line 219
   at pk3DS.Main..ctor() in C:\BuildAgent\work\b93f10d64d1a1178\pk3DS\Main.cs:line 54
   at pk3DS.Program.Main() in C:\BuildAgent\work\b93f10d64d1a1178\pk3DS\Program.cs:line 29

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

pk3DS, Version=1.0.0.108, Culture=neutral, PublicKeyToken=null
C:\Users\Spencer\Desktop\Rom Hack Starter Pack\pk3DS Build 108\pk3DS.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

pk3DS.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\Spencer\Desktop\Rom Hack Starter Pack\pk3DS Build 108\pk3DS.Core.dll

--------------------
User Message:
An unhandled exception has occurred.
The program must now close.
 right back where I started with... 
my path is...
C:\Users\Spencer\Desktop\Rom Hack Starter Pack\pk3DS Build 108

**Comment by YamiRioru** [comment]
I booted it the first time to edit pokemon moon and when I tried to boot it again, the error started happening... I do not know what is going on here....

**Comment by YamiRioru** [comment]
just grabbed all the original files from the zip I downloaded from the official page on the project page and it still spat an error at me?? what am I doing wrong??

**Comment by YamiRioru** [comment]
deleted the backup folder and nothing happened... can you help me?? I thanked you too early... @sora10pls

**Comment by sora10pls** [comment]
No matter what I try I'm unable to replicate this. Make sure your dump of Moon is clean; dump it with GodMode9 and extract it with .NET 3DS Toolkit or HackingToolkit3DS.

**Comment by kwsch** [comment]
incomplete / missing GARCs; don't tamper with the dump contents manually.
delete/move the rom/exe folder so that it won't try to auto-load the bad dump.
