### ISSUE TITLE
code.bin changes not applying

### ISSUE THREAD

**Issue by tommaniacal** [kwsch/pk3DS#179]
I'm trying to mod pokemon sun so that the TMs are randomized, but so far the changes aren't applying. 
![screenshot 3](https://user-images.githubusercontent.com/31083594/29400145-bd074eb2-82f1-11e7-90a2-ea7dd6d16998.png)
this is where I put the edited bin file, the romfs changes have been working and I haven't had the game crash, but anything that uses the code.bin has not changed. I don't have any other patches or mods to the game (although I'd like to remove the outlines of 3d models if possible), so I don't know what I'm doing wrong

**Comment by sora10pls** [comment]
Not a pk3DS problem; rename it to code.bin
