### ISSUE TITLE
pk3ds does not open exefs

### ISSUE THREAD

**Issue by xshockx** [kwsch/pk3DS#18]
pk3ds wont let me edit code.bin
I tried several methods I had found via google like renaming the folder to exe and ad a peridot before code.bin but the options stay greyed out. I used the version here from Github and compiled it via VisualStudio and I used the version from 12.02.15 from https://projectpokemon.org/forums/showthread.php?44950-pk3DS-XY-ORAS-ROM-Editor-amp-Randomizer

**Comment by kwsch** [comment]
The correct filename for the code binary is ".code" -- note the leading period.

.code.bin instead of code.bin

**Comment by xshockx** [comment]
I used the inbuild exefs unpacker and the code.bin is also called .code.bin

**Comment by xshockx** [comment]
OK I am sorry I found the problem but maybe you should know.
At first I used ctrtool to unpack the exefs.bin and ctrtools extracted a .bin <-- no name .bin file
As I used the inbuild unpacker in your programm it asked if it should overwrite, to which I said yes.
The .bin file of course stayed because it wasnt supposed to be in the exefs.bin. Now I deletet the .bin file and pk3ds works as it should. So ctrtool is maybe buged or did a error this time but you program does not find the .codes.bin file if there is a no name .bin file inside the exe folder.
Sorry if I described it badly im not good at this.

**Comment by kwsch** [comment]
https://github.com/kwsch/pk3DS/commit/fe1f5013f0f22df69ebf6111ec142ee338454a87
