### ISSUE TITLE
how to implement cro edits for gen 7

### ISSUE THREAD

**Issue by Amphar0s** [kwsch/pk3DS#180]
I wanted to randomize the pokemart inventories in pokemon sun, which is in the cro edits section of pk3ds. I couldn't find any tutorials on how to actually put this into the game, and copying the edited cro files into luma/titles/[titleid]/romfs crashes the game. How do I do this?

**Comment by sora10pls** [comment]
Your CROs need to match the currently installed version of the game on your 3DS.

Have 1.2 installed? Edit 1.2 CROs.
Have no update installed? Edit 1.0 CROs.
