### ISSUE TITLE
Static/Gift/Starter .cro files?

### ISSUE THREAD

**Issue by Amphar0s** [kwsch/pk3DS#184]
This isn't exactly a pk3ds issue, but I can't find the information anywhere else. Which files store the randomized Starters, Static Encounters, and Gift Pokemon in Pokemon Y? The Editor for them is located in the cro section, so I'm assuming they're .cro files, but I have no idea which ones they are.

**Comment by kwsch** [comment]
Check the file date modified

**Comment by sora10pls** [comment]
DllField.cro holds the actual data (Starters, Static, Gift, Type Chart), DllPoke3Select.cro are the models when selecting the starters (in all cases, be it Gen 6/1 in XY or Gen 3/2/5/4 in ORAS).
