### ISSUE TITLE
Feature Request: Shiny Option for Static/Gift/Starter Pokemon

### ISSUE THREAD

**Issue by herrfridolin** [kwsch/pk3DS#185]
Is it possible to set a single static/gift pokemon to always shiny?
I didn't find an option in pk3ds (except changing the textures/raising the global shiny rate,
 but I only need one shiny gift pokemon, not all of them).

**Comment by JackTheMenace** [comment]
this is something I asked awhile ago but it's not possible yet so the best idea would be to use layeredfs to temporarily change the shiny rate and then when you're done with it change the shiny rate back to normal

**Comment by herrfridolin** [comment]
Ooops Sorry! Didn't see your request! Thanks for telling me though.
