### ISSUE TITLE
[Bug] Gen 6 Multi Battle AI

### ISSUE THREAD

**Issue by sora10pls** [kwsch/pk3DS#188]
As seen in many Gen 6 randomizer playthroughs, if Max AI is set to all Trainers, the AI in Multi Battles bugs out and has your allies (and the opponents) attack any opponent regardless of which side of the field they're on.

To clarify, Double Battles **are not the same as** Multi Battles.

In pk3DS, all Double Battles (1 Trainer vs 2 Trainers) are marked correctly.
![image](https://user-images.githubusercontent.com/17801814/30038595-83c35158-9194-11e7-9bac-51a471d76a48.png)
Likewise, all Multi Battles (2 Trainers vs 2 Trainers) are marked as **Single** Battles.
Below example is the battle with Matt in the Delta Episode (Multi Battle with Steven).
Note how despite it being a Multi Battle, it's marked as Single.
![image](https://user-images.githubusercontent.com/17801814/30038608-a0b1a81e-9194-11e7-95a0-38194c08a0bf.png)

The fix? Give all Trainers in Single Battles with AI value 133 (default for Multi) the Max Double AI (135), as opposed to the Max Single AI (7).

**Comment by kwsch** [comment]
`10000101` = 133
`10000111` = 135
`00000111` = 7
