### ISSUE TITLE
[Feature Request] Additional flags in move data (SM, possibly ORAS)

### ISSUE THREAD

**Issue by ABZB** [kwsch/pk3DS#189]
In SM move data, there are additional flags at the following offsets in each move's block:
0x3C (4 hex digits, researching what values mean)
0x44 (4 hex digits, might always be 0)
0x48 (2 hex digits, in the binary representation, the first digit seems to be the contact flag, and the third digit seems to be the "recharge turn" flag)
0x4A (2 hex digits, value 0x20 seems to be the flag for Spectral Thief effect)
0x4C (2 hex digits, first binary digit seems to be flag for being a dance move)
0x4E (2 hex digits, might always be 0)

The ones for which I note possible meanings for I have conjectured but not yet tested.

I suspect that some of these apply to XY and ORAS as well, as when I edited that which pk3DS currently handles for the elemental hyper beams a couple of years ago, they still required a recharge turn...

EDIT:
On further experimentation, changing these flags does not seem to change anything in actual gameplay. I suspect that these flags are duplicated elsewhere....

I'm going to continue looking into this.

**Comment by strawpedro** [comment]
out of curiosity, have you by any chance found the flag for whether a move is a pulse move (that can be affected by the ability Mega Launcher) ?

**Comment by kwsch** [comment]
Closed; subset topic of #352 which covers the entire wazadata structure discussion.
