### ISSUE TITLE
[Bug] Editing TMs doesn't set back move descriptions

### ISSUE THREAD

**Issue by sora10pls** [kwsch/pk3DS#191]
After several randomizers, random TMs still have their base move descriptions in the TM pocket.

Gen 6:
https://github.com/kwsch/pk3DS/blob/master/pk3DS/Subforms/Gen6/TMHMEditor6.cs#L132-L149

Likewise, this feature should be added for Gen 7.

**Comment by sora10pls** [comment]
Okay I found the issue. pk3DS *does* update the item text, but the changes don't get saved to the GARC unless the Game Text editor is opened (no other actions are required). Gonna need to test with Gen 7, will edit when I have.

**Comment by kwsch** [comment]
I don't like the internals of pk3DS anymore, but this solution is fine for now :)

**Comment by sora10pls** [comment]
Yeah I've definitely noticed a lack of interest from you hahaha. Maybe with US/UM it'll respark :P
