### ISSUE TITLE
Game Text Male/Female

### ISSUE THREAD

**Issue by valten185** [kwsch/pk3DS#199]
Hello
I modified my Sun ROM for the Game text but when I launch a fight against a Trainer, instead of displaying "Barbara la Capitaine" it appears "Barbara le Capitaine" in French and similar for the objects: "un Potion", "un Poké Ball" in French, so all is put to the male singular .... Can we avoid this? I have the latest version of pk3ds

**Comment by kwsch** [comment]
Duplicate #198
