### ISSUE TITLE
How to create ability banlist?

### ISSUE THREAD

**Issue by tommaniacal** [kwsch/pk3DS#201]
Not exactly an issue, but I am not experienced with coding and don't  know how to use [https://github.com/kwsch/pk3DS/commit/a5f0d173bfb5965cc14a662bbf54290d524a9649](url)

**Comment by kwsch** [comment]
commit message says to create abilitylist.txt in the same folder as the exe, each line having an ability ID per bulbapedia
https://bulbapedia.bulbagarden.net/wiki/Ability#List_of_Abilities

ie

`
1
2
3
4
52
`
