### ISSUE TITLE
Questions regarding item editing in pk3DS

### ISSUE THREAD

**Issue by Peacock1090** [kwsch/pk3DS#207]
I'm currently working on a romhack of Pokemon Moon on my own spare time as I would like to one day get more involved in ROMHacking when I actually know how to program decently, and I wanted to know if it's possible to edit certain values of items in the game.

A thing I know most of you already know are all the unusable items still stored in the game's data. For example, the items they were going to introduce in Black/White that never worked and could only be accessed via hacking (i.e. X Accuracy 6, Ability Urge, etc.), I was wondering if it was actually possible to completely edit those items and replace them with items that were actually usable. I was actually interested in trying to make more held items such as Pikachu's Light Orb Chansey's Lucky Punch etc. but basically the only options you could do in pk3ds's item editor is basically Buy/Sell price and what I'm assuming the Use effect editor is for is what pouch the item goes into. Is it actually possible to go into the item data and hex edit and possibly do more with it than with pk3ds or is it currently not possible to mess with it? I know as of now script editing in the game is impossible, so I wasn't sure if this was the same type of ordeal and I shouldn't even bother with it til we had more info.

Is it also possible to just hex edit how much, say, a Hyper Potion will restore your Pokemon's HP and so on? It's not a big deal but it's just personal preference to edit a few of these values to where they were originally in the previous gens so I wasn't sure if this was possible either.

**Comment by kwsch** [comment]
for romhack purposes, it's mostly just hex editing for now. pk3DS only really cares about item prices.

https://pastebin.com/f3GuVKCs

I know Drayano has added a new evolution triggering item or repurposed regular held items to trigger evolution. By hex editing the UseEffect you can make an item trigger the evolution choose-pkm window, then it depends on the item ID selected in the evolution editor.

For making in-battle effect items, that's usually ExeFS/CRO only where you're inserting your own code. You'd need to know assembly and where to edit at, which is well beyond the scope of pk3DS.
