### ISSUE TITLE
[Bug] RSTE doesn't actually blacklist disallowed Trainer Classes

### ISSUE THREAD

**Issue by sora10pls** [kwsch/pk3DS#209]
Like the title says. With RSTE, when not ignoring Special Classes, it still allows for disallowed Trainer Classes (ones beginning with `[~`) unlike SMTE.

**Comment by kwsch** [comment]
probably this line:
https://github.com/kwsch/pk3DS/blob/1d1227512a05c2f5a633e1ddb7d4f4440baeaaa0/pk3DS/Subforms/Gen6/RSTE.cs#L729
should be changed to:
```c#
while (rIgnoreClass.Contains(rv) || trClass[rv].StartsWith("[~")); // don't allow disallowed classes
```

**Comment by sora10pls** [comment]
That fixed it, PR incoming.
