### ISSUE TITLE
Newest Version of PK3DS Crashes when Randomizing Levelup Moves

### ISSUE THREAD

**Issue by tommaniacal** [kwsch/pk3DS#212]
I recently redownloaded PK3DS (I had an older version) but now, whenever I click "Expand Pool" or "Spread Evenly" and randomize levelup moves, PK3DS crashes. I've redumped my Rom, redownloaded pk3ds, and tried using something other than Visual Studios C++, but every time it crashes with the text "index was outside the bounds of the array", so I'm pretty sure this is an issue with PK3DS itself. 
![screenshot 30](https://user-images.githubusercontent.com/31083594/31417635-7db29084-adf6-11e7-914c-4ebd454de614.png)

**Comment by kwsch** [comment]
>recently

was fixed 3days ago
https://github.com/kwsch/pk3DS/issues/202
