### ISSUE TITLE
[Bug] RSWE randomization speeds have dropped

### ISSUE THREAD

**Issue by sora10pls** [kwsch/pk3DS#215]
As the title says. After randomizing ORAS wild encounters, once pk3DS reaches roughly Location Slot `063` (this may vary for you, I dunno), it begins to greatly slow down and often make pk3DS stop responding.

While in the end it doesn't crash, nor does it fail to randomize, it's strange to know that XYWE uses roughly the same code and RSWE is slower.

I know that I have a fairly well-built PC so I wanted to test. After testing two builds side-by-side (latest [build 216] and commit 12719e0 [build 138]), the older build is significantly faster than the latest.

**Comment by kwsch** [comment]
RSWE has to account for dexnav species count maximums (18 unique slots across all); it's also still constrained to the GUI as the GUI does the majority of the value get/set & saving.

The expanded randomizer options slow things down relative to old ;)

**Comment by sora10pls** [comment]
So it's just a matter of refactoring RSWE for speed like you've done with Personal, Evolution, MoveEditor, etc.? Good to know.

P.S. Those changes have been amazing. Kudos to you for doing it :)

**Comment by kwsch** [comment]
Closing stale issue due to no progress in implementation.

Pull requests implementing the requested features will be accepted.
