### ISSUE TITLE
X/Y Starter Modification Issue

### ISSUE THREAD

**Issue by sora10pls** [kwsch/pk3DS#22]
I recently encountered the fact that when changing the starters in X and/or Y, the models when you select the starter Pokemon do not change. For example, I modified the starters to have the following:

Chespin -> Aegislash
Fennekin -> Cinccino
Froakie -> Volcanion

When I go to select my starter, the models still show Chespin, Fennekin, and Froakie. However, when I actually pick the starter (in my case, Froakie), the dialogue box says, "Matt received Volcanion!" and there actually is a Volcanion in my party.

I'm not sure if that's a problem with pk3DS or X and Y themselves (as I've modified starters in OR/AS and it works like a charm), but it's something I thought I'd bring to your attention. Perhaps if it is a problem with the games, add a prompt that informs the user about it? I dunno haha.

P.S. Sorry for all of the recent issues haha, not my intention to seem needy. I'm just an avid fan of modding the Pokemon games and pk3DS is really just an awesome tool :)

**Comment by kwsch** [comment]
Since it was a read/write issue, please restore the original CRO (either via pk3DS's backup or from your original dump).

**Comment by sora10pls** [comment]
After trying out the latest commit, randomizing starters and closing the form to keep starters a surprise does not actually save, or rather, overwrite the CRO. Modifying, not closing the form, and then clicking Save does overwrite the CRO, but the former (randomizing and closing form) does not overwrite the CRO

**Comment by kwsch** [comment]
Right, it was recently changed to not autosave when the form is closed; **pressing the Save button is required** for changes to be kept.

When randomizing blind it simulates a click on the Save button when done.

**Comment by sora10pls** [comment]
Yeah, that I'm aware of. What I'm saying is that randomizing blind no longer simulates a click on the Save button :P worked fine prior to the latest commit

After clicking Yes, it closes the form, but does not save the changes. http://image.prntscr.com/image/183fdcfe0df2428eb965759f85939600.png

**Comment by kwsch** [comment]
Should be working now.

**Comment by sora10pls** [comment]
Just tested, and yeah it is now haha. Thanks! :)

**Comment by thebrasem** [comment]
question for Sora10 - how did you modify the starters? as far as i know pk3ds crashes when CRO editing. did you resign the files, or somehow didn't crash it? thanks in advance.

**Comment by sora10pls** [comment]
Thank you for bumping this over one year later

CRO edits have never crashed pk3DS. They did however, at one point, crash the game upon load. This has been rectified ever since several CFWs started adding RO module patches (Luma3DS, ReiNand, etc.) that would allow for custom CROs to be loaded.

**Comment by thebrasem** [comment]
I used pk3DS today - when clicking on “Starters” it tells me that “CRO editing currently causes crashes. Continue?” And after randomizing it gets stuck on Not responding. So that’s why I’m asking you - several CFWs have started adding those module patches - how does one randomize starters without pk3DS crashing then?

**Comment by sora10pls** [comment]
Your pk3DS is *immensely* outdated.
![image](https://user-images.githubusercontent.com/17801814/31056259-cc153c1a-a69c-11e7-827d-e768eb6f7cc6.png)
![image](https://user-images.githubusercontent.com/17801814/31056261-d1d2c528-a69c-11e7-9993-41e131701bee.png)

**Comment by thebrasem** [comment]
okay, one week later, and there's a problem.
I got to randomize the startes, but every trainer's pokemon are way too high. The first battle in Pokemon Y - against your rival - is one against a Illumise, lvl 33. Randomized it multiple times, even multiplied the levels in the Trainer editor by 1. Not really feeling like doing this all over again, honestly.

**Comment by sora10pls** [comment]
>(and yes it was outdated, the file i got was from the github/releases. so not the projectpokemon thing.)

@kwsch Can you please lock this issue? Nothing is bugged out and it’s over a year old.
