### ISSUE TITLE
[Feature Request] Important Trainers have 6 Pokemon option for gen 7

### ISSUE THREAD

**Issue by tommaniacal** [kwsch/pk3DS#222]
This is an option in gen 6 games, I don't see why it couldn't for gen 7 also. Important trainers would be your Rival, the Kahunas, the Elite Four, Plumeria, Guzma, Faba, and Lusamine. Having 6 Pokemon would make the game a lot more challenging than it currently is :]

**Comment by kwsch** [comment]
sure, assemble a list of trainer file numbers that should be subject to this modification.
pk3DS doesn't have a way to know which trainer is important other than being told (via code) which IDs are.

**Comment by sora10pls** [comment]
`006, 007, 008, 009, 010, 011, 012, 013, 014, 023, 052, 076, 077, 078, 079, 082, 083, 084, 089, 090, 129, 131, 132, 138, 144, 146, 149, 152, 153, 154, 155, 156, 158, 167, 185, 215, 216, 217, 218, 219, 220, 221, 222, 235, 236, 238, 239, 240, 241, 349, 350, 351, 352, 356, 357, 358, 359, 360, 371, 372, 396, 398, 400, 401, 403, 405, 409, 410, 413, 414, 415, 416, 417, 418, 419, 435, 438, 439, 440, 441, 447, 448, 449, 450, 451, 452, 467, 477, 478, 479, 481, 482, 483, 484`

https://bulbapedia.bulbagarden.net/wiki/List_of_game_characters#Pok.C3.A9mon_Sun_and_Moon

**Comment by tommaniacal** [comment]
Awesome! Thanks for looking those up. Yeah I'd probably leave out the first Hau battles, just to give players a chance to get more pokemon

**Comment by sora10pls** [comment]
Now for USUM!

```
009, 010, 011, 012, 013, 014, 023, 052, 076, 077, 078, 079, 081, 082, 083, 084, 089, 090, 131, 132, 138, 144, 146, 149, 153, 154, 156, 159, 160, 185, 215, 216, 217, 218, 219, 220, 221, 222, 235, 236, 238, 239, 240, 241, 350, 351, 352, 356, 358, 359, 371, 372, 396, 398, 401, 405, 409, 410, 415, 416, 417, 418, 419, 438, 439, 440, 441, 447, 448, 449, 450, 451, 452, 477, 478, 479, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 558, 561, 582, 583, 630, 644, 647, 648, 649, 650, 651, 652
```
