### ISSUE TITLE
[Feature Request] Max Trainer AI for SMTE

### ISSUE THREAD

**Issue by sora10pls** [kwsch/pk3DS#224]
With properly functioning Multi Battle flags! The following Trainer IDs are all the Trainers in SM featured in Multi Battles:

```
220, 221, 222, 241, 438, 439, 440, 441, 442, 443, 444, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456
```

Reference:
`220` - Hau (Aether Paradise, Water Starter)
`221` - Hau (Aether Paradise, Grass Starter)
`222` - Hau (Aether Paradise, Fire Starter)
`241` - Faba (Aether Paradise 1F)
`438` - Hau (Diglett's Tunnel, Water Starter)
`439` - Hau (Diglett's Tunnel, Grass Starter)
`440` - Hau (Diglett's Tunnel, Fire Starter)
`441` - Gladion (Aether Paradise 1F)
`442` - Employee (Aether Paradise 1F)
`443` - Grunt (Diglett's Tunnel)
`444` - Grunt (Diglett's Tunnel)
`447` - Hau (Aether Paradise, Water Starter)
`448` - Hau (Aether Paradise, Grass Starter)
`449` - Hau (Aether Paradise, Fire Starter)
`450` - Hau (Aether Paradise, Water Starter)
`451` - Hau (Aether Paradise, Grass Starter)
`452` - Hau (Aether Paradise, Fire Starter)
`453` - Employee (Aether Paradise 1F)
`454` - Employee (Aether Paradise 1F)
`455` - Employee (Aether Paradise 1F)
`456` - Employee (Aether Paradise 1F)

**Comment by sora10pls** [comment]
Now for USUM; still researching which Team Rainbow Rocket Grunts you battle with Guzma. This would be easier if they didn't all have Lv. 62 Pokémon...

```
241, 438, 439, 440, 441, 442, 443, 444, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 544, 558, 582
```

Reference:
`241` - Faba (Aether Paradise 1F)
`438` - Hau (Diglett's Tunnel, Water Starter)
`439` - Hau (Diglett's Tunnel, Grass Starter)
`440` - Hau (Diglett's Tunnel, Fire Starter)
`441` - Gladion (Aether Paradise 1F)
`442` - Employee (Aether Paradise 1F)
`443` - Grunt (Diglett's Tunnel)
`444` - Grunt (Diglett's Tunnel)
`447` - Hau (Aether Paradise, Water Starter)
`448` - Hau (Aether Paradise, Grass Starter)
`449` - Hau (Aether Paradise, Fire Starter)
`450` - Hau (Aether Paradise, Water Starter)
`451` - Hau (Aether Paradise, Grass Starter)
`452` - Hau (Aether Paradise, Fire Starter)
`453` - Employee (Aether Paradise 1F)
`454` - Employee (Aether Paradise 1F)
`455` - Employee (Aether Paradise 1F)
`456` - Employee (Aether Paradise 1F)
`544` - Employee (Aether Paradise, 1F)
`558` - Guzma (Team Rocket's Castle)
`582` - Lillie (Aether Paradise, 1F)

**Comment by sora10pls** [comment]
Finally finalized all the Trainer IDs that should be ignored for Multi Battles!

**Comment by kwsch** [comment]
It might be better to just change the "Max AI" to instead do `tr.AI |= 7;` instead of `tr.AI = 7;`, as the AI field is bitflags.

The lowest 3 bits toggle progressively smarter AI, and the higher bits are used for augmenting the behavior (multi).
