### ISSUE TITLE
Personal Tab not randomizing all pokemon species

### ISSUE THREAD

**Issue by Amphar0s** [kwsch/pk3DS#225]
This has been consistently happening in Omega Ruby, if I attempt to randomize the personal stats of pokemon, it'll only work for the first 30 pokemon (Bulbasaur through Nidoran) None of the others will change at all, types, abilities, catch rate, etc will be unaltered, even though I still get the message "All relevant entries have been randomized!" It appears to be based off what pokemon are visible in the Current Species drop down bar, because if I jump ahead and randomize it again, it will randomize the next 30 pokemon, but none after that. Either way, it's annoying that I have to randomize it multiple times to get all of the pokemon to be random

**Comment by sora10pls** [comment]
I'm unable to replicate this. Are you sure that you're using the latest build?

I've tested with Omega Ruby 3 times now and it's gone through and modified every species. If you can, please let me know what settings you have (un)checked.

Note that for my testing, I've left everything default checked.
