### ISSUE TITLE
"File Too Big" Error Pls Help!!

### ISSUE THREAD

**Issue by iCow7** [kwsch/pk3DS#226]
So Whenever I try to put my Sun (.3ds) ROM into pk3ds, it says the file is too big. Any suggestions on how to fix? 
![2017-10-29](https://user-images.githubusercontent.com/33207617/32149644-1841a40a-bcde-11e7-8be4-6a9f98283ea8.png)
(Don't mind the background that was my brother)

**Comment by sora10pls** [comment]
pk3DS doesn’t load .3DS ROMs; it loads unpacked RomFS/ExeFS contents, which can then be rebuilt into .3DS after modifying the game data.
