### ISSUE TITLE
pk3ds GARC tools resetting changed hex values

### ISSUE THREAD

**Issue by Peacock1090** [kwsch/pk3DS#228]
This is most likely another dumb error I'm making, but last time I posted about changing item values via hex editing and while it may not really be the answer I've been wanting, it was still useful and I wanted to test changing the values for the amount of HP an item recovers (super potion, berries, and the like.) I found the value that dictates that with HxD, changed it, and saved it. Things were going well enough.

However, after I used the pk3ds' GARC tools as the other ones I was using would just end up corrupting the files, it seemed like after pk3ds would repack the garc files, the hex edits were reset and nothing really changed. While the files weren't corrupt or damaged at least, I just wasn't sure if this was just a small bug or there's just something I'm doing wrong.

Forgot to say thanks for answering my last question though, it was very helpful even if I wasn't able to hex edit everything successfully.

**Comment by kwsch** [comment]
Probably have bak files getting included which screws up the order of files.
You're probably not using the repacked file. Most always it has a file extension when repacked.

**Comment by Peacock1090** [comment]
Turns out I was just seriously not paying any attention and I wasn't keeping track of my repacked GARC file. I just tested it again and the edits seem to be working now.

Again, thanks for your help even if this was basically my fault. I'll go ahead and close this issue.
