### ISSUE TITLE
SM: Pikachu has new evolution method

### ISSUE THREAD

**Issue by evandixon** [kwsch/pk3DS#229]
Found when debugging the PP Pokédex:
![image](https://user-images.githubusercontent.com/2699524/32582707-bf37bbee-c4b5-11e7-8d21-235afeb0e9ff.png)

The pk3DS source defines 40 evolution methods. Pikachu has two evolution methods, one of them being ID 42. When the evolution editor reaches this evolution method, it stops reading evolutions.

The additional evolution methods need to be defined in EvolutionEditor7.

**Comment by sora10pls** [comment]
Same happens with Cubone and Exeggcute.

**Comment by evandixon** [comment]
Rockruff (Form 1) is the only other one AFAIK.

**Comment by kwsch** [comment]
https://github.com/kwsch/pk3DS/commit/a8a8a0bcba2bf22da9f7545f45552471677543cb

Feel free to PR with clearer evo descriptions when fully documented ;)
