### ISSUE TITLE
[Feature Request] Item Editing: Disallow certain items from in-battle use

### ISSUE THREAD

**Issue by DioVento** [kwsch/pk3DS#230]
Certain "Medicine" items like Carbos or Sacred Ash do not appear in the menu during battles. I'd like to be able to alter other items, such as Revives, to be unusable in battle in this manner.

Alternatively, if you could point me at where to hex-edit this (or if it's possible with the existing flags presented in PKHeX's Item Editor) that would be just fine.

**Comment by kwsch** [comment]
More of a research request unrelated to the current functions of pk3DS.

I'd suspect this is related to Item Stats as I haven't seen any 'in-battle show pouch' arrays in the disassembly. Quickly looking at the item stat table (export button to excel/libre calc)...

KeyFlags appears to be a bitflag enum indicating which sub-option the item shows up under in battle?
I'll close this issue, feel free to post any research on the forums.
