### ISSUE TITLE
Garc repacking delivers error message after success message

### ISSUE THREAD

**Issue by hlixed** [kwsch/pk3DS#231]
When repacking a GARC, pk3DS alerts a successful "repacked X files!" message, creates the GARC file, and then emits an error:

```
System.NullReferenceException: Object reference not set to an instance of an object. pk3ds.garcutil.garcpackms() in C:\BuildAgent\work\.....\GarcUtil.cs: line 66
```

I suspect `label` is set to `null` by default, so attempting to access `label.InvokeRequired` is what causes the error. I suppose that makes this a purely cosmetic error, since the GARC file is still produced.

(Also, when repacking an unchanged GARC, pk3DS does not produce a byte-for-byte replica of the original, consistently creating a slightly smaller GARC than the original. Is this a problem? )

**Comment by kwsch** [comment]
Regarding repacking:
https://github.com/kwsch/pk3DS/blob/1e2736ab350c0728d3b4d03351fa9321cc484ac1/pk3DS.Core/CTR/GARC.cs#L95-L100

Haven't had any complaints about the packing size defaulting to 4 having any problems for GARCs originally packed with 0x80 or anything-else-not-4. It might be a micro optimization for the cpu r/w that was utilized for certain files. Dunno ;)

**Comment by hlixed** [comment]
Ah, that makes sense. Thank you for fixing the error message!
