### ISSUE TITLE
It giving an error here

### ISSUE THREAD

**Issue by PreciousTrainer** [kwsch/pk3DS#233]
https://prnt.sc/hbyygw idk why it's giving this after I want repack the folder called 4_g .

**Comment by kwsch** [comment]
the files inside the folder need to have names as integers in order to determine the packing order.

**Comment by PreciousTrainer** [comment]
http://prntscr.com/hc3l7c inside the folder: http://prntscr.com/hc3lc4
the thing is i was repacking compressed bins so the problem is that's why?

**Comment by PreciousTrainer** [comment]
Any idea?
