### ISSUE TITLE
i had a error 

### ISSUE THREAD

**Issue by harvestyt** [kwsch/pk3DS#234]
Exception Details:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at pk3DS.Main.checkIfRomFS(String path) in C:\BuildAgent\work\b93f10d64d1a1178\pk3DS\Main.cs:line 298
   at pk3DS.Main.openQuick(String path) in C:\BuildAgent\work\b93f10d64d1a1178\pk3DS\Main.cs:line 174
   at pk3DS.Main..ctor() in C:\BuildAgent\work\b93f10d64d1a1178\pk3DS\Main.cs:line 54
   at pk3DS.Program.Main() in C:\BuildAgent\work\b93f10d64d1a1178\pk3DS\Program.cs:line 29

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

pk3DS, Version=1.0.0.200, Culture=neutral, PublicKeyToken=null
C:\Users\harvest\Downloads\Randomizer_Tutorial_7\Step #2 - Randomize (pk3DS)\pk3DS.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

pk3DS.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\harvest\Downloads\Randomizer_Tutorial_7\Step #2 - Randomize (pk3DS)\pk3DS.Core.dll

--------------------
User Message:
An unhandled exception has occurred.
The program must now close.

**Comment by kwsch** [comment]
Be sure you are using the latest version of the program with a complete ROM dump.
