### ISSUE TITLE
Unable to edit Trainer name in Trainer Editor.

### ISSUE THREAD

**Issue by Frumentarii** [kwsch/pk3DS#235]
After closing the Trainer Editor tab, the Trainer name does not seem to save, despite everything else saving. 
https://gyazo.com/5114041d8347dc440d7e1cbdae271cdd Here's a demonstration of what happens.

**Comment by kwsch** [comment]
Trainer Names aren't set back on form close, so any changes are discarded.
Didn't fully implement text editing in subeditors.

```
Main.Config.getText(TextName.TrainerNames)
```
https://github.com/kwsch/pk3DS/blob/a04342e3afcc9170d67306aa37e78669b78531f8/pk3DS/Subforms/Gen7/SMTE.cs#L396-L400

https://github.com/kwsch/pk3DS/blob/a04342e3afcc9170d67306aa37e78669b78531f8/pk3DS.Core/Game/GameConfig.cs#L212-L216

fix should be calling setText when the form is closing
