### ISSUE TITLE
[Feature Request] Ultra Wormhole requirement editing

### ISSUE THREAD

**Issue by TRJTRY1** [kwsch/pk3DS#238]
In USUM several of the legendaries available through the ultra wormhole have to have a specific pokemon in the player's party before they will appear, and I was hoping to be able to swap the required pokemon or remove the requirement entirely

**Comment by kwsch** [comment]
Likely script related; would have to be researched for how it works first (on the forums) prior to being considered for implementation.

**Comment by sora10pls** [comment]
If you can edit your ROM, you can edit your save data to get the Pokémon ;)

**Comment by TRJTRY1** [comment]
im working on a romhack trying to see if i can modify the triggers for the events not just bypass the version exclusives ie just editing my save wont help

**Comment by wwwwwwzx** [comment]
sub_2DD0D0 might help.

**Comment by TRJTRY1** [comment]
Sorry, im confused where can I find that information?
