### ISSUE TITLE
Random Held Items for All Wild Pokemon?

### ISSUE THREAD

**Issue by sora10pls** [kwsch/pk3DS#24]
Currently in pk3DS, it is possible to randomize the Held Items of certain Pokemon (I believe you refer to them as 'relevant entries' within the program) in the Personal form.

What this does: modifies the potential Held Items of a Pokemon that can currently be found holding an item in the actual game. For example, Pelipper can be found in the wild holding either a Pretty Wing (50% chance) or a Lucky Egg (5% chance), while a Pokemon like Cascoon has no chance of holding any item when found in the wild.

What I would like to know is if it's possible to not only modify relevant entries' Held Items, but also every entry in the list (798 entries in X/Y & 825 in OR/AS) to have a 50% chance, 5% chance, and 1% chance Held Item. I was considering simply editing all Pokemon to have three possible Held Items, but going through 790+ entries just wasn't what I wanted to spend my time doing lol.

If possible, I was thinking that this could be done through a checkbox (area defined with the red outline) asking if the user would rather have it modify only relevant entries or all entries (checked for only relevant, unchecked for all).

Hopefully this was clear enough to understand and that it is implemented in some form :)

![screenshot_1](https://cloud.githubusercontent.com/assets/17801814/16347843/dba475c6-3a1c-11e6-8039-c5070cef8b4e.png)

**Comment by kwsch** [comment]
Isn't this what the held items checkbox does?

**Comment by sora10pls** [comment]
As I said, it only modifies relevant entries. Pokemon that can't be found holding Held Items regularly aren't modified.

**Comment by sora10pls** [comment]
Latest commit definitely helped. Thanks a ton!
