### ISSUE TITLE
TM, Shiny Rate, Type Chart files???

### ISSUE THREAD

**Issue by edwarbad23** [kwsch/pk3DS#240]
Hi, I'm trying to randomize Pokemon US and I done and transfered all about romfs and works in my game!! But Idk what I do to work the TM, Shiny Rate, Type Chart in the ExeFS tab, I'm tried to create exefs folder in SD cart (like romfs) but nothing happens ( I put 50% Shiny Rate and Randomize the TM) !!!

Plz I need to know what file are for randomize these items!! Thnx very much!!

**Comment by TRJTRY1** [comment]
asuming you're using the luma layeredfs, in the exefs folder there should be a file ".code.bin" copy that file directly to the folder that romfs is in on your sd card rename it "code.bin"
