### ISSUE TITLE
Issue when modifying gametext (USUM)

### ISSUE THREAD

**Issue by NDJohnston04** [kwsch/pk3DS#241]
I've randomized the game text as well as plain old modified it. Here were the results.

When randomizing, the game froze whenever I attempted to load the overworld.

When modifying trainer and class names, their models do not show on the "You've been challenged by xxxx!" screen, and then it crashes when I push A. 

Both times I was using Luma LayeredFS.

**Comment by kwsch** [comment]
so dont randomize gametext, it's probably expecting certain strings.

**Comment by NDJohnston04** [comment]
okay, any thoughts on what happened when I didn't modify anything in GameText but it still crashed the game>?

**Comment by kwsch** [comment]
Don't change trainer classes for battles that require a model to be loaded.

The randomizer correctly skips changing trainer classes if the trainer is used for such purposes.
https://github.com/kwsch/pk3DS/blob/e0ec1dac38dfee43c94e0c417e7f779d47a243cc/pk3DS/Subforms/Gen7/SMTE.cs#L608-L623
