### ISSUE TITLE
Pokemon names in Traditional/Simplified Chinese not displaying correctly

### ISSUE THREAD

**Issue by strawpedro** [kwsch/pk3DS#262]
![qq 20171220015827](https://user-images.githubusercontent.com/34144805/34201590-cf47e5b0-e529-11e7-908f-b30a6a05ecba.png)
Not sure what is causing this, the text file 60 containing all the pokemon names is not showing the characters correctly. Seems to be the only file that's having this issue, the rest of the text files works just fine.
working example: (this one is for trainer names)
![qq 20171220020551](https://user-images.githubusercontent.com/34144805/34201750-5be843e8-e52a-11e7-9ed9-949d59cd47c9.png)

**Comment by kwsch** [comment]
It's displaying correctly. The game uses a special font for those values.
