### ISSUE TITLE
Randomizing TMs for Pokemon Ultra Sun & Moon

### ISSUE THREAD

**Issue by uscdude92** [kwsch/pk3DS#273]
Hi, I've tried MULTIPLE methods in attempting to randomize the TM's in Ultra Sun & Moon, but have failed each time. Is there something I'm forgetting to do, or something different I need to do? Thanks.

**Comment by sora10pls** [comment]
Using Luma LayeredFS, move `code.bin` to `sd:/luma/title/<title_id>/`

`00040000001B5000` = Ultra Sun
`00040000001B5100` = Ultra Moon

If running 1.1 update data, ensure you either:
- Use a `code.bin` dumped from the patch
- Delete the patch to properly load initial release (1.0) `code.bin`

Not a bug, this can be closed.
