### ISSUE TITLE
Wild Pokemon Moveset

### ISSUE THREAD

**Issue by uscdude92** [kwsch/pk3DS#275]
Hi, I just finished randomizing Ultra Moon, and everything is working well, until I caught my first encounter, which was an Armaldo, yet its moveset isn't randomized, unlike my starter was. Do you know why this is? Thanks.

**Comment by kwsch** [comment]
You must have randomized gift moves but not learnsets.

**Comment by sora10pls** [comment]
Do remember that Route 1 has a static encounter as your first ever encounter, and wild Pokémon have their moves auto-populated by the game. If you randomized learnsets *after* static encounters, pk3DS will have set Armaldo’s normal moves seeing as how it’s a static encounter and learnsets have not yet been randomized.

**Comment by uscdude92** [comment]
so whats the difference between level-up moves, and learnsets, and do i do level-up moves BEFORE static encounters

**Comment by uscdude92** [comment]
i just had another instance, where the first Totem pokemon was musharna, and it had psybeam/hypnosis/defence curl (a.k.a. its normal moveset)

**Comment by uscdude92** [comment]
Never mind, I realized what you meant sora10pls, thank you so much!!
