### ISSUE TITLE
Support for Sun&Moon?

### ISSUE THREAD

**Issue by goteniai** [kwsch/pk3DS#28]
Dummy Message

**Comment by kwsch** [comment]
Probably will be a separate but similar tool, a few things have changed... enough to warrant another program to handle it.

**Comment by goteniai** [comment]
Thanks for the prompt reply. Have you come up with the solution to extract files from the new GARC?

**Comment by thatsmyface** [comment]
I am also interested in how I should go about extracting the models from the Sun and Moon Demo as well. Please let me know if you guys come up with anything. Standard GARC Extractors are not working and all crash.

**Comment by giodude12** [comment]
Same, wanna live my maxie fantasies

**Comment by goteniai** [comment]
Hi, I've made a few changes to your GARC-Unpack Form1.cs file. With this new file, I can extract contents from the new GARC File. But writing back is a much harder. The OTAF file number is no longer the same as BTAF file number. And for each BTAF segment, some of the data do not have the same meaning. (Most do.) And the stuff at the end of the file is confusing too. Attached is the file with the changes I've made and some original garc files you can study.

https://drive.google.com/drive/folders/0B7_vosH0Fm0ydTJTM0FIcmNtcUU?usp=sharing

**Comment by iApplepet** [comment]
Hey @goteniai can you upload to GDrive a compiled version of it? I have a feeling I might be able to do something with it.

**Comment by thatsmyface** [comment]
Yeah. Can you tell me how to run this new version of it?

**Comment by goteniai** [comment]
@iApplepet @kwsch This is a compiled version: https://drive.google.com/file/d/0B7_vosH0Fm0yUUc0VExIWXJqcDQ/view?usp=sharing
