### ISSUE TITLE
PK3ds Crash Error

### ISSUE THREAD

**Issue by Endermeen** [kwsch/pk3DS#293]
When I launch the program and enter any of the tabs, and then I X out of the tab itself. I get this fatal error and it crashes the whole thing. I'm running a Windows 10 64-bit computer. I tried to run as administrator, delete Temp folder contents and reinstall the program, nothing works. I know the problem is related to memory somewhere, or on my computer, but I have no idea how to fix it, someone lend a hand?

Exception Details:
System.IO.IOException: The process cannot access the file 'C:\Users\Ameen\AppData\Local\Temp\tmp4F2D.tmp' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at pk3DS.Core.CTR.GARC.packGARC(Byte[][] data, Int32 version, Int32 contentpadnearest)
   at pk3DS.Core.CTR.GARC.MemGARC.set_Files(Byte[][] value)
   at pk3DS.Main.<B_Evolution_Click>b__40_0() in C:\BuildAgent\work\86ef6ef9a1b8eb38\pk3DS\Main.cs:line 719
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

pk3DS, Version=1.0.0.301, Culture=neutral, PublicKeyToken=null
C:\Users\Ameen\Desktop\3DS Randomizer Pack\Step 2 - Randomize\pk3DS.exe

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

pk3DS.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\Ameen\Desktop\3DS Randomizer Pack\Step 2 - Randomize\pk3DS.Core.dll

--------------------
User Message:
An unhandled exception has occurred.
The program must now close.

**Comment by kwsch** [comment]
Please don't post issues to multiple locations.
https://projectpokemon.org/home/forums/topic/34377-pk3ds-3ds-rom-editor-randomizer/?do=findComment&comment=227777
