### ISSUE TITLE
Trainer Levels

### ISSUE THREAD

**Issue by uscdude92** [kwsch/pk3DS#296]
Hi, whats the best way to raise levels of trainers in the game, or what would you recommend? I tried multiplying by 1.05, but the levels are like, 30 when they should only be 22, 23. Did I do something wrong? Thanks.

**Comment by kwsch** [comment]
If you've run the randomization multiple times you'll get the compound increases you're witnessing

**Comment by sora10pls** [comment]
As mentioned before, make sure you’re only applying a Level boost if you have clean Trainer Data GARCs loaded.

Example: applying a 15% boost one day...
Lv. 50 (clean) * 1.15 => Lv. 57
...and then applying a 15% boost another day...
Lv. 57 (the newly boosted Level) * 1.15 => Lv. 65

I’m unable to replicate this using the latest build and with clean GARCs.
