### ISSUE TITLE
Tutorial how to Build.

### ISSUE THREAD

**Issue by Xanadu16** [kwsch/pk3DS#3]
I keep running into issues like my VS saying "error MSB3577: Two output file names resolved to the same output path" which usually means a resx conflict so it'd be nice to have a guide to follow building on either Windows Mac or Linux.

**Comment by kwsch** [comment]
No idea; I don't tune my projects for mac/linux. 

All I do with VS is press build/debug and have no issue with compiling.

**Comment by Xanadu16** [comment]
Well I have an issue compiling, it gives me a "error MSB3577" error, which means a resx conflict. What VS do you use?

**Comment by kwsch** [comment]
VS2010 C# Express &/ VS 2012 Professional
