### ISSUE TITLE
Error when loading Pokèmon Ultra Sun

### ISSUE THREAD

**Issue by Filo97** [kwsch/pk3DS#315]
> Exception
> 
>  Details:
> System.OverflowException: Le dimensioni della matrice hanno superato l'intervallo supportato.
>    in pk3DS.Core.TextFile.get_LineData()
>    in pk3DS.Core.TextFile.get_Lines()
>    in System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
>    in System.Linq.Buffer`1..ctor(IEnumerable`1 source)
>    in System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
>    in pk3DS.Core.GameConfig.InitializeGameText()
>    in pk3DS.Core.GameConfig.InitializeAll()
>    in pk3DS.Main.openQuick(String path) in C:\BuildAgent\work\ccf72a59f9911202\pk3DS\Main.cs:riga 215
>    in pk3DS.Main.B_Open_Click(Object sender, EventArgs e) in C:\BuildAgent\work\ccf72a59f9911202\pk3DS\Main.cs:riga 98
>    in System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    in System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>    in System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    in System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    in System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    in System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>    in System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    in System.Windows.Forms.Control.WndProc(Message& m)
>    in System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    in System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>    in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> Loaded Assemblies:
> --------------------
> mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
> C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll
> 
> pk3DS, Version=1.0.0.327, Culture=neutral, PublicKeyToken=null
> C:\Users\fnova\Documents\pk3DS Build 327\pk3DS.exe
> 
> System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
> C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
> 
> System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
> C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll
> 
> System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
> 
> System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
> C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
> 
> System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll
> 
> System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
> C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
> 
> System.Windows.Forms.resources, Version=4.0.0.0, Culture=it, PublicKeyToken=b77a5c561934e089
> C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms.resources\v4.0_4.0.0.0_it_b77a5c561934e089\System.Windows.Forms.resources.dll
> 
> pk3DS.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
> C:\Users\fnova\Documents\pk3DS Build 327\pk3DS.Core.dll
> 
> mscorlib.resources, Version=4.0.0.0, Culture=it, PublicKeyToken=b77a5c561934e089
> C:\Windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_it_b77a5c561934e089\mscorlib.resources.dll
> 
> --------------------
> User Message:
> An unhandled exception has occurred.
> You can continue running the program (albeit with potential side-effects), but please report this error.

**Comment by kwsch** [comment]
Likely trying to load bad ROM data. Needs more context besides the error message.

Is this a clean decrypted ROM dump?
Have you successfully used the program on the same dump with prior versions?

**Comment by Filo97** [comment]
This is downloaded with Villain3DS. Decrypted the encrypted .cia with latest hackingtoolkit. Didn't work.
Downloaded with Villain3DS. Decrypted the decrypted (on 3ds) .cia with HackingToolkitV9. Didn't work.
Last time i tried was about three or four months ago, with pokèmon ultra moon, and it worked.

**Comment by Filo97** [comment]
Pokèmon Alpha Sapphire obtained in the same exact way seems to work.

**Comment by sora10pls** [comment]
Perhaps try dumps of your actual copy of the game ~~if it exists~~ ;)
