### ISSUE TITLE
Not really an issue, just a quick question. Thank you

### ISSUE THREAD

**Issue by triiscrazy** [kwsch/pk3DS#323]
Hi, this is not really an issue, i just have a question on how to use Move Editor. I was trying to edit moves that require recharging next turn like Giga Impact or Hyper Beam, basically trying to get rid of the recharging, for my personal play only. But I couldnt figure out how to do it. Have anyone successful done this please teach me how. Thank you for an awesome program, sorry for being a noob.

Also, is there a way to add a switch out effect to moves, for example moves like U-turn or Volt Switch would  switche the user out, so i was just wondering if I can add similar effect to other move. 

Thank you so much

**Comment by kwsch** [comment]
https://github.com/kwsch/pk3DS/issues/189
not known how exactly the data needs to be edited, if it's even possible with just move data editing (ie, there's special handling in the game code for carrying out the more complex moves).
