### ISSUE TITLE
Game Soft-locked

### ISSUE THREAD

**Issue by S00nai** [kwsch/pk3DS#325]
Not sure if this is entirely the randomizer's fault or not, but I Just thought that I'd bring this to attention.

The game had soft-locked after I had killed a mega garchomp that Emily was using when you first fight her in the school. Once I had killed the garchomp, it played it's death animation but once any of my pokemon tried to learn a move the garchomp came back invisible with health in the red. I couldn't do anything to it at all. It was fixed by changing the garchomp to another pokemon.

Emily was randomized to a Team Rainbow Rocket member, the moves of the garchomp were randomized by the levelup stipulation, and held items were randomized as well. The garchomp had sand attack, sandstorm, tackle, and absorb as moves.

**Comment by S00nai** [comment]
Oh wait, I meant the teacher not Ilima

**Comment by kwsch** [comment]
Probably best to post it in the forum thread since it isn't clear what is going wrong.

**Comment by OMNIVader23** [comment]
What probably went wrong here is when randomized the base HP of Mega Garchomp became lower then the Base HP of Garchomp meaning when he de-Megaevolves he has health left confusing the game
