### ISSUE TITLE
Starters stuck as Sunkerns

### ISSUE THREAD

**Issue by TheHolyZekken** [kwsch/pk3DS#326]
Whenever I click the "Randomize all starters" button the first set of starters are always Sunkerns. I've tried restarting pk3ds and reinstalling. ![sunkerns](https://user-images.githubusercontent.com/38623952/39096567-977e0eaa-461f-11e8-82d4-634c2a7d1270.PNG)

**Comment by sora10pls** [comment]
Unable to replicate after numerous attempts

**Comment by TheHolyZekken** [comment]
UPDATE: Selecting "Keep same gen" changes what pokemon is repeated. I tried it with ORAS and rather than Sunkerns it kept choosing Kricketots and after selecting "Keep same gen" it changed it to Azurills.

**Comment by kwsch** [comment]
It randomizes based off BST +/- 20% of the current species; multiple randomizations may result in extremes (random low -> random lower -> random lowest). Restore the original files and re-randomize.

**Comment by TheHolyZekken** [comment]
Restoring and re-randomizing didn't fix it.
