### ISSUE TITLE
[Bug] File Restoration not working

### ISSUE THREAD

**Issue by sora10pls** [kwsch/pk3DS#327]
Have tested with all game types (XY, ORAS, SM, USUM), and pk3DS fails to restore original files despite it saying that it did.

Steps I did to test this:
- Get a clean dump of a game
- Open it with pk3DS
- Make sure that the backup was created (path below)
`C:\Users\Matt\Randomizers\pk3DS\backup\1_x`
- Randomize Personal Stats
- Close the editor, and restore files
- Re-open pk3DS, Personal data is *still* randomized

This happens with every editor, files just fail to restore properly. I've even double-checked the generated `a`, `dll`, and `exefs` folders before restoring, and all the files were backed up correctly. Manually replacing the game data with said backups works fine, though the file restorer itself doesn't work.

From what I'm gathering, pk3DS overwrites existing backups for games after the game is loaded for a second time, getting rid of vanilla data in favor of edited data; I think this should be changed to where if a backup exists and data is loaded for a second time, the data shouldn't be overwritten - it defeats the purpose of restoring original files if it just restores data that isn't vanilla.

EDIT: Replacing backup files with vanilla data and then restoring immediately after also does not properly restore the vanilla data.

**Comment by kwsch** [comment]
pk3DS saves any persistent data when the form is closing; restoring backups doesn't reload after restoring, thus the originally loaded data is re-saved (overwriting the newly restored data).

You have to either manually kill the application (there is no Application.Exit or whatever call at the end of the restore) or hold control(?) when closing the program to disable writebacks.

**Comment by kwsch** [comment]
https://stackoverflow.com/a/13046082

Application.Exit triggers forms to call their Closing/Closed events:
https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/Application.cs,1094

(calls ExitInternal); should call Environment.Exit(-1) to completely kill pk3DS instead.
Before that, can restart the program with Process.Start(Application.ExecutablePath);

**Comment by sora10pls** [comment]
Restoring backup files still overwrites backup files just after restoring original files with the latest commit.
![image](https://user-images.githubusercontent.com/17801814/40272646-b4bed930-5b7e-11e8-9a87-aaf8af3e7a80.png)
