### ISSUE TITLE
Randomisation not taking effect

### ISSUE THREAD

**Issue by TentacoolThings** [kwsch/pk3DS#328]
hiya, I've been trying to randomize my pokemon ORAS and Moon cartridges and while pk3ds has been working perfectly fine and I've double checked that it's saving my randomizations I've been having issues when I apply the appropriate files matching my changes that when I load it up in game that they haven't taken place like starters and (for ORAS ) the poochyena static encounter. All update data for these games has been removed and I've done this process with multiple dumps of the game just in case that was the issue 

I've looked through dozens of issues on here to try and find a fix and nothing I have done has worked i hope someone can help me solve this issue it would be very much appreciated

**Comment by TentacoolThings** [comment]
https://youtu.be/k-pnqSsJBv0 


For reference this is the video I’ve been using I followed it originally but it wasn’t working with pk3Ds becuase I copied to gm9/out rather than decrypting but changing to Decrypt is the only different thing I’ve done from this tutorial

**Comment by kwsch** [comment]
@sora10pls 

Closing as this is not an issue with the program.
