### ISSUE TITLE
[BUG] [USUM] Randomizing encounters leads to Alolan Sandslash have normal Sandslash's level up moveset

### ISSUE THREAD

**Issue by TheEvilTurnip** [kwsch/pk3DS#332]
I just started a randomizer of Pokemon Ultra Moon and my first encounter was an Alolan Sandslash. After I captured it at level 4 it's moves were Poison Sting, Sand Attack, Scratch, and Defense Curl, which reflect what a normal Sandslash's moves would be at that level. An Alonan Sandslash would normally have Slash, Defense Curl, Ice Ball, and Metal Claw at level 4.

I have not yet checked to see if this is an issue with all Alolan forms or uniquely Sandslash's.

**Comment by kwsch** [comment]
The `FormStatsIndex` isn't modified by the personal editor (to somehow point to regular sandslash).

Could be that the randomized encounter was Sandslash-0 but the game forced it to be Sandslash-1 due to some undocumented alola rules?

**Comment by TheEvilTurnip** [comment]
Also important to note that this was the VERY first encounter on Route 1, which is normally locked to a Pikipeck, I'm not sure if this counts as a static encounter or not. Either way I want to locate it in pk3DS but when I look under Route 1 in I do not see a Sandslash, Alolan or not...

**Comment by kwsch** [comment]
@sora10pls Form is being assigned after moves are being fetched; needs to be reversed.

https://github.com/kwsch/pk3DS/blob/54fef2c6860d2e8c44d7f02d0a6235b187a44454/pk3DS/Subforms/Gen7/StaticEncounterEditor7.cs#L632-L637
