### ISSUE TITLE
[Bug] USUM Species in SM

### ISSUE THREAD

**Issue by sora10pls** [kwsch/pk3DS#334]
As I brought to your attention in DMs, SpeciesRandomizer currently fails to properly check for MaxSpeciesID, allowing for 803-807 to be rolled when randomizing SM (this should only be possible with USUM).

Unsure as to why this is the case, though.

https://github.com/kwsch/pk3DS/blob/63600a2a35a7bd5a9a7d31909256e7ffcf2704aa/pk3DS.Core/Randomizers/SpeciesRandomizer.cs#L203-L207

**Comment by kwsch** [comment]
Is this even an issue? Config has the max species ID at 802

https://github.com/kwsch/pk3DS/blob/698f03317a05dd7fe07d76f92f855ad83ebb3f75/pk3DS.Core/Legality/Tables7.cs#L8

https://github.com/kwsch/pk3DS/blob/698f03317a05dd7fe07d76f92f855ad83ebb3f75/pk3DS.Core/Game/GameInfo.cs#L42-L58

Thus the SpeciesRandomizer internal list of species shouldn't emit any species 803+

**Comment by sora10pls** [comment]
Yes. Randomizing SM with Legendaries/Mythicals added to species randomization can lead to this:
![image](https://user-images.githubusercontent.com/17801814/42470529-be34be1c-8388-11e8-98f0-37a613317926.png)

And after checking in hex to be certain, values can range from 0x323 (803) to 0x327 (807). I'm not even sure why it does this considering the check mentioned in my original comment.

**Comment by kwsch** [comment]
https://github.com/kwsch/pk3DS/blob/da0f1f6eca0c76eeb11a1ade8d35b9dc87389179/pk3DS/Subforms/Gen7/SMTE.cs#L602-L616

The internal species list should be initialized there; try checking if the list contains anything above 802?

With debugging, you can always find out why :)

https://github.com/kwsch/pk3DS/blob/da0f1f6eca0c76eeb11a1ade8d35b9dc87389179/pk3DS.Core/Randomizers/SpeciesRandomizer.cs#L14-L28
