### ISSUE TITLE
Shiny rate editor not taking effect ORAS

### ISSUE THREAD

**Issue by Kirito312** [kwsch/pk3DS#340]
So, I’m new to this, but every time I change the shiny rate on OR, the changes don’t take effect. It’s as if nothing saves. I believe I’m recompiling it correctly and I always remember to change .code.bin to code.bin. Again, I’m new to this so I don’t know what’s going on. Help? Every other change I make takes effect besides the shiny rate.

**Comment by kwsch** [comment]
>Every other change I make takes effect besides the shiny rate.
does this include any other changes to the exefs/code.bin? Remove any installed game updates as any game patch overwrites the exefs/code.bin.

**Comment by Kirito312** [comment]
No, everything else with exefs/code.bin goes through perfectly. And there are no installed updates.
