### ISSUE TITLE
[Small Oversight/Bug] Ash Greninja stuck in Active form

### ISSUE THREAD

**Issue by TheEvilTurnip** [kwsch/pk3DS#344]
As someone who enjoys have pretty vanilla randomization, I don't like having permanent mega evolution and stuff like that appear, basically anything that isn't legit. And while you can disable those from being randomized into it Battle Bond Ash Greninja can appear in it's Active form and will never revert back to it's original form. I only noticed this issue with Ash Greninja, but it may also be in other form based Pokemon as well such as Zen Mode Darmanitan.  Just thought I'd bring this to your attention.

**Comment by kwsch** [comment]
Would have to be added here:
https://github.com/kwsch/pk3DS/blob/6a36a86a63b74645feb2dbd360557288d952ade9/pk3DS.Core/Randomizers/FormRandomizer.cs#L17-L37

probably just a greninja only check

**Comment by TheEvilTurnip** [comment]
It is possible to encounter a permanent Active form Ash Greninja. I just thought of Zen Mode Darmanitan as an example of another potential illegal encounter for vanilla randomizer such as myself. However I just encountered a School Form Wishiwashi as well.  Wishiwashi should never "appear" in it's school form unless it was a Totem Wishiwashi, which it was not especially considering this is Ultra Moon version where there is none.  This makes me suspicious about any Pokemon that has a form change mid battle, such as Greninja, Wishiwashi, Darmanitan, Aegislash, Mimikyu (and Totem), Minior.  These Pokemon all have abilities which change their form during battle, however they will never start out in their alternative forms (assuming full HP), so I was just hoping you could add in a check for Greninja and Wishiwashi and see if the other Pokemon could potentially cause any issues as well.
