### ISSUE TITLE
[Feature Request] Progress bar for Garc unpacking and repacking

### ISSUE THREAD

**Issue by freshspicc** [kwsch/pk3DS#345]
It'd be useful to have some sort of indicator that the program is actually running, especially with repacking which can take hours for some files.

**Comment by kwsch** [comment]
GARC packing is usually pretty fast; the slow part is the compression of any LZ compressed files that were decompressed by the user.

There's a way to skip decompressing all files when unpacking by holding control; this will make repacking much faster. The downside is that you have to individually decompress files.
