### ISSUE TITLE
Can't seem to get CRO or exeFS randomisation to work ORAS, Sun and Moon

### ISSUE THREAD

**Issue by MermRage** [kwsch/pk3DS#349]
For ORAS:
I can't randomise Starters
Shiny percentage 
Poke Mart items 
Static pokemon 
Random items
player models and names 
(Basically everything in CRO and exeFS files)
For Sun and Moon:
Shiny rate 
random items 
player models and names 

HELP ANYONE I'M SO CONFUSED I FOLLOWED EVERY TUTORIAL AND NOTHING 
(FOR CITRA)

**Comment by MermRage** [comment]
btw this is for Citra

**Comment by kwsch** [comment]
This is not a place to get generic help.
