### ISSUE TITLE
[bug] pokemon x trainer gift items

### ISSUE THREAD

**Issue by plurple** [kwsch/pk3DS#353]
I may well have done something wrong when I randomized but when I defeat a trainer and they give me an item they weren't meant to give me they don't say anything just white text box appears before and after I relieve the item. but also if I talk to the trainer after I have defeated them I get the white text boxes and receive the item again.

**Comment by kwsch** [comment]
Working as intended, the text files have a line allocated for post battle messages. pk3DS does not set anything to it.

Can't edit scripts yet hence the repeat behavior.
