### ISSUE TITLE
Build #360 Trainer Pokemon Move Sets

### ISSUE THREAD

**Issue by MeDrChang** [kwsch/pk3DS#358]
Hi,

 I may be missing something but i am unable to set trainer pokemon move sets to match the level up move sets that i randomise in pk3DS build 360. i am trying to randomise this in Alpha Sapphire, and have read through your responses to similar issues but have had no luck myself. 

If i select "don't modify" then the move sets remain as they were originally set.
If i select "randomise all" then they are all completely random as described.
If i select "use level up only" then it seems to set the moves back to the pokemons original move set and the moves don't correlate to the randomised level up move set. 

I hope that makes sense and thanks in advance.

**Comment by kwsch** [comment]
Are you randomizing the learnsets in the other editors first?

**Comment by MeDrChang** [comment]
I think so...

I go into "level up moves" then randomise them and back out and go on to randomise the trainers. That's what I assumed yet it seems to retrieve the standard unrandomised one for me.
