### ISSUE TITLE
[Feature Request] Edit more easily the Encounter Rate of wild encounters (1 button)

### ISSUE THREAD

**Issue by edwarbad23** [kwsch/pk3DS#359]
Hi! I try to do a Randomize a US game but it's very tedious and tiring edit one for one the Encounter Rate of each table and I saw that there was not the option to edit more easily the encounter rate for all locations, so I was wondering If you could add that option, maybe an option to "Put 10% each enounter all tables locations" or "randomize all encounter rate all tables locations".

Thnx for all!!

**Comment by kwsch** [comment]
Closing stale issue due to no progress in implementation.

Pull requests implementing the requested features will be accepted.
