### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by ewormPL** [kwsch/pk3DS#365]
If possible, an option to export all of all moves' data to a txt file would be appreciated. Should help analyse what certain effect and flag numbers mean, what qualities of moves are tied to what element of their data etc. Hopefully it's not a difficult thing to implement?

**Comment by kwsch** [comment]
Already there; see [Export Table] on the right.

![image](https://user-images.githubusercontent.com/6393368/44408041-68253d00-a514-11e8-9c9c-a84213d047c8.png)
