### ISSUE TITLE
Z-Effect more obvious

### ISSUE THREAD

**Issue by ewormPL** [kwsch/pk3DS#367]
It's awesome to see the Move Editor enhanced in the newest builds, but the one thing I still wish would be clearer is the effects of the status Z Moves. It'd be more convenient to simply pick a "+2 SpA" option from a list, rather than cross-reference every time what number corresponds to which effect and type that in.

**Comment by kwsch** [comment]
Migrating from previous issue (#352) by @Tyulis, which confirmed my initial hunch:

```
After a few research, values as 0x22 and 0x23 seem to be indeed Poké Refresh stats.
So at 0x22, there is the effect:

    0 : None
    1 : Disheveled
    2 : Mud
    3 : Dust
    4 : Dry

And at 0x23 that's the probability of these effects to happen if the pokémon uses or is hit by the move. There are plenty of other parameters, but they are not related to moves.
```

Might have to rearrange the layout of the editor to accommodate wider controls (instead of having 0-255 number entries).
