### ISSUE TITLE
EggMoves and Sprites doesn't appears of Alolan Form Pokémon

### ISSUE THREAD

**Issue by Asia81** [kwsch/pk3DS#37]
The EggMoves list of Alolan forms Pokémon doesn't appears, same with their sprites.
http://image.noelshack.com/fichiers/2016/46/1479646327-vulpixa.png

(Goupix = Vulpix)

I just need to dump the list, I don't need to edit it.

**Comment by kwsch** [comment]
Generation 7 support is still a work in progress.
