### ISSUE TITLE
Alternate Form Sprites in Gen 7 Move Editors

### ISSUE THREAD

**Issue by sora10pls** [kwsch/pk3DS#370]
In the Gen 7 Level Up Editor, sprites for alternate forms are either not displayed or not displayed correctly.

If Pikachu, Cosplay sprites are used instead of Cap sprites.
If any other Alternate Form (Mega, Primal, etc), no sprite is displayed at all.

The reason behind this is that Alternate Form 1 is disregarded, and the program tries to display Alternate Form 2. Since most of these Pokémon only have 1 Alternate Form, nothing is displayed. 

I found this out because Lycanroc 1 displays Dusk Lycanroc (Lycanroc 2), but Lycanroc 2 displays nothing. Same goes for Charizard, Mewtwo, and whatever other examples I can't think of right now.

Egg Move Editor shows no sprites for any Alternate Forms.

![image](https://user-images.githubusercontent.com/17801814/44689487-b7440400-aa25-11e8-9d46-d3fce588956f.png)
![image](https://user-images.githubusercontent.com/17801814/44689457-97acdb80-aa25-11e8-8d9c-7423ec0c313b.png)
![image](https://user-images.githubusercontent.com/17801814/44689461-9bd8f900-aa25-11e8-82e3-8ab7ae8e5e14.png)
![image](https://user-images.githubusercontent.com/17801814/44689530-d6db2c80-aa25-11e8-884f-f34b00f249bb.png)

**Comment by kwsch** [comment]
PKHeX was the original source of the current sprite generating code, and I don't think every change was copied over.

I'm trying to avoid dll hell / actually installing PKHeX; maybe I can split off the image generation code to a separate dll (for use in other projects, like PKHeX) and look at using ILMerge again for regular builds.

**Comment by kwsch** [comment]
Closing stale issue due to no progress in implementation.

Pull requests implementing the requested features will be accepted.

Probably can just borrow & rewire the pkNX sprite building code if this is still desired.
