### ISSUE TITLE
Two QoL fixes

### ISSUE THREAD

**Issue by ewormPL** [kwsch/pk3DS#372]
Little "quality of life" things I'd like to see:

- the moves taught by the tutors from USUM are editable. For the longest time I had no idea this was the case, simply because the option is located under "PokéMart" editing. A separate or renamed button would be appreciated. I may be the only idiot who missed this, but I may not.

- the TypeChart editor could use labels for the rows/columns - indicating both which side is the offensive/defensive one (Attack/Pokémon) and also which type is represented by which row. The text displaying below helps, but is not the most intuitive. The red/green/black boxes themselves are good enough indicators for me, though I could see some preferring they actually contained "2x", "0,5x" and "0x" in them. But that's a nitpickiest of nitpicks.

**Comment by kwsch** [comment]
Closing stale issue due to no progress in implementation.

Pull requests implementing the requested features will be accepted.
