### ISSUE TITLE
ORAS Pokémon Contest data missing

### ISSUE THREAD

**Issue by mk360** [kwsch/pk3DS#375]
The Pokémon Contest Spectaculars moves data is lacking, and for my use case, it's pretty useful, to say the least. Could you please add them into the Moves Editor panel ^-^?
Oh and by the way, I feel it's also necessary to add an option allowing us to dump _all_ the moves into text, just like the Level Up Moves editing section does.

**Comment by kwsch** [comment]
Contest data for moves is not stored in the Move Data that is viewable in the Move Editor; it'd likely be in another garc which is currently undocumented.

Would need to be fully documented on the forums prior to being a candidate for implementation in pk3DS.
