### ISSUE TITLE
Randomized Trainer Pokemon have original Pokemon moveset.

### ISSUE THREAD

**Issue by Khrystarlite** [kwsch/pk3DS#377]
I randomized the all the trainer Pokemon, but they all have the movesets of the pokemon they replace. For example, Hau's Pichu was randomized to a Giratina, but only had Pichu's moves.

Did I miss something in the UI that will help me fix this issue?

**Comment by kwsch** [comment]
There's a moveset randomizer option in one of the trainer editor tabs, which can specify what is to be done with the pkm's moveset when randomizing.
