### ISSUE TITLE
Trainer Randomization Error 

### ISSUE THREAD

**Issue by Dcbeich** [kwsch/pk3DS#384]
Hi everybody, I've been trying out the pk3DS program for the first time, and I've come upon a problem when randomizing Y version. The randomizations have worked fine for the starter pokemon, wild encounters, and for the trainers... until they get to their second pokemon. Just by facing a few of the trainers in the first couple areas, their first pokemon sent out is randomized, but the second comes out have been A) level 100 Alakazam that softlocks the game with any move it uses, B) level 100 Charizard (with Mega Gardevoir cry) that does not break the game, and C) level 54 Excadrill that does not break the game. When the trainers are viewed in the pk3DS editor, they do not have these overpowered 'mons and instead have typically randomized ones. Does anyone have any ideas why this might be happening?

**Comment by kwsch** [comment]
likely bad data when you're transferring it to your 3DS; not a pk3DS issue

use layeredfs + luma so that you aren't re-encrypting a romfs; other than that, no idea.

**Comment by Dcbeich** [comment]
I used Luma v9.1, so that utilizes layeredfs, so I don't think that's the problem.
I went over all the steps I did, but I couldn't quite figure out what happened. I tried the method with Omega Ruby and I didn't get the same error. I'll report back if I figure out what exactly happened with Y version.

**Comment by kwsch** [comment]
Thanks for the follow up 👍
