### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Kharik** [kwsch/pk3DS#388]
Hello, 

I'm a new adventurer at CFW and decided to randomize my Pokémon Sun. Everything goes fine, i got god9, luma, fbi and everything needed to use Pk3DS. 
When I delete my update file, and run the game, it crashes and then shutdown. It asks me to save the error to the dump or press any button to shut it down. If I start a new game, it goes ok, until I can move my character.
Any one know what's wrong?

I saw @sora10pls replying some1, but I couldn't understand what was wrong with it.

![image](https://user-images.githubusercontent.com/44231205/47084531-19c9ad00-d1ea-11e8-860a-15c831fe84c3.png)

Edit: Btw, I'm sorry in advance if this isn't the correct place to ask this.

**Comment by sora10pls** [comment]
Your problem lies with your ExeFS/CRO edits. Either remove the files from your SD Card (`code.bin` and/or `Shop.cro`) or re-randomize them with clean files from a new & clean dump of the game.

Not a bug with pk3DS.
