### ISSUE TITLE
Height/Weight Reading changes values upon directly viewing entry

### ISSUE THREAD

**Issue by MightyBirdy** [kwsch/pk3DS#39]
Like #32 , but it will dump correctly the first time. (On the latest build.)

Three dumps were done: pk3DS 1.0.3 dump and pk3DS latest's first dump were identical. 

Discovered after initial latest build dump that Bulbasaur and Eternal Flower's values had changed, due to starting and ending on them.

Scrolled through every single entry and back to see what would read incorrectly afterwards.

The result is this: https://www.diffchecker.com/JHD7wMog 

There still seems to be an issue with decimal points despite 36eba31 and 9b327db being meant to handle this.

**Comment by kwsch** [comment]
Thanks for checking; loading was working fine, just the string->value->save not behaving 👍
