### ISSUE TITLE
[Bug] [USUM, but probably all games] 'Metronome Only' mode in Moves menu causes catching tutorial softlock

### ISSUE THREAD

**Issue by RCTMASTA** [kwsch/pk3DS#391]
Not sure about this behavior in XY/ORAS/SM but I imagine it's probably the same, except possibly with a move other than Tackle:
Tackle's PP needs to be set to 1 instead of 0 when using Metronome Only mode, in order to prevent a softlock during the catching tutorial in USUM.

**Comment by kwsch** [comment]
@sora10pls lol
