### ISSUE TITLE
Personal Stats dumps lack TM learnability data

### ISSUE THREAD

**Issue by Ntonio36** [kwsch/pk3DS#394]
The list of the TMs a Pokémon can learn is lacking from the generated text dumps, as well as the moves learnt from Special Tutors. So yeah, the button stating "Dump All" is pretty misleading :p.

**Comment by kwsch** [comment]
Would have to expand the dumping logic; only dev-chosen surface info is dumped:
https://github.com/kwsch/pk3DS/blob/263f7ca9099c99ee582bfd7196fac23fa5209bb4/pk3DS/Subforms/Gen7/PersonalEditor7.cs#L400-L442
