### ISSUE TITLE
Handle more "Edge" cases if not done already.

### ISSUE THREAD

**Issue by Xanadu16** [kwsch/pk3DS#4]
TwitchPlaysPokemon would like to eventually do a Gen 6 randomizer run, but we need to know if stuff like "does it handle edge cases? like getting a garbage starter? or other progress inhibiting situations?" is handled.

Example, Magikarp with Splash is chosen as a starter, which is a junk starter. Or suddenly Gym 1 has an Arceus on its team.

Reference Universal Pokemon Randomizer ( https://github.com/Dabomstew/universal-pokemon-randomizer ) for its flexibility. I actually filed a issue with his tool for Gen 6 support since I liked how flexible his tool was, but didnt offer Gen 6 support.

**Comment by Xanadu16** [comment]
First such edge case: 1st trainer in X/Y was given a Shedinja, even though if the game used default Wild data there isnt anything that can potentially KO it.

**Comment by kwsch** [comment]
Fixed Shedinja edge case by preventing it all together in RSTE; also managed to spot a bug in the species list (regis begin at 377 not 337).

[Prevent Shedinja in RSTE & Fix Random G3 Species](https://github.com/kwsch/pk3DS/commit/76026adae6dbf787da514eacadbcd65c89ee88c8)

**Comment by Xanadu16** [comment]
It should be a togglable option ("Allow Wonder Guard?") or something, but this works.

**Comment by kwsch** [comment]
Implemented by SciresM
https://github.com/kwsch/pk3DS/commit/76028db6f4628d8932e3cf8d8359ffd9735a9fe2
