### ISSUE TITLE
Compile a new release?

### ISSUE THREAD

**Issue by dawnbomb** [kwsch/pk3DS#400]
was gonna compile the changes and try it out, and then i realized i'm on a craptop with parents for christmas without visual studio.

anyway, it seems last  normal download release was 3 Years ago! i imagine a bunch probibly happened in this time. any shot we can get a admin to release a 1.0.4 already? :p

**Comment by kwsch** [comment]
https://projectpokemon.org/home/forums/topic/34377-pk3ds-3ds-rom-editor-randomizer/
there is no 'release' for this program; every commit is compiled and is available for download in the thread

**Comment by kwsch** [comment]
right click
projectpokemon has its own discord
https://projectpokemon.org/chat/

**Comment by FrostKnight** [comment]
How do you download an artifact?

I get here:

https://dev.azure.com/project-pokemon/pk3DS/_build/results?buildId=9171&view=artifacts&pathAsName=false&type=publishedArtifacts

and click on pk3ds, and it doesn't let me download it. or anything.
