### ISSUE TITLE
Pokemon sun not working now?

### ISSUE THREAD

**Issue by dawnbomb** [kwsch/pk3DS#401]
fresh extract files, open in PK3ds, do literally nothing (just LOOK at trainers and some menus, change nothing), put it back together and try to run it and the game crashes / refuses to boot.

can anyone confirm the most recent version still actually works for gen7 games? as in the game will still run? works fine in X and sapphire, not at all with ultra sun.

**Comment by MegaKBang** [comment]
If you really changed nothing... then why did you put all the files into the 3ds?
If there are no changes then just play it without the layeredfs lol
And yes it still works with gen 7 for me

**Comment by dawnbomb** [comment]
i had a mild hunch and decided to test if it would fail on doing nothing, and it did.  another guy on the discord can't get this to work either, i tried downloading previous build as well incase, same thing. hmmm...

only thing i can think of is it worked on my laptop abit, now im on my pc and it fails so... some.. hardware thing...?
