### ISSUE TITLE
is there any guide on how to "properly use" PK3ds?

### ISSUE THREAD

**Issue by dawnbomb** [kwsch/pk3DS#402]
sorry for using this as a forum, but i don't see anywhere else and the discord is pretty dead.

is there any actual guides on how to use PK3ds? theres a discord with no pins, a forum link with a single topic thats all over the place, this github page, but no actual straight up explanation. i mean, not even a read me!

i couldn't figure out for the life of me why i kept getting "organize my folders" error / alert, and theres like nothing online.  best i could find is this shoft, and covers only a little, PDF guide. it says there would be a part 2 for recompile, and i presume i already know how, but i guess sense i was already not using proper folder structure / ect and getting errors, i bet i don't know how to compile either. (PDF link downloadable over here at https://www.maxconsole.com/threads/how-to-properly-use-pk3ds.36995/ 

anyway, is there a actual full in depth guide for from dumping the rom/files to everything to use PK3ds and turn it back into a properly playable rom/ect? you'd think if PK3ds cares about file structure so much it would actually tell us how to use it properly? (i mean i guess it gives a alert/error but like, something more?)

i know it's not a "big thing" to development but for actually USEING the program, it kinda is a issue yeah?

**Comment by kwsch** [comment]
pk3DS has been out for years. There are numerous tutorials on the internet on how to use it.

pk3DS just edits individual files

1. Dump romfs & exefs binaries (using other tools & tutorials)
2. Unpack romfs & exefs binaries to get the individual files (using other tools & tutorials). Keep the romfs and exefs contents in separate folders, as noted by the thread.
3. Now you can edit individual files. pk3DS automates the hex editing at this stage.
![image](https://user-images.githubusercontent.com/6393368/50545273-5559fd80-0bc3-11e9-9194-ee8ccf1041e6.png)
4. When done, close program.
5. Repack romfs & exefs, using other tools, or copy folder to use with layeredfs/saltysd (following those tutorials).
