### ISSUE TITLE
[Bug] [X/Y] Trainer healer box corrupts test permanently

### ISSUE THREAD

**Issue by dawnbomb** [kwsch/pk3DS#404]
if you make a trainer a healer, the text for the trainer becomes a complete blank if you speak to them. if you later unselect the healer box, the text stays corrupt.   the incode text does not change, but the game won't display it anyway.

(and also, a really glitchy double/triple heal thing happens that you can't escape)

**Comment by kwsch** [comment]
Text for the trainer becomes blank because the associated text line is blank. You'd have to fill the appropriate line in with whatever text you want them to say.
