### ISSUE TITLE
Encounter Tab in Sun and Moon

### ISSUE THREAD

**Issue by trainboy2019** [kwsch/pk3DS#41]
Whenever I click on the Wild Encounter Tab, pk3DS loads, but before it finishes, it freezes and says pk3DS stopped working. I downloaded and rebuilt the source code at around 11:55 P.M on 11/21/16 EST. Here is the problem log. 

> Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	pk3DS.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	5833cfdf
  Problem Signature 04:	pk3DS
  Problem Signature 05:	1.0.0.0
  Problem Signature 06:	5833cfdf
  Problem Signature 07:	243
  Problem Signature 08:	34
  Problem Signature 09:	System.ArgumentException
  OS Version:	6.3.9600.2.0.0.768.101
  Locale ID:	1033
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	1318
  Additional Information 4:	13181ae637ac2592fac0ca2dd662cdcc

**Comment by kwsch** [comment]
Generation 7 support is still a work in progress. SMWE still needs to be updated for full functionality anyway.
