### ISSUE TITLE
An Unhandled exception has occurred

### ISSUE THREAD

**Issue by friendlytiger** [kwsch/pk3DS#410]
So i'm trying to get pk3DS to work but whenever I click on one of the boxes to change something this log pops up:

An unhandled exception has occured. The program must now close.
**Exception Details:**
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at pk3DS.Main.<B_Personal_Click>b__34_0() in C:\BuildAgent\work\ccf72a59f9911202\pk3DS\Main.cs:line 580
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Loaded Assemblies:**
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

pk3DS, Version=1.0.0.394, Culture=neutral, PublicKeyToken=null
C:\Users\besny\OneDrive\Desktop\3DS Randomizer Pack\Step 2 - Randomize\pk3DS.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

pk3DS.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\besny\OneDrive\Desktop\3DS Randomizer Pack\Step 2 - Randomize\pk3DS.Core.dll

--------------------
User Message:
An unhandled exception has occurred.
The program must now close.

I've tried to extract the data from the game again in case there was an error but it still didn't work. I also tried to copy the game data that was in my SD card again adn restart from the begining but it didn't work even then. I'm hoping someone can help and thanks for your time.

**Comment by kwsch** [comment]
Bad ROM dump.
https://github.com/kwsch/pk3DS/search?q=System.IndexOutOfRangeException%3A+Index+was+outside+the+bounds+of+the+array.&type=Issues

**Comment by friendlytiger** [comment]
> Bad ROM dump.
> https://github.com/kwsch/pk3DS/search?q=System.IndexOutOfRangeException%3A+Index+was+outside+the+bounds+of+the+array.&type=Issues

How do I re-dump it?

**Comment by friendlytiger** [comment]
Nvm I fixed it yay

**Comment by MottekeSF** [comment]
HOW did you fix it?

**Comment by Chaos1080** [comment]
@friendlytiger  Can u say how u did it?

**Comment by friendlytiger** [comment]
@chaos1080 I think I solved this problem when a friend fixed it for me. Sorry, but I don't know how he fixed it.
