### ISSUE TITLE
I'm sure you've answered this before, but...

### ISSUE THREAD

**Issue by fieryxx7** [kwsch/pk3DS#411]
I'm literally brand-new to this. i've found a couple other places where my issue is located, but your replies on them were literally to the tune of 'i've already answered this before, bad dump(bad tutorioul) bad times".
 but i need some help. i'm pulling my hair out mate. i can't find anything other than a lot of people asking the same questions. if the answers are out there, i'm either missing them or looking in the wrong holes.

To the point, the issue i'm having is that i'm trying to randomize Pokemon Sun. i've seen the tutorials, i've read that Braindump is no longer working. i've tried several other methods from youtube comments. I've copied the exefs/romfs folders to my sd card, i've dycrted the entire0000010.app to the gmd9 folder. but when i open pk3ds to start randomizeing, i can't get the folder to open properly. it keeps giving me this error 
Exception Details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at pk3DS.Core.GameConfig.InitializePersonal()
   at pk3DS.Core.GameConfig.InitializeAll()
   at pk3DS.Main.openQuick(String path) in C:\BuildAgent\work\ccf72a59f9911202\pk3DS\Main.cs:line 226
   at pk3DS.Main.B_Open_Click(Object sender, EventArgs e) in C:\BuildAgent\work\ccf72a59f9911202\pk3DS\Main.cs:line 101
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

pk3DS, Version=1.0.0.394, Culture=neutral, PublicKeyToken=null
C:\Users\fiery\OneDrive\Desktop\pk3dds\pk3DS.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

pk3DS.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\fiery\OneDrive\Desktop\pk3dds\pk3DS.Core.dll

Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running the program (albeit with potential side-effects), but please report this error.

If you can please help me, you might also be helping a lot of people who are arriving here a year or more later and unable to find the answers that are years old at this point.

**Comment by kwsch** [comment]
Program is working fine. As prior issues have said, bad ROM dumps/unpacking causes the program to misbehave. pk3DS expects sane data.

GitHub Issues aren't the place for general troubleshooting; the forums provide a thread for requesting help using the program.

YouTube guides are notorious for these problems.
