### ISSUE TITLE
Some trainers were given pokemon with no moves

### ISSUE THREAD

**Issue by saphiroko** [kwsch/pk3DS#415]
I randomized the trainers and their pokemon, but some pokemon in trainer battles have no moves and only use Struggle. I don't remember exactly what settings I used, but I didn't modify their moves at all. Has anyone else had this issue?

**Comment by kwsch** [comment]
Restore backups and try again.
It would help if you indicated the game you were modifying, as well as the precise settings so anyone can try and replicate the issue. Works for everyone else currently, can re-open if this is a recurring issue for others.
