### ISSUE TITLE
file doesn't match count

### ISSUE THREAD

**Issue by fishmandoigus** [kwsch/pk3DS#419]
I know you answered this already but I'm getting this problem and I was going through a video guide and used the extract.bat file to get the exe/romfs. And after that it still says that it doesn't match the file count. Is there anything I'm missing? Help would be very much appreciated :)

**Comment by kwsch** [comment]
the program expects a fully unpacked ROM.
if the count of files in your folders does not match any of the ROMs unpacked file counts, it gives you that message, indicating your dump is incomplete or is not the right files.
