### ISSUE TITLE
Pk3ds move help

### ISSUE THREAD

**Issue by deoxys15** [kwsch/pk3DS#422]
Hi﻿ ﻿all. I was editing moves with pk3ds and i have the following issues:

How can edit the move belch to be an ordinary move, without ﻿﻿﻿needing to eat a berry in order to perform It? ﻿

 ﻿﻿How can I edit doom desire﻿ and﻿ ﻿future sight in order to be a 1 turn normal move?

How can I edit burn Up so you dont lose fire type once performed?

Maybe It has something to do with "0xb"?

Thanks all!﻿

**Comment by kwsch** [comment]
Looking at emerald, it looks like it is determined by the effect:
https://github.com/pret/pokeemerald/blob/8064b011d142cfb7a6c8aa1f8366b85a6ff4e45a/src/data/battle_moves.h#L4592-L4603

0xB is move inflict duration, which defines the permanence of an effect:
https://github.com/kwsch/pk3DS/blob/5faeb58378b562c6121f6cbe356767ae28f6838c/pk3DS.Core/Structures/Moves/MoveInflictDuration.cs#L3-L10

You might be able to copy the move data from Pound (copy the bin) and see if that has any result. If not, it would probably require editing the game code; the game code has some move IDs hardcoded for special processing.

**Comment by deoxys15** [comment]
What bin should i edit?
