### ISSUE TITLE
Trainer rebattle with pk3ds

### ISSUE THREAD

**Issue by deoxys15** [kwsch/pk3DS#423]
I'm﻿ ﻿currently editing trainers' teams. What is the checkbox "flag"? Is this for a rematch? Can I enable rematches for f.e., Hala, which only battles you once after the elite 4 or dexio, nanu or mina﻿?﻿﻿

**Comment by kwsch** [comment]
No idea what the flag does; it's just exposed for editing. 

I'm pretty sure what you want to do is managed by scripts instead. When you beat the elite four, the game scripts can clear event flags that would allow the overworld entity to trigger a rebattle.
