### ISSUE TITLE
Doesn't load in directories

### ISSUE THREAD

**Issue by duckspacito** [kwsch/pk3DS#425]
The program can't load in a file directory.

**Comment by kwsch** [comment]
Can you elaborate?

Be sure to extract the program to a stable location (not temporary files, not run from the zip). When loading a game, you have to have a complete ROM dump.

**Comment by snake0484** [comment]
I've not used this program before and i believe i'm encountering this issue, when you say "complete rom dump extracted" do you mean the .bin files such as "HeaderNCCH0.bin"

**Comment by kwsch** [comment]
Refer to the thread. It expects exefs and romfs folders in the root of the folder you've selected. YouTube guides should easily illustrate this.
