### ISSUE TITLE
Crash when trying to open personal stats

### ISSUE THREAD

**Issue by Silver2608** [kwsch/pk3DS#426]
I have been trying to randomize my Pokemon Alpha Sapphire game and had it working apart from a crash when opening the personal stats file. I tried a redump then a different method of dumping but nothing fixed this error. Now when I try to open the pk3ds app it aborts.

Any help would be appreciated

**Comment by Silver2608** [comment]
I have now been able to fix the opening issue but the crash still occurs when trying to edit personal stats.

**Comment by kwsch** [comment]
Bad ROM dump.

Search previous issues for your error message.
