### ISSUE TITLE
Error occurs when trying to set shiny rate for Pokemon Y

### ISSUE THREAD

**Issue by pinkclouds94** [kwsch/pk3DS#428]
I get this error when I click the Shiny Rate option. It doesn't give me the ability to edit at all, just throws this error and tells me to abort the program. Seeing as this was the only thing I wanted to change in my Pokemon Y game, it's very irritating.

It first tells me 

.code.bin not decompressed. Aborting.

Then goes to

Unable to find PID Generation routing. Closing.

Then gives the following:

An unhandled exception has occurred.
You can continue running the program (albeit with potential side effects), but please report this error.
Please provide the following information when reporting this error,

Exception Details:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at pk3DS.ShinyRate..ctor() in C:\BuildAgent\work\ccf72a59f9911202\pk3DS\Subforms\ShinyRate.cs:line 59
   at pk3DS.Main.B_ShinyRate_Click(Object sender, EventArgs e) in C:\BuildAgent\work\ccf72a59f9911202\pk3DS\Main.cs:line 1030
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

pk3DS, Version=1.0.0.402, Culture=neutral, PublicKeyToken=null
C:\Users\Pink Clouds\Desktop\Pokemon RNG Tools\3DS Randomizer Pack\3DS Randomizer Pack\Step 2 - Randomize\pk3DS Build 402\pk3DS.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

pk3DS.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\Pink Clouds\Desktop\Pokemon RNG Tools\3DS Randomizer Pack\3DS Randomizer Pack\Step 2 - Randomize\pk3DS Build 402\pk3DS.Core.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running the program (albeit with potential side-effects), but please report this error.

**Comment by kwsch** [comment]
You didn't completely dump the ROM data.

>.code.bin not decompressed. Aborting.
