### ISSUE TITLE
Cant open a file

### ISSUE THREAD

**Issue by Burstinatrix** [kwsch/pk3DS#434]
Hi, 
first thanks for that tool
so it's about a month now that i try and cant manage to do it.
Got the ultra moon rom decrypted .3ds format for citra and i try to randomize it,
i used hackingtoolkit9ds pressd D and put it in his own folder
no problem here
until i try to run pk3ds and Nothing it doesnt open the file and i cant do anything :/
any helps ? did i make Something wrong ?

**Comment by kwsch** [comment]
pk3DS expects clean dumps with the correct file count. You can always try debugging in Visual Studio 2019 Community

**Comment by Burstinatrix** [comment]
Debugging in visual studio? How am I supposed to do that?
