### ISSUE TITLE
repacking size smaller when editing evolution/mega / black screen in game Sun/moon

### ISSUE THREAD

**Issue by MrShawnTRods** [kwsch/pk3DS#44]
the issue with evolution editing and mega evolution editing has not been solved for sun and moon.  the size of the files become smaller and trying to load the game after repacking gives black screen.

**Comment by evandixon** [comment]
How are you repacking the ROM?  If it's using my .Net 3DS Toolkit, then the black screen is not caused by pk3DS.

**Comment by MrShawnTRods** [comment]
With asia81's toolkit.

Not making any changes after extracting the cia and repacking doesnt cause any size differences and issues. But if i make any changes to evolution and mega evolution, it makes the size about 7mb smaller. installs fine but then game doesnt load.

how do you repack?

**Comment by sora10pls** [comment]
I just tested editing evolution methods for certain Pokemon, put the GARC onto my SD Card and loaded it into the game using SaltySD, worked perfectly fine. I experienced no size differences with the GARC.

For reference: /a/0/1/4

**Comment by MrShawnTRods** [comment]
Weird. The size becomes smaller when compiling the cia after editing.
But stays the same when no modification is made. (game runs fun after installing when no modification is made, and its extracted and rebuilt)

**Comment by MrShawnTRods** [comment]
Since extracting the game and rebuilding it untouched runs it fine.
but editing with pk3ds and rebuilding doesnt run fine, I cant see the link as to why it woudnt be pk3ds related?

**Comment by sora10pls** [comment]
Considering I haven't had the issue with (multiple) edits to the Evolution GARC, I wouldn't be so sure. Are you using the latest commit to test?

**Comment by MrShawnTRods** [comment]
I have tried a different decrypted cia.
Unpacking the cia and repacking results in 3,144,559 KB (which is its orignal size.)
Changing Abra's evolution to Infernape(as an example) and then repacking results in 3,136,944

**Comment by MrShawnTRods** [comment]
Mind uploading a compiled version of the latest commit for me? Just in case, I will try again.

**Comment by sora10pls** [comment]
[pk3DS.zip](https://github.com/kwsch/pk3DS/files/634483/pk3DS.zip)

**Comment by MrShawnTRods** [comment]
Same issue with your build.
But I noticed that the garc sizes stay correct with your build. But the final generated cia after editing is small yet again. I guess editing something and repacking is causing the issue?

Is there any other working method to repack cia apart from SaltySD?

**Comment by MrShawnTRods** [comment]
Ya, I have been trying for weeks with every single commit with the same result. Since the untouched repack doesnt cause any problems, I was sure it was related to pk3ds.

I am trying to look into salty3ds but cant really find proper instructions on how to use it with Pokemon Sun/moon

**Comment by MrShawnTRods** [comment]
Close this issue please.

Looks like every method of repacking edited cia causes the cia size to be wrong. Nothing wrong with pk3ds.
