### ISSUE TITLE
Downloading

### ISSUE THREAD

**Issue by PotatoZion** [kwsch/pk3DS#441]
When I tried to download pk3ds it didn't work, I watched a couple of youtube tutorials, still didn't work. I couldn't figure out what was wrong but I knew that I didn't have the application that was shown in the picture. I don't know what's wrong but I need some help

**Comment by kwsch** [comment]
The thread on ProjectPokemon describes how to download. It's the same process as pkNX.

**Comment by PotatoZion** [comment]
The problem is I don't have the things described on the thread

**Comment by PotatoZion** [comment]
The file I downloaded was called pk3DS-master.zip

**Comment by PotatoZion** [comment]
never mind got it to work
