### ISSUE TITLE
Pk3ds Master Folder Doesnt have the pk3ds application itseld

### ISSUE THREAD

**Issue by deKippenpootje** [kwsch/pk3DS#443]
So when I download the Pk3ds Master folder, i cant find the launcher to the actual randomizer application, and I cant find it anywhere else on the internet.

Could someone please help me to get a good version of pk3ds?

**Comment by kwsch** [comment]
You downloaded the code, not the compiled program.

Re-read the download instructions.

**Comment by deKippenpootje** [comment]
Where can I find the download instructions, and are they so clear that even a dumdum like me can understand?

**Comment by kwsch** [comment]
https://projectpokemon.org/home/forums/topic/34377-pk3ds-3ds-rom-editor-randomizer/

It's linked at the top of the repository.
