### ISSUE TITLE
CRO is overwritten

### ISSUE THREAD

**Issue by supersem2004** [kwsch/pk3DS#447]
Im pretty new to randomizing and I dont think this is a pk3DS problem I think its more like a citra problem or a problem with the PC itself but I figured you might be the best to ask. I have randomized a few games for my friends so we can play nuzlockes together. My randomizers have worked with everyone exept for one guy. The games will launch but they just arent random. When I try them on my own PC they are random. This problem is on Omega Ruby and Alpha Sapphire and on X and Y. But not on Ultra Sun and Ultra Moon. I have searched a lot for him and I think the .CRO are overwritten. Do you guys know anything about this? I am clueless.

**Comment by kwsch** [comment]
Not a pk3DS issue that your method of playing the game doesn't load the edited file.
