### ISSUE TITLE
EDITING doesn't work ANYMORE?

### ISSUE THREAD

**Issue by AdaptableJojo** [kwsch/pk3DS#449]
Hi!
I downloaded PK3DS a week ago and had much fun with it but there is an issue which makes life a bit hard and it is quite the same with every ROM I tried:
I download a ROM, copy and extract it and edit it with PK3DS, all fine until now. But if I do those steps again (with some games it doesn't work at all but mostly it stops working after the 2nd or 3rd successfull edited ROM), some things won't work anymore, no matter if I use the same or another ROM dump, I tried nearly everything now.
These things that stopped working were:
- Trainer editing in Ultra Moon AND Ultra Sun (everything else still worked)
- Wild encounter editing in Omega Ruby (everything else still worked)
I asked the same question elsewhere and got the answer that I use bad ROM dump(s).
But there are things that don't make sense then:
- An exact copy of the same ROM dump worked before
- Other ROM dumps don't work either
- It happened with every game I tried to edit
I have got no clue what is going on and would be really thankful if someone had and told me!

**Comment by AdaptableJojo** [comment]
The error is always the same:
Exception Details:
System.ArgumentOutOfRangeException: Der Wert 120 ist für Value ungültig. Value sollte zwischen 'Minimum' und 'Maximum' liegen.
Parametername: Value
   bei System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   bei System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   bei pk3DS.Main.<B_Trainer_Click>b__39_0() in D:\a\1\s\pk3DS\Main.cs:Zeile 698.
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

pk3DS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\johan\Desktop\Citra Stuff\Randomizing\drop\pk3DS\bin\Release\pk3DS.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

System.Windows.Forms.resources, Version=4.0.0.0, Culture=de, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms.resources\v4.0_4.0.0.0_de_b77a5c561934e089\System.Windows.Forms.resources.dll

pk3DS.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\johan\Desktop\Citra Stuff\Randomizing\drop\pk3DS\bin\Release\pk3DS.Core.dll

OptaneShellExt, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b2b395177cd09cef
C:\Program Files\Intel\OptaneShellExtensions\OptaneShellExt.dll

SharpShell, Version=2.2.0.0, Culture=neutral, PublicKeyToken=f14dc899472fe6fb
C:\Program Files\Intel\OptaneShellExtensions\SharpShell.dll

log4net, Version=1.2.15.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a
C:\Program Files\Intel\OptaneShellExtensions\log4net.dll

PinningServiceApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d2c7ef10062b7593
C:\Program Files\Intel\OptaneShellExtensions\PinningServiceApi.dll

System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.ComponentModel.Composition\v4.0_4.0.0.0__b77a5c561934e089\System.ComponentModel.Composition.dll

mscorlib.resources, Version=4.0.0.0, Culture=de, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_de_b77a5c561934e089\mscorlib.resources.dll

--------------------
User Message:
An unhandled exception has occurred.
The program must now close.

**Comment by kwsch** [comment]
pk3DS has not received any changes in 9 months.
