### ISSUE TITLE
Cannot patch the game

### ISSUE THREAD

**Issue by LucarioRanger** [kwsch/pk3DS#454]
The game did not patch for the randomize update. I have the pk3ds omega ruby's Luma folder on the SD card

-I have no update data on the SD card (32 GB). 
-Used PK3ds, and tried to patch the game using pk3ds "luma" folder
-Copied&paste all files from the GARCs list
-"Luma" Folder was copied and pasted into SD card

**Comment by kwsch** [comment]
Not an issue with pk3DS.
