### ISSUE TITLE
randomized TM learnsets broken

### ISSUE THREAD

**Issue by pingexe** [kwsch/pk3DS#455]
when i randomized TMs they work fine as the new randomized move, but who can actually learn them is based off what the TM used to be, for example in ORAS bulk up was randomized into roost but i could teach it to a Darmanitan and not a Mandibuzz. idk how to fix

**Comment by kwsch** [comment]
Not broken.

The move that a {TM Item} teaches is separate from what {TM Items} a given Species-Form can learn.
