### ISSUE TITLE
Clicking Randomize All in Trainer Editor crashes when randsettings.txt is present with NUD_Level=1.0

### ISSUE THREAD

**Issue by jahnpm** [kwsch/pk3DS#456]
This happens because decimal.TryParse(s, out var n) parses "1.0" as 10, which is too large.
Fix is to replace decimal.TryParse(s, out var n) in RandSettings.cs (line 82) with:
decimal.TryParse(s, NumberStyles.AllowDecimalPoint, CultureInfo.CreateSpecificCulture("en-GB"), out var n)

**Comment by kwsch** [comment]
Did you copy the randomization settings file from another computer?

**Comment by jahnpm** [comment]
No, it was saved by pk3DS on my machine. It saves as "1.0", but when trying to parse, it ignores the dot and returns 10. Maybe because the current culture of my system is the wrong one, but my suggestion should make it really culture independent.
