### ISSUE TITLE
Starter Pokemon Location/Totem Pokemon location

### ISSUE THREAD

**Issue by DeathChaos25** [kwsch/pk3DS#46]
Just wanted to leave a heads up about what I've found so far that could possibly be implemented, this is all from the a/1/5/5 garc file.

0.bin contains some static "gift" Pokémon, this contains the 3 starters and fossil Pokémon, there's 20 Blocks here and each of them is 0x14 in size, with the first two bytes being the Pokémon's ID, the order for this file is;
The 3 starters;
Omanyte, Kabuto, Aerodactyl, Lileep, Anorith, Cranidos, Shieldon, Tirtouga, Archen, Tyrunt

A small example of this being edited is [here](https://www.youtube.com/watch?v=RCkSl2iLXVQ).

1.bin contains a few important wild encounters, notably the Totem Pokémons, some of the Pokémon fought within the trials, and other key encounters such as the Ultra Beast, or the very first Pikipek the player finds.

Each block is 0x38 in size and there's roughly about 137 blocks in here.
I did a small data dump that can be found [here](http://pastebin.com/DBkKY0e2).  

I may be wrong about some values, but from what I've seen it's usually;
Pokémon ID (2 bytes), - Form (1 byte) , - Level (1 byte) , - Held Item (2 bytes), - 6 bytes that I skipped because I don't know what they are for now, - moves (2 bytes each), - Nature (1 byte), - IVs (1 byte each)  
There's still a lot of bytes that I haven't figured out, but this was enough to get a good rough idea for the blocks.  

In 4.bin, it seems to have blocks that are 0x34 in size, but I don't really know what data they contain.

The other files is just data that I don't know what it is, but 0 and 1 are at least very useful.

**Comment by kwsch** [comment]
Already knew about this, just haven't implemented any editor. X/Y/OR/AS had these in CROs and since Gifts, Encounters, and Trades are in the same GARC, have to make a single editor to handle all three. For PKHeX I had parsed these files for the legality checking engine:

```
private static readonly EncounterStatic[] Encounter_SM = // @ a\1\5\5
// Gifts - 0.bin
// Static Encounters - 1.bin
// Trades - 4.bin
```

https://github.com/kwsch/PKHeX/blob/master/PKHeX/Legality/Tables7.cs#L103
