### ISSUE TITLE
Can't randomize starter X/Y update 1.5

### ISSUE THREAD

**Issue by TiredFerreira** [kwsch/pk3DS#460]
So I was having trouble randomizing my starters in my X game ver 1.5, the out of nowhere I decided to test the starter randomize using the Y version ver 1.2 and it worked!

After that. I restarted the game and also updated it to 1.5 just to see if the update was really the problem and voila! The starters weren't randomized again.

TL;DR: Starter randomizer doesn't work on version 1.5 of Pokémon X/Y

**Comment by kwsch** [comment]
"didn't work" is too vague.

Game patches override the content in the ROM. You have to edit the patch files instead, or play without patches.
