### ISSUE TITLE
Pokémon Ultra Sun/ Moon not yet fully implemented

### ISSUE THREAD

**Issue by codpowerpat** [kwsch/pk3DS#465]
The trainer, wild pokemons + static encounters seem to not be implemented

**Comment by kwsch** [comment]
They're implemented.

Load a valid dumped ROM and the buttons can be used.

**Comment by codpowerpat** [comment]
I have a bug only with trainer, wild pokemons and static encounters. They doesnt work, and the first one of the first screen work( evolutions + personal stats)

**Comment by kwsch** [comment]
Remove any installed patches and ensure you're copying all required files.

This functionality works fine; the game cannot load data which it does not have available to load. In other words, the game doesn't fall back to the original data, it only uses the patch content.

**Comment by codpowerpat** [comment]
Okay i will check, the game works well on citra, but it seem that these functionalities don't work well with what i did setup.
