### ISSUE TITLE
Getting this issue when loading up PK3DS version 4.0.2

### ISSUE THREAD

**Issue by RevanXVIV** [kwsch/pk3DS#469]
So whenever I open up PK3DS I keep getting this message and it closes itself: Exception Details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at pk3DS.Core.GameConfig.InitializePersonal()
   at pk3DS.Core.GameConfig.InitializeAll()
   at pk3DS.Main.openQuick(String path) in C:\BuildAgent\work\ccf72a59f9911202\pk3DS\Main.cs:line 226
   at pk3DS.Main..ctor() in C:\BuildAgent\work\ccf72a59f9911202\pk3DS\Main.cs:line 51
   at pk3DS.Program.Main() in C:\BuildAgent\work\ccf72a59f9911202\pk3DS\Program.cs:line 29

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

pk3DS, Version=1.0.0.402, Culture=neutral, PublicKeyToken=null
C:\Users\nickm\Desktop\Everything\PK3DS\pk3DS.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

pk3DS.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\nickm\Desktop\Everything\PK3DS\pk3DS.Core.dll

--------------------
User Message:
An unhandled exception has occurred.
The program must now close.

It worked fine a few days ago, do I need to update something?

**Comment by zmarotrix** [comment]
I'm getting a similar issues. It seems any time it tries to create a new thread (by opening one of the sub menus), I get a null pointer exception. Here's after I clicked "Wild Encounters"

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=pk3DS
  StackTrace:
   at pk3DS.Main.<B_Wild_Click>b__40_0() in F:\GitHub\pk3DS\pk3DS\Main.cs:line 707
```
From commit: https://github.com/kwsch/pk3DS/commit/927830bf1125125e85b36f03d416a32e3175b4b6


Tested on these commits;
https://github.com/kwsch/pk3DS/commit/28347df8eabe0225b17f30060c13e40a0f35558c
https://github.com/kwsch/pk3DS/commit/82af1d63aa339323a2d7cb8f2dfade78c82dffde

**Comment by kwsch** [comment]
Bad ROM dump. Restore backups?
