### ISSUE TITLE
Repacking gives smaller size in sun/moon

### ISSUE THREAD

**Issue by MrShawnTRods** [kwsch/pk3DS#47]
Repacking most things after editing gives smaller size. Repacking the game after editing gives around 7mb smaller than untouched repack. Causes game to not load.
Cia installs fine but the game doesn't load.

**Comment by Draydrew** [comment]
I think I've also experienced this problem, if I, using .Net 3DS Toolkit:

- Extract a decrypted version that works on Citra
- Edit anything with PK3DS
- Build it again

Citra is unable to open the ROM and just fails with an editor. But there's no problem if I rebuild without any changes.

**Comment by MrShawnTRods** [comment]
Close this issue please.

Looks like every method of repacking edited cia causes the cia size to be wrong. Nothing wrong with pk3ds.
