### ISSUE TITLE
Latest commit causing crashes after randomizing encdata

### ISSUE THREAD

**Issue by sora10pls** [kwsch/pk3DS#48]
Used to work totally fine as of commit 02a8ed0, but after updating to latest commit I constantly get crashes when setting encdata. I've tried both Sun and Moon, using completely fresh and unedited GARCs from my own personal dumps (/a/0/8/2 in Sun, /a/0/8/3 in Moon), but to no avail.

![image](https://cloud.githubusercontent.com/assets/17801814/20868283/f1b94e02-ba25-11e6-91f0-356132acc31e.png)

**Comment by kwsch** [comment]
Tried debugging? Not experiencing that.

**Comment by sora10pls** [comment]
Huh, apparently compiling source code myself resolved the issue. I had previously gotten the latest commit from TeamCity, same place where automatic builds of PKHeX are put, and that didn't work for whatever reason. Sorry to disturb :)
