### ISSUE TITLE
Add support to Demo versions + Pokémon Bank

### ISSUE THREAD

**Issue by Hareon** [kwsch/pk3DS#481]
Hi! You made an excellent work in this tool. I'm here to ask for support for the Demo versions of the Pokémon ORAS and SM.
Pokémon Bank is a good option to add as support too.

**Comment by kwsch** [comment]
The program already supports `ORASDEMO` and `SMDEMO` dumps.

Bank is not a playable game.

**Comment by Hareon** [comment]
![Capturar](https://user-images.githubusercontent.com/54816136/110160427-c9f3dc80-7dca-11eb-9f99-8dd4889d6d61.JPG)
I don't know why, but it gives error when I try to lauch the ORAS demo. It's decrypted extracted file.

**Comment by kwsch** [comment]
The program throws that error when it fails to load files.

https://github.com/kwsch/pk3DS/blob/754b9b8d95ada3a67989c42e5713ad90060d343f/pk3DS.Core/Game/GARCReference.cs#L75

The program is looking inside `a/1/9/5`'s garc for the personal data.

**Comment by Hareon** [comment]
Ok, I'll try another rom to solve the problem. Thanks!!!
