### ISSUE TITLE
Trying to edit trainers causes a crash

### ISSUE THREAD

**Issue by Chinch-Bug** [kwsch/pk3DS#483]
I'm not sure whether something is wrong with 3DS toolkit, which I use to extract files, or pk3DS, but I've used both to create randomized games and such before with no issue, but recently when I tried to edit roms (ultra sun & ultra moon btw), trying to access the trainers tab gives me this error:

Since recompiled roms also seem to not work anymore, it might be the 3DS toolkit's issue?

> Exception Details:

> System.FormatException: Invalid GARC Version: 0x0000
>    at pk3DS.Core.CTR.GARC.UnpackGARC(Stream stream)
>    at pk3DS.Core.CTR.GARC.UnpackGARC(Byte[] data)
>    at pk3DS.Core.GameConfig.GetMemGARC(String file)
>    at pk3DS.Core.GameConfig.GetGARCByReference(GARCReference gr)
>    at pk3DS.Main.<B_Trainer_Click>b__39_0() in D:\a\1\s\pk3DS\Main.cs:line 681
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()
> 
> Loaded Assemblies:
> --------------------
> mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
> C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll
> 
> pk3DS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
> D:\pk3ds2\pk3DS.exe
> 
> System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
> C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
> 
> System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
> C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll
> 
> System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
> 
> System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
> C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
> 
> System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll
> 
> System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
> C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
> 
> pk3DS.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
> D:\pk3ds2\pk3DS.Core.dll
> 
> --------------------
> User Message:
> An unhandled exception has occurred.
> The program must now close.

**Comment by kwsch** [comment]
https://github.com/kwsch/pk3DS/issues/320#issuecomment-381412057
