### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by CrimsonSoldier** [kwsch/pk3DS#484]
I´m sorry I´m that ignorant, but I just don´t understand what to do to install  the program. Once I´ve downloaded the file of Pk3ds master, what do i do to open it? 
Thank you:)

**Comment by kwsch** [comment]
As linked in the repository's About details:

> https://projectpokemon.org/home/forums/topic/34377-pk3ds-xy-oras-rom-editor-and-randomizer/
