### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by CrimsonSoldier** [kwsch/pk3DS#485]
Once I complete the randomization and open the game in Citra, it crashes. I´ve tried with the unchanged game and it works.
I´m not really sure whether the problem is in Hacking Toolkit or Pk3ds, si if anyone knows what´s happening or has had the same problem; please tell me...

**Comment by kwsch** [comment]
Not an issue with pk3DS. This isn't the place to troubleshoot loading edited game files in an emulator.
