### ISSUE TITLE
issue with sun and moon item editing, the flag to change an items battle bag doesnt work

### ISSUE THREAD

**Issue by avividrose** [kwsch/pk3DS#487]
I'm trying to move healing items out of the battle bag, but for some reason the game ignores when i change that flag. it insists on being available in the battle bag. 

also, i noticed that for every item, the revive flag is locked to true, except for revives, where it is defaulted to false but seems to be changeable.

**Comment by kwsch** [comment]
Pretty sure there's another field item definition file that determines which pouch something appears in, which is not defined in the item stats.

**Comment by avividrose** [comment]
thanks for the reply! 
is that other field item definition file just a separate GARC that i should be overriding? or is it another edit i need to make in pk3ds?

**Comment by kwsch** [comment]
I don't think pk3DS edits that, so you'll have to figure it out yourself.

**Comment by avividrose** [comment]
im a bit confused, what do you mean by it doesnt edit that? there is a field in the item stat editor to edit its bag placement. does that flag not actually edit any garc files?
