### ISSUE TITLE
How to update a randomized game?

### ISSUE THREAD

**Issue by FerdinandoPH** [kwsch/pk3DS#491]
I want to update my pokemon y randomized rom. How can I do it without losing the randomization?

**Comment by kwsch** [comment]
Unrelated to this program.

Unpack the ROM as you normally would, then use the program.

**Comment by FerdinandoPH** [comment]
The thing is, updates are distributed as separate cias, and when installing them some features from the randomization are gone. There is an option to load the update in another randomizer, so I was wondering how to do it with this one

**Comment by kwsch** [comment]
The 3DS game updates aren't really that important to keep installed, but if you must, you can always merge the patch romfs into the base ROMFS and cherry pick the edited files. pk3DS supports editing patched exefs content too, just replace the exefs with the patch one.
