### ISSUE TITLE
Please help I've worked on it for a while and don't want it to go to waste  

### ISSUE THREAD

**Issue by Meep02** [kwsch/pk3DS#492]
Exception Details:
System.FormatException: Invalid GARC Version: 0x0000
   at pk3DS.Core.CTR.GARC.UnpackGARC(Stream stream)
   at pk3DS.Core.CTR.GARC.UnpackGARC(Byte[] data)
   at pk3DS.Core.GameConfig.GetMemGARC(String file)
   at pk3DS.Core.GameConfig.GetGARCByReference(GARCReference gr)
   at pk3DS.Core.GameConfig.InitializeGameText()
   at pk3DS.Core.GameConfig.InitializeAll()
   at pk3DS.Main.OpenQuick(String path) in D:\a\1\s\pk3DS\Main.cs:line 231
   at pk3DS.Main..ctor() in D:\a\1\s\pk3DS\Main.cs:line 55
   at pk3DS.Program.Main() in D:\a\1\s\pk3DS\Program.cs:line 32

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

pk3DS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
D:\Downloads\pk3DS (1)\pk3DS\pk3DS.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

pk3DS.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
D:\Downloads\pk3DS (1)\pk3DS\pk3DS.Core.dll

--------------------
User Message:
An unhandled exception has occurred.
The program must now close.

**Comment by kwsch** [comment]
https://github.com/kwsch/pk3DS/search?q=Invalid+GARC+Version%3A+0x0000&type=issues

Try searching. Bad ROM dump is bad.

**Comment by Meep02** [comment]
I searched Bad ROM dump is bad but I still don't understand do i have extract the game again or what i need more than Try searching. Bad ROM dump is bad. sorry if i sound rude I've been working on it for months and it randomly stopped working

**Comment by kwsch** [comment]
> do i have extract the game again

potentially, assuming that restoring backup data does not work.

The program is sanity checking the ROM data. Bad data = not going to be able to be loaded, hence the error. Not sure *how* your data became bad, but it's not because of pk3DS.

**Comment by Meep02** [comment]
how do i restore a back up?

**Comment by kwsch** [comment]
Options -> about garcs
pk3DS's folder stores a backup of all modified garcs

**Comment by Meep02** [comment]
i cant even open the app
