### ISSUE TITLE
Unable to Open

### ISSUE THREAD

**Issue by Lugnut1116** [kwsch/pk3DS#493]
I just did a fresh download of pk3ds and when i attempt to open the program itself I am greeted with this.

Exception Details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at pk3DS.Core.GameConfig.InitializePersonal()
   at pk3DS.Core.GameConfig.InitializeAll()
   at pk3DS.Main.OpenQuick(String path) in D:\a\1\s\pk3DS\Main.cs:line 230
   at pk3DS.Main..ctor() in D:\a\1\s\pk3DS\Main.cs:line 51
   at pk3DS.Program.Main() in D:\a\1\s\pk3DS\Program.cs:line 32

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

pk3DS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
D:\Pokemon Randomizers 6+\pk3DS\pk3DS.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

pk3DS.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
D:\Pokemon Randomizers 6+\pk3DS\pk3DS.Core.dll

--------------------
User Message:
An unhandled exception has occurred.
The program must now close.

**Comment by kwsch** [comment]
> I just did a fresh download of pk3ds and when i attempt to open the program itself I am greeted with this.

pk3DS remembers the last open path even if you try using an updated version. It's trying to load the saved path, and the data in the folder is no longer a valid ROM dump.

**Comment by Lugnut1116** [comment]
Well then I'm confused, because i was using it on minute and it crashed then started saying this so i tried replacing the rom and it didnt fix it.

**Comment by Lugnut1116** [comment]
Nvm fixed
