### ISSUE TITLE
pokemon 3ds randomizer

### ISSUE THREAD

**Issue by scEdom79** [kwsch/pk3DS#494]
hi, i need help, i hacked my 3ds to lunch .cia games, i randomized with pk3ds pokemon omega ruby european version, but when i get my starter the randomize don't work, so i tryed on citra with a decrypter so i could get the .cci version of the file and on citra it works can someone help me

**Comment by kwsch** [comment]
The program works; this is not the place to get help with why your console is not loading the modified data.

**Comment by scEdom79** [comment]
> The program works; this is not the place to get help with why your console is not loading the modified data.

The you tell me where should i ask this question because if use a thing the should explain how use it instead of uploading it and then you need to see a tutorial that only works for an emulator

**Comment by kwsch** [comment]
This issue tracker is for reporting faults with this program, or discussing features.

Not for "how do I use the results from this program correctly".

There are many tutorials on the internet, and there are forums where you can request help. Not here.
