### ISSUE TITLE
I am currently trying to make a pokemon romhack for pokemon Y and yet again this error appeared i was nearly finished but this error came up any fix for this 

### ISSUE THREAD

**Issue by wardy555** [kwsch/pk3DS#497]
Exception Details:
System.FormatException: Invalid GARC Version: 0x0000
   at pk3DS.Core.CTR.GARC.unpackGARC(Stream stream)
   at pk3DS.Core.CTR.GARC.unpackGARC(Byte[] data)
   at pk3DS.Core.GameConfig.GetGARCByReference(GARCReference gr)
   at pk3DS.Core.GameConfig.InitializeAll()
   at pk3DS.Main.openQuick(String path) in D:\a\1\s\pk3DS\Main.cs:line 227
   at pk3DS.Main..ctor() in D:\a\1\s\pk3DS\Main.cs:line 55
   at pk3DS.Program.Main() in D:\a\1\s\pk3DS\Program.cs:line 29

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

pk3DS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\connor\Desktop\drop\pk3DS\bin\Release\pk3DS.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

pk3DS.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\connor\Desktop\drop\pk3DS\bin\Release\pk3DS.Core.dll

--------------------
User Message:
An unhandled exception has occurred.
The program must now close.

**Comment by kwsch** [comment]
Bad ROM dump, the GARC file it is trying to read is not valid, hence the error.

**Comment by wardy555** [comment]
It can't be a bad dump because I have already been playing the rom I was just added few more things to it

**Comment by kwsch** [comment]
Well, then you corrupted your ROM dump somehow as the data for one of the GARCs is no longer valid.

I've pushed a new commit to help indicate the problematic file. I'm not sure if this is caused by closing the program before it is done saving the data.
