### ISSUE TITLE
Pk3ds 

### ISSUE THREAD

**Issue by wardy555** [kwsch/pk3DS#498]
With pk3ds I am trying to do mulitply level for trainer Pokémon I either get only one trainer getting leveled up or all trainers either level 1 or 99

**Comment by kwsch** [comment]
Don't randomize multiple times with the level amplifier set.

**Comment by wardy555** [comment]
So what would be the best multiplier because 1.05 only did one stage??

**Comment by kwsch** [comment]
Randomizing with 1.05 increases all levels by 5%.

Randomizing again with the same will increase all levels by 5% again.

Randomizing again with the same will increase all levels by 5% again.

Randomizing again with the same will increase all levels by 5% again.

Randomizing again with the same will increase all levels by 5% again.
