### ISSUE TITLE
PK3ds

### ISSUE THREAD

**Issue by wardy555** [kwsch/pk3DS#499]
![IMG_20210906_203653](https://user-images.githubusercontent.com/79413433/132256325-c56a373c-a474-4ba8-bc29-fafa11648f02.jpg)
Whats the issue???

**Comment by kwsch** [comment]
Bad dump, it wasn't able to find the required GARC.

**Comment by wardy555** [comment]
What causes a bad rom dump??

**Comment by kwsch** [comment]
Dumping the ROM incorrectly, or manually messing with ROM files inside the ROM dump.

This isn't an issue with pk3DS; all it is saying is that the data it is trying to read is incorrect / missing.
