### ISSUE TITLE
Pokemon Omega Ruby

### ISSUE THREAD

**Issue by OMNIVader23** [kwsch/pk3DS#504]
Keeps crashing when entering the first Pokemon Center (As male and Female) On Pokemon Omega Ruby, Confirmed this is an issue after randomizing, as Original rom works just fine 
![Screenshot 2021-09-26 165505](https://user-images.githubusercontent.com/91316115/134815573-5c5273d8-f1dd-48af-a7c4-06908224f020.png)
![Screenshot 2021-09-26 171710](https://user-images.githubusercontent.com/91316115/134815694-884cc53a-3388-444d-88ac-f5bc0722df09.png)

**Comment by OMNIVader23** [comment]
Issue seems to be that the textures for inside the pokemon center have vanished, just tested loading the unedited rom and entering the center, entered fine, saved inside the Center then reloaded the Randomized rom. and now just a black screen

**Comment by kwsch** [comment]
There's no support for emulated games here. You're likely mixing and matching files incorrectly; randomizing wild species etc do not cause issues in a Pokemon Center.
