### ISSUE TITLE
Personal Stats editor

### ISSUE THREAD

**Issue by Kobazco** [kwsch/pk3DS#51]
Hey, everything works just great in the Personal Stats editor except for 2 things:

1. When changing an ability, it does not save.
2. When changing a type, it does not save either.

**Comment by kwsch** [comment]
It's just standard combobox behavior, just typing in text doesn't change the index/value.

**Comment by Rashock** [comment]
For me it's not saving any change, not even the Quick Hatch, any idea?

Thank you very much for the great tool

**Comment by Draydrew** [comment]
It seems like the SelectedIndex stays at the original value when you swap tabs for any of the combo boxes. Not sure why though.

**Comment by Draydrew** [comment]
It seems like no combo box changes will save when you move onto another Pokémon, but the text boxes like the base stats are fine.

**Comment by Draydrew** [comment]
I haven't been able to solve this issue but I'm mistaken on the combo box thing - it seems that anything trying to save to an array element doesn't actually work. The Base EXP and Color combo boxes work with no issues, I'm not sure what else the bugged elements have in common.

Items, typings, abilities and egg groups all fail to save and they're all meant to set array elements.
