### ISSUE TITLE
Pokemon X Wild Encounter are not active in game

### ISSUE THREAD

**Issue by LakshmisKshatriya** [kwsch/pk3DS#510]
When I edit the Wild Encounters the canges I've made do not show up in game any other change for example about Trainers **do** show up. Its just the usual PKMN Encounters. But when I open the game data the changes I've made are still there. Also I tried various ways but I just cant progress. Can anyone help me?

**Comment by kwsch** [comment]
Be sure you're copying the edited encounter data garc so the game reads it. The game can't read old data if new data is overriding it, and new data won't have the old data, because it was overwritten.

**Comment by LakshmisKshatriya** [comment]
Hi, thanks for your quick answer, sadly I didn't quite get it and am a bit confused. What steps do i have to take exactly? Thank you again!

**Comment by kwsch** [comment]
Remove any installed game patches by deleting them
Double check all the files got copied with the correct path and file name

**Comment by LakshmisKshatriya** [comment]
If I deinstall the game patch 1.5 and launch the game the game crashes.![20211113_170856.jpg](https://user-images.githubusercontent.com/93215080/141650845-1092eb9e-6c1a-420d-b4b2-41738153a586.jpg)

**Comment by LakshmisKshatriya** [comment]
Problem solved you are a hero btw!
