### ISSUE TITLE
Cannot seem to get this running in linux,

### ISSUE THREAD

**Issue by FrostKnight** [kwsch/pk3DS#512]
Is it possible you can make some premade builds of this that only require wine to run?

I am itching to see how this works, but the msbuild line screws it up...

Or make it so that it only needs mono-complete to work, one or the other would be lovely.

mkdir -p tmp
TMPDIR=~/youruser/pk3DS-master/tmp msbuild /p:Configuration=Release pk3DS.sln
/bin/sh: 1: msbuild: not found
make: *** [Makefile:16: pk3DS/bin/Release/pk3DS.exe] Error 127

Side note,  kind of puzzled as to what is actually required to build it anyhow...

**Comment by kwsch** [comment]
Builds are published via Azure Pipelines; follow the green checkmarks for a given commit to download the artifact zip containing the built exe

**Comment by FrostKnight** [comment]
My bad, I found it by going to the forums and downloading it there, as for the artifact zip, couldn't figure out how to, but its solved nonetheless so no worries.

I wonder what works in this build to be honest though... :)
