### ISSUE TITLE
Strange problem with level up moves 

### ISSUE THREAD

**Issue by wardy555** [kwsch/pk3DS#519]
So I finally managed to complete my Pokémon X rom Hack yesterday I was extremely happy but level up moves on my Pokémon aren't in the full game so for example I gave my ledian drain punch at level one but he doesn't have it when I tried to learn it to him any particular reason this could be caused by??

**Comment by kwsch** [comment]
Remove any installed game patches, and ensure that all modded files were loaded correctly.
