### ISSUE TITLE
File doesn't match count

### ISSUE THREAD

**Issue by linkus14** [kwsch/pk3DS#523]
I am trying to randomize a team subbit rom hack using pokemon Y. I use their provided .3ds file extractor and follow the steps i have for years but for some reason i keep getting a " file count does not match expected game count" "files:4" 

Please if anyone could help. I'm very pc iliterate so i apologize if i ask more than once what you meant.

Thank you all in advance.

**Comment by kwsch** [comment]
Dump the entire romfs. The game has more than 4 files when it is unpacked.

**Comment by kwsch** [comment]
> Im sorry but how do you do this?

Read a guide on how to dump the files. Having the files correctly dumped is a prerequisite to use the program, and is outside the scope of this repo/issue tracker.
