### ISSUE TITLE
Everything is repeating 

### ISSUE THREAD

**Issue by Spas120** [kwsch/pk3DS#529]
When ever I randomize Pokemon moon it always has the same starters and the trainers always have the same pokemon from the last time I randomized the game so I need help fixing this

**Comment by kwsch** [comment]
Revert to the original data, randomize, then copy the modified files to your 3DS.

**Comment by Spas120** [comment]
I'm not sure how to do that

**Comment by kwsch** [comment]
Dump your ROM again with your 3DS, and delete the layeredfs copy that had the modified files. Files don't magically revert to their old modified state when you replace them.
