### ISSUE TITLE
S/M starter randomization question/suggestion

### ISSUE THREAD

**Issue by sora10pls** [kwsch/pk3DS#53]
I've tested out the latest commit and the starter randomizer works great. Only downside to it is that when you actually go to pick your starter, none of the models or names change in accordance to what was randomized. This makes choosing the starters a guessing game and isn't exactly the most ideal way to differentiate them without having to go back into pk3DS to check.

For my question, I was wondering if it were possible to change the models shown in the cutscene to match those of the randomized starters? (I feel this will be the less likely of the two)

And for my suggestion, what I feel would be the more likely scenario: I was curious to see if it would be possible that after the starters get randomized, pk3DS would also change the story text to match that of the first Type and name of the Pokemon of the randomized starters?

For reference, the following text is located under Story Text (Text File 41, Lines 1-3)

![image](https://cloud.githubusercontent.com/assets/17801814/20898838/e37a6148-baf5-11e6-8706-b2cd2d999cfd.png)

So for example... the original starters are shown off as this in the games:
The Grass-type Rowlet
The Fire-type Litten
The Water-type Popplio

If Rowlet became Shinx, if Litten became Umbreon, and Popplio became Mudsdale, the text would change to:
The Electric-type Shinx
The Dark-type Umbreon
The Ground-type Mudsdale

I understand that this could be tedious (or even impossible to do, that I'm not so sure of), but it's worth a shot asking :)

**Comment by kwsch** [comment]
Sure it's possible, but how would pk3DS handle setting the text if a language other than English were selected? A string replace using species name and type name would probably do the trick (not sure about JP/ZH languages tho).

I'd think the game displays models based off of the event scripting (or a CRO if there is a variant of Starter3Poke this gen). 

Past gen starter modifying updated the gift table CRO; however in Gen7 nobody knows how the game determines what pokemon is shown in the cutscene.

**Comment by sora10pls** [comment]
I checked all languages and they're all located in the same spot, Story Text/Text File 41/Lines 1-3. Perhaps have pk3DS quickly cycle through all of the possible languages and modify the Types and names accordingly? I'm aware there could be small discrepancies between different languages (like JP/ZH languages as you mentioned), but that could be fixed with the help of translators.

Model swaps are just icing on the cake, I wouldn't think that they're entirely necessary right away, as long as there's at least **some** way to tell what each of the starters are. And like you said again, nobody knows how the game handles the models shown in the cutscenes
