### ISSUE TITLE
Pokemon X and Y not randomizing

### ISSUE THREAD

**Issue by sealguy180** [kwsch/pk3DS#530]
each time i randomize pokemon x and y the starters and wild pokemon arent random and idk how to fix it

**Comment by kwsch** [comment]
Copy your files correctly to your 3DS's SD card so that they're loaded by your custom firmware instead of the base game files.

**Comment by sealguy180** [comment]
well i usually just extract the game, edit it, rebuild it as a cia file and then download it on the 3ds with FBI unless thats what you mean

**Comment by kwsch** [comment]
Files do not magically un-randomize. The data either is used, or something else is using the data (like an installed patch). It doesn't magically revert to something that isn't there.

**Comment by sealguy180** [comment]
what are you talking about
