### ISSUE TITLE
Possible PK3DS Issues with ORAS

### ISSUE THREAD

**Issue by RuinousPrincess** [kwsch/pk3DS#531]
I've managed to successfully change types and stats, randomize Pokémon, but upon pressing A on the title screen results in a black screen. So, if I save and quit then go try loading the game on the title screen it's just black. I'm not sure if it's just the possible dump of the games causing bugs, Citra or maybe PK3DS is causing issues. I can't for some reason get back into game once quitting unless I remove the files from PK3DS out of the mod folder. Unless ORAS isn't supported by PK3DS. I can randomize other games easily and load save files, but ORAS for some reason is the only ones causing issues for me with PK3DS.

**Comment by kwsch** [comment]
Not an issue with pk3DS.

Test with your console. You're probably crashing because of modified CRO files which the console is sanity checking. Needs the firmware patch to ignore a bad sign. Unrelated to pk3DS.

**Comment by RuinousPrincess** [comment]
I been doing it through Citra by having it dump files from the Rom, not a real console. Probably also just the rom being bad, but thanks for letting me know. I'll see if I can find anything to fix things on my end.
