### ISSUE TITLE
Some Pokémon forms missing at Personal Information

### ISSUE THREAD

**Issue by EliteFourRafa** [kwsch/pk3DS#533]
I'm editing an Ultra Sun Rom and I can say this tool is really good and is making my work easier. But for some reason when I try to edit the Personal Information the forms of Flabébé, Florges, Vivillon, Deerling and Sawsbuck aren't available to edit. I can choose them when I edit the Wild Encounters but I can't find them to edit the Personal Information (for the Deerling and Vivillon lines this is very important because I want to give their forms different typings). 

Could somebody help me please? 

Thanks in advance!

**Comment by kwsch** [comment]
Cosmetic forms don't have different stats, thus they don't have separate personal info data.
