### ISSUE TITLE
Can't browse any folder

### ISSUE THREAD

**Issue by Dalk2ness** [kwsch/pk3DS#534]
Can't browse any folder on windows 11 22h2
![image](https://user-images.githubusercontent.com/10178164/210169805-c5e375c8-df4f-4942-8695-1b38150be436.png)

**Comment by kwsch** [comment]
Likely culprit is OneDrive desktop folder sync:

https://answers.microsoft.com/en-us/windows/forum/all/windows-11-browse-for-folder-dialog-issue-only/0a0ce0a5-0a72-4483-a51e-1b3ee9dffcdb

**Comment by Dalk2ness** [comment]
> Likely culprit is OneDrive desktop folder sync:
> 
> https://answers.microsoft.com/en-us/windows/forum/all/windows-11-browse-for-folder-dialog-issue-only/0a0ce0a5-0a72-4483-a51e-1b3ee9dffcdb

Thank u so much sir ^^
it's very helpful
