### ISSUE TITLE
Move editing complications

### ISSUE THREAD

**Issue by GOATSTAPPEN** [kwsch/pk3DS#535]
Hello! I have looked for days on end about this issue, but never really found a solution. Farthest I've gotten is finding other people who share my problem. 

I am trying to replace the move "Hold Hands" with a custom move, kind of like Flip Turn.

I changed the name (I'm pretty sure) on all the text files that mention helping hand, and also set the effect number (which I am assuming is the animation) the same as U-Turn, (228). 

Yet, it still is named "Hold Hands" and has the same animation as original. Typing changed, and power did change, but the name, animation, nor description text change.

Am I editing the wrong move? What could be the problem? If there was a past issue that covered this please let me know, as I couldn't find it after looking at every issue that mentioned the key term "move."

**Comment by kwsch** [comment]
Dump the entire game text to see where else the text needs updating.

Move animation sequences are stored separately, and aren't documented.

Be sure to remove any installed patches that may be overwriting your base ROM changes.

**Comment by GOATSTAPPEN** [comment]
Ok, here it is. The only patch I have installed is update 1.2 for Ultra Sun, is that problematic?
[gamtext.txt](https://github.com/kwsch/pk3DS/files/10501851/gamtext.txt)

**Comment by kwsch** [comment]
Re-read my last sentence.

This isn't an issue with pk3DS.

**Comment by GOATSTAPPEN** [comment]
Oh okay, my bad. There were a few lines of text that still had Hold Hands. So for changing move animations, i.e making Hold Hands have U turn animation, is that just not possible? Or is pk3DS not the software I should be looking at for this.
