### ISSUE TITLE
Unable to run pk3ds

### ISSUE THREAD

**Issue by Apall-Low** [kwsch/pk3DS#554]
I tried to download the most recent version of pk3ds, but the folder doesn't contain the actual executable to run the program. I followed the download instructions on the projectpokemon post, but it seems like the file it's telling me to download is the wrong one, and I can't find the right version anywhere.
![image](https://github.com/user-attachments/assets/ced70ff3-244d-4844-8faf-035b958218ca)

**Comment by kwsch** [comment]
pk3DS needs .NET 8 Desktop Runtime, which is what the popup message will link you to.

**Comment by Apall-Low** [comment]
Thanks for responding so quickly, I really appreciate it. Since my previous version simply had a file named pk3ds.exe and ran without a problem, I assumed the file served a different purpose.
