### ISSUE TITLE
Personal Stats editor abilities

### ISSUE THREAD

**Issue by Kobazco** [kwsch/pk3DS#56]
Hey, thanks for your fix on the personal stats editor. Changing the types of Pokemon seem to work now, but abilities do not. They still reset sadly.

**Comment by Draydrew** [comment]
To add onto this it looks like whatever item is in the 50% slot for a Pokémon (whether there is an item there or not) also gets applied to the 5% and 1% slots. Egg groups and types are saving correctly though.

**Comment by Draydrew** [comment]
Made a pull request https://github.com/kwsch/pk3DS/pull/57 to fix these.
