### ISSUE TITLE
Rebuild Rom Pokemon Sun/Moon

### ISSUE THREAD

**Issue by valten185** [kwsch/pk3DS#63]
I modified my rom S/M with pk3ds but now I want to know how rebuild my rom and if i can use this rom with gateway (o3ds 4.2).

thanks

**Comment by kwsch** [comment]
Unrelated to pk3DS; you can try the Tools->Rebuild->3DS, if not, use one of the many public rebuilding tools that can be found on gbatemp or elsewhere.
