### ISSUE TITLE
pk3DS cannot open error

### ISSUE THREAD

**Issue by Pofuego** [kwsch/pk3DS#67]
whenever I try to open it this pops up

    Cannot execute "C:\Users\clayton\AppData\Local\Temp\Rar$EXa0.243\pk3DS.exe"

  
![capture](https://cloud.githubusercontent.com/assets/24513176/21084061/e90e77fa-bfb1-11e6-996f-36a0cedada76.PNG)

**Comment by kwsch** [comment]
Extract the .exe from the zip file.

**Comment by Pofuego** [comment]
Now this happens
![capture](https://cloud.githubusercontent.com/assets/24513176/21084195/7c89ea58-bfb4-11e6-8cbf-bb56e79dbbff.PNG)

**Comment by kwsch** [comment]
You need a 64bit operating system to run the latest version of pk3DS due to the excessive RAM needs.

The program will eventually be reworked to be less memory intensive; the latest version is stuck as 64bit-only for the time being.
