### ISSUE TITLE
Feature request: option to only randomize Special Marts

### ISSUE THREAD

**Issue by sora10pls** [kwsch/pk3DS#68]
Currently, the Mart Randomizer randomizes **all** Poke Mart inventories, making it hard to obtain "the necessities" for normal gameplay (Medicine, Poke Balls, Repels, etc.).

It would be a nice addition if there was the option to only randomize Special Mart inventories, like the right Poke Mart clerks, for example.

**Comment by MrShawnTRods** [comment]
Yes please
