### ISSUE TITLE
TM/HM not being restored to the original

### ISSUE THREAD

**Issue by egzonqj** [kwsch/pk3DS#69]
So well, I was "playing" a little bit with pk3DS on Sun and after randomizing all I wanted to go back to the original data, but the TMs were still randomized.

I guess this is a bug or it does not backup ExeFS, or... I don't know. Just wanted to notify :P

**Comment by kwsch** [comment]
Restore original files is only for GARCs (and CRO), manually replacing the exefs is a simple task for the user to do.

Pending refactor for separate game backup folders #31, this issue should be addressed at the same time.
