### ISSUE TITLE
Personal Stats Editor does not save changes in Move Tutors tab

### ISSUE THREAD

**Issue by ApacheThunder** [kwsch/pk3DS#71]
This seems to impact only Pokémon Sun/Moon and the TMs/Move tutors. It does save changes to the new Z-Move settings, but changes to TMs/Move Tutors is lost once the Personal dialog is closed and reopened. It seems to never save them as I did not see the changes applied ingame. The new z-move settings seem to save however.

**Comment by ApacheThunder** [comment]
Unfortunately it looks like this didn't correct the issue. (refer to my comment on the commit specified for the details)

**Comment by kwsch** [comment]
https://github.com/kwsch/pk3DS/commit/c979c8b4aeb774e8500509369e10d7c8e0714243 adds the missing set behavior for the bools.
