### ISSUE TITLE
Problem with pk3ds

### ISSUE THREAD

**Issue by valten185** [kwsch/pk3DS#72]
I have a problem with pk3ds ; in effect, i modified my rom(pokemon sun) with pk3ds and i rebuilt. But when i start this game et i have a black screen after the logo. I tried with a rom not modified and it works. So maybe there is a problem with pk3ds....?

**Comment by sora10pls** [comment]
Not a problem with pk3DS, this has already been reported before. Your method of repacking is what's the problem.

Reference:
#44
#47
#63
#65
