### ISSUE TITLE
The file crash after Wild Encounter randomization

### ISSUE THREAD

**Issue by KamNationPLS** [kwsch/pk3DS#75]
Hi the file .exe that I found crash at Wild Encounter. 

How can I have the latest .exe file X32 ? I don't have any idea how to create the .exe since the code source. 

Can someone please help me ? (sorry for my bad english)

**Comment by kwsch** [comment]
>.exe that I found

Recompile from source. 64bit is required for now as repacking wild encounters needs more than 2GB of RAM.
