### ISSUE TITLE
Concerns regarding Trainer Editor 7

### ISSUE THREAD

**Issue by sora10pls** [kwsch/pk3DS#77]
As I mentioned in a previous issue, I recently finished up a Sun randomizer nuzlocke. Later in the game, I noticed that a lot of the Trainer Pokemon's movesets were pretty pathetic. A Level 64 Serperior used... Tackle? Surely that isn't intended to happen because it's so early in the Pokemon's levelup moveset, and this definitely was not the case with Gen 6.

When randomizing Trainer Pokemon, I set moves to `Use Levelup Only`. While this works for the early game, it severely drops in difficulty in the later game (as I mentioned before with the Serperior example). I then decided to test and see what would happen if I set the moves to `High Powered Attacks`, only to realize that Pokemon had extremely insane movesets in the early game, such as a Munchlax already having Giga Impact at Level 5.

What do I think the problem is? When setting a Pokemon to have its levelup moves only, pk3DS only looks for the VERY beginning of the Pokemon's levelup moveset and uses whatever 4 moves it can find. What makes me believe this is the following example (yet again, it's that Serperior I mentioned):

Serperior's levelup moves (take note of the first 4)
![image](https://cloud.githubusercontent.com/assets/17801814/21487094/4050dd76-cb8f-11e6-8e6b-bbefa1347787.png)

Serperior's moves when set to `Use Levelup Only`
![image](https://cloud.githubusercontent.com/assets/17801814/21487092/376a22c6-cb8f-11e6-84f2-45989f1015ec.png)

Notice that they are the EXACT same.

What I suggest is that pk3DS handles this like it did with Gen 6; take into consideration the Pokemon's current level, and modify the levelup moves accordingly.

So if Serperior were Level 5, it should have:
- Tackle
- Leer
- Vine Whip
- Wrap

And if Serperior were Level 40, it should have:
- Mega Drain
- Slam
- Leaf Blade
- Coil

Hope you understand where I'm coming from with all this!

**Comment by sora10pls** [comment]
Another few examples to prove that this is the case.

Thundurus' levelup moves
![image](https://cloud.githubusercontent.com/assets/17801814/21487114/e663d6fa-cb8f-11e6-8371-dbb201ea7b92.png)

Thundurus' moves when set to `Use Levelup Only`
![image](https://cloud.githubusercontent.com/assets/17801814/21487121/fa0047ac-cb8f-11e6-9c45-d5cbb62ed3d0.png)

Rayquaza's levelup moves
![image](https://cloud.githubusercontent.com/assets/17801814/21487129/1e34bd1a-cb90-11e6-8be0-d38317e9fe5c.png)

Rayquaza's moves when set to `Use Levelup Only`
![image](https://cloud.githubusercontent.com/assets/17801814/21487127/158cc1d0-cb90-11e6-85e1-8f21f7aedb81.png)

In all 3 examples shown (Serperior, Thundurus, Rayquaza), regardless of what Level they are, `Use Levelup Only` will ONLY use the first 4 moves in its levelup moveset (if the Pokemon has reached the required level for each move, that is).

**Comment by sora10pls** [comment]
Thank you very much!

**Comment by RalphMO** [comment]
Can you edit this with a .sav file?

**Comment by kwsch** [comment]
pk3DS is a ROM editor, not a save editor.
