### ISSUE TITLE
Trainer & Static Encounter crash

### ISSUE THREAD

**Issue by SwampyGator** [kwsch/pk3DS#78]
Hello. I am using the latest pk3ds to randomize Sun. Wild Encounter works fine, but everytime I try to enter Trainer or Static Encounter, the application crashes and exits. Is there a fix for this?

**Comment by kwsch** [comment]
Did you compile it yourself or did you find the exe somewhere?

**Comment by SwampyGator** [comment]
Downloaded the exe off of a video tutorial. Also had the same problem on a version compiled by me.

**Comment by kwsch** [comment]
Try using a clean dump, old versions may have saved the GARCs incorrectly which persists even when using the latest commits.

**Comment by SwampyGator** [comment]
So re dump game?

**Comment by kwsch** [comment]
Yes.

**Comment by SwampyGator** [comment]
K! I'll start braindump, and I'll let you know if it works. Thanks!

**Comment by SwampyGator** [comment]
Redumped, now it works! Thanks!

**Comment by SwampyGator** [comment]
Kinda on a side note whenever I try to load romfs and code from hans it just boots me back to homebrew.

**Comment by SwampyGator** [comment]
Edit: Needed the hax 2.8 hans
