### ISSUE TITLE
Rebuild RomFS/ExeFS for S/M

### ISSUE THREAD

**Issue by sora10pls** [kwsch/pk3DS#80]
When rebuilding RomFS/ExeFS binaries for S/M through pk3DS, if setting save type as a HANS RomFS or ExeFS, it does not automatically fill in Title IDs for the files like it does for X/Y/OR/AS.

Sun should be: `00164800.romfs` and `00164800.code`
Moon should be: `00175E00.romfs` and `00175E00.code`

**Comment by kwsch** [comment]
HANS game ID is fetched from the [SMDH CEC ID](https://3dbrew.org/wiki/SMDH#Application_Settings) and is not hard-coded.

How should pk3DS be fetching the ID if it resolves to 00000000?

**Comment by kwsch** [comment]
To be left to the user to manually enter.
