### ISSUE TITLE
Feature request: UI Picture modifier(Import/Export)

### ISSUE THREAD

**Issue by okt04175** [kwsch/pk3DS#82]
I want to modify the battle UI picture,please try to make this feature,thanks!

**Comment by kwsch** [comment]
too vague. no mention of which game, what exact battle ui (no example pic was provided).

you can do most modifications by editing the images yourself. Unpack the GARC with pk3DS, edit the images, then rebuild the GARC.

**Comment by okt04175** [comment]
I want to modify the battle UI button.
http://i.imgur.com/EsAoL8p.png
