### ISSUE TITLE
Pk3ds detects pokemon sun but doesn't allow to edit

### ISSUE THREAD

**Issue by renatosk** [kwsch/pk3DS#83]
First of all , i dont know if this is the right place to ask this , i apologise if is not.
As you can see in this image  https://i.imgur.com/iI00ErH.png , the program detects pokemon sun but for some reason doesn't allow me to edit , do you know what is it?

**Comment by kwsch** [comment]
romfs isn't clean; if you've unpacked any GARCs then the filecount doesn't match the expected count for Sun/Moon.

**Comment by renatosk** [comment]
Hmm , i dont do anything related to GARC files , but i think its the app that i used to dump my game (old version braindump) , do you recommend a other method to dump my game?

**Comment by kwsch** [comment]
Closing, please use the latest commits and refer to #93 for troubleshooting information.
