### ISSUE TITLE
Is there any method to Import/Export UI button Picture?

### ISSUE THREAD

**Issue by okt04175** [kwsch/pk3DS#84]
How to modify/replace the battle UI button(Pokemon,Bag,Run,Fight)? http://i.imgur.com/EsAoL8p.png
I just want to use the English Ver. battle UI  button replace Chinese Traditional Ver.&Chinese Simplified Ver.  battle UI  button,because i hate the Official translation.

**Comment by kwsch** [comment]
Same response as your previous issue (https://github.com/kwsch/pk3DS/issues/82)

>you can do most modifications by editing the images yourself. Unpack the GARC with pk3DS, edit the images, then rebuild the GARC.

pk3DS won't be an image editing suite; you have to unpack the files yourself and modify them, pk3DS will only assist with pack/repack.
