### ISSUE TITLE
SOS-Encounters not working

### ISSUE THREAD

**Issue by Vestolen** [kwsch/pk3DS#85]
After Randomizing wild encounters and sos encounters, no wild pokemon except for totem pokemon call for help, adrenaline orbs are usable, but seem to have no affect. Edit: Pokemon that usually appear in Alola call for help all others do not.

**Comment by sora10pls** [comment]
Call Rates need to be modified for every single Pokemon within the Personal editor, this is normal behaviour as you're not meant to find the Pokemon not native to Alola

**Comment by Vestolen** [comment]
I see. Thanks for the help
