### ISSUE TITLE
Pk3ds sun static encounters make the app crash

### ISSUE THREAD

**Issue by camacho1607** [kwsch/pk3DS#86]
ive been trying to randomize pokemon sun and wild encounters work well but when i try to randomize random encounters it says pk3ds has stopped working

**Comment by kwsch** [comment]
Are you using the latest commit? What settings are you using for the randomization? How has it stopped working (any error message)?

Please provide as much information as possible, can't do much with vague reports that X isn't working.

**Comment by camacho1607** [comment]
that's all that was happening was not a bague description no error message and it was clicking the static encounters button but i found out it was my fault for not dumping the game correctly
