### ISSUE TITLE
PK3DS Stops Working After Randomizing Wild Encounters

### ISSUE THREAD

**Issue by MidgeThePidge** [kwsch/pk3DS#88]
This is what happens after randomizing wild pokemon in the latest commit. I have no choice but to close the program.
![capture](https://cloud.githubusercontent.com/assets/25043681/21867805/41a74266-d826-11e6-97ef-ec6007c3d04d.JPG)

**Comment by kwsch** [comment]
What operating system is this? pk3DS needs a 64bit OS (32bit is insufficient due to RAM usage > 2GB).

May be worth debugging in an IDE (Visual Studio) to determine the actual error message.

**Comment by MidgeThePidge** [comment]
It's a 32-bit. That's the problem I guess.
