### ISSUE TITLE
NEED 32 BIT

### ISSUE THREAD

**Issue by nerfnotch22** [kwsch/pk3DS#89]
Hey, kwsh. plz plz im begging you i  need a 32 bit support. i spent weeks with no sleep just installing cfw just to find out that in the tutorial i was using that i downloaded pk3ds and im on 32 bit plz plz plz release both 32 and 64 bit  plz! oh and  pk3ds always crashed [as i used the june builds ] when i randomized the type chart it would crash. is it fixed?

**Comment by sora10pls** [comment]
Your problem with the Type Chart (build doesn't matter, pk3DS functioned the same way) was that it was located in a CRO, and you need to patch the RO module in order to load modified CROs (Luma3DS does this by default).

Also not gonna lie this comes off as a bit whiny lmao

**Comment by MidgeThePidge** [comment]
Yeah I'd like 32-bit support as well.

**Comment by evandixon** [comment]
"pk3DS needs a 64bit OS (32bit is insufficient due to RAM usage > 2GB)."
-@kwsch, #88
