### ISSUE TITLE
Does not start on Pokemon Sun Version 1.1

### ISSUE THREAD

**Issue by MidgeThePidge** [kwsch/pk3DS#90]
Pokemon Sun does not load after the 1.1 patch of the game. It gets stuck at a black screen when the game tries to load up. 

Luckily I have a tool to uninstall updates...

**Comment by kwsch** [comment]
Not pk3DS's problem.

Patches ignore base ROM files in favor of the patch contents if present. Don't mix/match files with saltySD etc redirection, as the code is expecting certain files. 

You'd need to do the same thing as is used for patched Gen6 games, which is unrelated to pk3DS.

**Comment by MidgeThePidge** [comment]
Would putting files from other games in the saltySD folder such as Smash Bros Mods mess up Pokemon Sun?

**Comment by kwsch** [comment]
The game tries to load 1.1 .code but your file redirection loads 1.0 .code; game crashes.
Either remove patch 1.1 or remove saltySD (play vanilla). You have to use saltySD to load the files that patch 1.1 provides instead.

Installed Patch + Redirection = no.

**Comment by MidgeThePidge** [comment]
So is there anyway to use PK3DS on 1.1?

**Comment by kwsch** [comment]
pk3DS doesn't care about the game-version/patch, it edits the files you give it.

Once the files are edited, pk3DS's job is done. It's up to you and other tools (like saltySD) to be set up / used in this scenario.
