### ISSUE TITLE
Wild enc., Trainer, static enc., move stats wont work on Sun

### ISSUE THREAD

**Issue by LightningRod33** [kwsch/pk3DS#93]
When I click the Wild Encounters, Trainer, Static Encounters, or Move Stats button, pk3ds crashes. I'm using Pokemon Sun. I really don't know what I'm doing wrong. Also, the TM/HM and Type Chart buttons aren't clickable. Someone please help. Thanks

**Comment by kwsch** [comment]
Compile from source or find the latest build, do not use out of date builds posted on random websites.

**Comment by LightningRod33** [comment]
Sorry if I'm sounding stupid, but how do you compile from source?

**Comment by kwsch** [comment]
[Visual Studio Community](https://www.visualstudio.com/downloads/)
[Download zip](https://github.com/kwsch/pk3DS/archive/master.zip) from [pk3DS's project page](https://github.com/kwsch/pk3DS) (green button on the right side)

install visual studio community, extract the zip, and open the sln/csproj with visual studio -> press Start in the top ribbon to run the program

**Comment by LightningRod33** [comment]
Thank you so much! I really appreciate your help.

**Comment by LightningRod33** [comment]
I really am sorry if I'm being annoying, but I need your help again. I ran the pk3ds with Visual Studio community, but the buttons still don't work. Do you think there's an issue with my rom? How can I fix it? Thank you so much. Even if this doesn't work, thanks for helping me out.

**Comment by kwsch** [comment]
Did you unpack the ROM?
(romfs & exefs in the same folder, select the parent folder as shown on the forums).

**Comment by LightningRod33** [comment]
Yup

**Comment by kwsch** [comment]
It's not a clean dump/unpack; things have been modified. 

You can try re-dumping or use the [latest commit (redownload zip)](https://github.com/kwsch/pk3DS/commit/30f43d060002a39da7b0d5f793efb6510da973b4) where I've added some error messages.

**Comment by LightningRod33** [comment]
Unfortunately it did not work. The error was: An unhandled exception of type 'System.IO.EndOfStreamException' occurred in mscorlib.dll   After that, it brings me to CTR.GARC unpackGARC (Stream stream) and lines 443 to 510 have garc hightlighted. Ex, in line 443, garc in garc.magic is highlighted. Do I have to redump the ROM?

**Comment by kwsch** [comment]
Need to re-dump your rom then. Could be that the past version you used had repacked incorrectly, or if you restored backups it may have goofed your GARCs.

**Comment by LightningRod33** [comment]
Thank so much for helping me. It really means a lot. :)
