### ISSUE TITLE
Starter editing does nothing on ORAS

### ISSUE THREAD

**Issue by thebeastgamer25** [kwsch/pk3DS#98]
see above. also, im patching to a cia.

**Comment by kwsch** [comment]
uninstall any game patches, they overwrite the base files which ignores your edits.

**Comment by thebeastgamer25** [comment]
What do you mean? What I mean by "patching" is extracting a dumped CIA, editing, rebuilding, and installing that.

**Comment by thebeastgamer25** [comment]
@kwsch What do you mean? What I mean by "patching" is extracting a dumped CIA, editing, rebuilding, and installing that.

**Comment by kwsch** [comment]
http://www.serebii.net/omegarubyalphasapphire/patch.shtml

**Comment by thebeastgamer25** [comment]
@kwsch Oh OK, but it will keep saying "UPDATE AVALIBLE", is there a a way you can change that?

**Comment by kwsch** [comment]
That question is not really related to pk3DS, you'd have to build a custom patch.

[GBATemp Tutorial](https://gbatemp.net/threads/tutorial-how-to-rebuild-a-custom-update-for-pok%C3%A9mon-xy-oras.391282/)
