### ISSUE TITLE
.cia files???

### ISSUE THREAD

**Issue by jjsr420** [kwsch/pk3DS#99]
I've looked, and looked. Is there a way to randomize .cia files?

**Comment by kwsch** [comment]
pk3DS deals with romfs/exefs, which are obtained by [extracting .3DS or .CIA files](https://gbatemp.net/threads/tutorial-how-to-decrypt-extract-rebuild-3ds-cia-cxi-files.383055/).

**Comment by jjsr420** [comment]
TY SO MUCH!
